### ISSUE TITLE
[bug] "Transfer amount too low" text is displayed in "Route" option after changing the network if wallet address was entered manually 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Transfer amount too low" text is displayed. Route is grayed out.

https://github.com/user-attachments/assets/cffa530b-b6b3-422c-90b2-53e3ad5a6150

Note: Issue is not reproducible using Phantom wallet. 

https://github.com/user-attachments/assets/29907848-cdf3-4123-ba71-dbb8a554f554

### Expected Behavior

"Transfer amount too low" text is not displayed. Route is not grayed out.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Prepare to send 5 FTM from Fantom (MetaMask) to Solana (Wallet address entered manually)
3. Change destination network to Osmosis 
4. Check the route

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Phantom
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by sebastianscatularo** [comment]
should be fixed once https://github.com/wormhole-foundation/wormhole-connect/pull/2347 get merged

**Comment by tsadovska** [comment]
Currently, the "Cosmos Gateway Manual route" option is displayed instead of the "Cosmos Gateway Automatic route" option.

![image](https://github.com/user-attachments/assets/680c69c1-489a-40f4-a5e7-b2756c1ba84e)


Ticket will be re-checked once https://github.com/XLabs/portal-bridge-ui/issues/1006 is solved.

**Comment by yuli-ferna** [comment]
@tsadovska Should be fixed! https://portalbridge.com/
<img width="732" alt="image" src="https://github.com/user-attachments/assets/cedfed81-9586-4363-bdcd-0c5bd230f3b7">

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/ [Mainnet]. 
Ticket is closed.
