### ISSUE TITLE
[bug] Manual wallet address input should not be possible when user selects 'Add <token> to the wallet' for a resumed transaction

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Switch to Manual Input" option is displayed.

https://github.com/user-attachments/assets/a44f0bd2-fdf6-425a-a1d0-9d38a6790715

### Expected Behavior

"Switch to Manual Input" option is not displayed, because user can enter a different wallet address. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Click on "Resume Transaction"
3. Search transaction by hash 0x157e370562bd4730b998a79f32d3e912fc9db42f5b2ca98b755f79b20a5b5d7f (Fantom)
4. Click on "Add <token> to your wallet" link
5. Check if "Switch to Manual Input" option is displayed

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by sebastianscatularo** [comment]
addressed at https://github.com/wormhole-foundation/wormhole-connect/pull/2348

**Comment by tsadovska** [comment]
Tested OK. 
Checked on https://preview.portalbridge.com/859350d189/. 
"Switch to Manual Input" option is not displayed on "Connect wallet" screen when user resumes transaction and then clicks on "Add <token> to your wallet" link. 
Ticket is closed.
