### ISSUE TITLE
[bug] WalletNotConnectedError when claiming asset on Solana when address was entered manually - CCTP Manual route

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails after clicking on "Claim" button. Please use [this link](https://drive.google.com/file/d/1yKPE0LEwP5rK06TGaet5XbhxMrYlP8oG/view?usp=sharing) to view the recording. 

```
WalletNotConnectedError
    at re.sendTransaction (solana-NB8VjGln-B4GPbAcJ.js:7:47857)
    at E.sendTransaction (solana-NB8VjGln-B4GPbAcJ.js:7:44740)
    at E.signAndSendTransaction (solana-NB8VjGln-B4GPbAcJ.js:7:44973)
    at Ne (solana-NB8VjGln-B4GPbAcJ.js:7:52973)
    at signAndSendTransaction (pb-index-CjRBRb8w.js:527:69281)
    at async CCTPManualRoute.redeem (pb-index-CjRBRb8w.js:534:75201)
    at async Operator.redeem (pb-index-CjRBRb8w.js:537:139006)
    at async Object.wo [as onClick] (pb-index-CjRBRb8w.js:764:1327)
```

![image](https://github.com/user-attachments/assets/0bd03fc7-edba-4057-8b46-28bd8cd81fd5)

### Expected Behavior

Transfer can be successfully finished. 

### Steps To Reproduce

1. Prepare to send 0.0001 USDC from Polygon (MetaMask) to Solana (Wallet address manually entered)
2. Click on wallet address in "To" section and select "Change wallet" option
3. Select Pontem wallet
4. Close Pontem notification
5. Click on "Approve and proceed with transaction" button
6. Click on "Claim" button

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Pontem
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

### Anything else?
Linked issue: https://github.com/XLabs/portal-bridge-ui/issues/992
_No response_

**Comment by sebastianscatularo** [comment]
should be resolved once https://github.com/XLabs/portal-bridge-ui/issues/999 is solved

**Comment by tsadovska** [comment]
Re-checked on https://preview.portalbridge.com/859350d189/. 
The transfer of USDC from Polygon (MetaMask) to Solana (manually entered wallet address) cannot be initiated.

![image](https://github.com/user-attachments/assets/c0a80dd6-76b9-4b4a-80e2-856064b0a6ee)


Ticket is closed.
