### ISSUE TITLE
[bug] Warning "No bridge or swap route available" does not disappear after changing the wallet

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Warning "No bridge or swap route available for selected tokens" is displayed. The "Approve and proceed with transaction" button becomes visible only after user clicks on "Manual Bridge" option. 

https://github.com/user-attachments/assets/821ed292-8893-4e74-aa9c-66df82f1ce37

### Expected Behavior

Warning "No bridge or swap route available for selected tokens" is no longer displayed. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Prepare to send 0.00001 SOL from Solana (Phantom) to Aptos (wallet address entered address)
3. Click on wallet address in "To" section and select "Change wallet" option from dropdown menu
4. Connect Pontem wallet
5. Check if warning is displayed

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Phantom, Pontem
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by yuli-ferna** [comment]
@tsadovska This should be fixed :) https://portalbridge.com/




https://github.com/user-attachments/assets/248752e7-88a0-4b71-bec2-07a7e0ca9219

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/.
Warning is no longer displayed after user enters wallet address manually and then changes a wallet.
Ticket is closed.
