### ISSUE TITLE
[bug] An error appears after clicking on "Create account" link if destination address was entered manually

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error appears in Console: 

```
Error: wallet.signAndSendTransaction is undefined
    at Ne (solana-4SlQZmA2-CEdK_Uie.js:7:52902)
    at signAndSendTransaction (pb-index-CZxC1Ciq.js:527:69330)
    at async Object.createAssociatedTokenAccount (pb-index-CZxC1Ciq.js:761:86349)
    at async vr (pb-index-CZxC1Ciq.js:761:84209)
```

![image](https://github.com/user-attachments/assets/4f4585be-884d-4a0e-b87d-22ba46e4b765)

### Expected Behavior

User is redirected to token registration page.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Prepare to send USDC (BSC) from BSC (MetaMask) to Solana (Wallet address entered manually)
3. Click on "Create account" link in warning "No associated token account exists for your wallet on Solana. You must create it before proceeding."

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.100 (Official Build) (arm64)
```

**Comment by bradstevens1** [comment]
@tsadovska Did you get it solved yet ?

**Comment by yuli-ferna** [comment]
@tsadovska This should be fixed https://portalbridge.com/

<img width="763" alt="image" src="https://github.com/user-attachments/assets/80a2bcef-3ec0-43df-b0bb-4bf9f07a6c40">
