### ISSUE TITLE
[bug] Incorrect text is displayed in route option - Cosmos Gateway route

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text "Cosmos Gateway Approve transfer with destination wallet" is displayed in route option, however no approval is needed on destination chain, token is received automatically. Please use [this link ](https://drive.google.com/file/d/1m5B0O9Tz9VCNy8IK-7Efa_Vuiyn7ReJy/view?usp=sharing)to view the recording. 

Note: Issue is not reproducible on https://portalbridge.com/ 

![Screenshot 2024-08-09 at 12 48 30](https://github.com/user-attachments/assets/59283929-b212-4ed7-88e8-adb368a8b624)

### Expected Behavior

Text "Cosmos Gateway Receive tokens automatically" is displayed in route option. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ 
2. Prepare to send 0.0001 WMATIC from Osmosis (Leap) to Kujira (Leap)
3. Check text on route option

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Leap
- Browser: Google Chrome Version 127.0.6533.100 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
Issue is also reproducible when sending asset from EVM chain to Cosmos chain, for example 5 FTM from Fantom to Osmosis. Manual route is shown instead of Automatic route. 

![Screenshot 2024-08-09 at 15 23 39](https://github.com/user-attachments/assets/fbda0f85-ede8-46e0-b953-e204630fa2a5)

**Comment by danielisaacgeslin** [comment]
@tsadovska  @yuli-ferna  i moved this one to QA cause it seems fix on the latest version of connect `0.3.19-beta.9-development`. The preview in the ticket points to an older one `0.3.19-beta.7-development`

**Comment by yuli-ferna** [comment]
@tsadovska it should be fixed :)

<img width="713" alt="image" src="https://github.com/user-attachments/assets/c0b283cf-0a26-480a-b368-85eb13436bc2">

**Comment by tsadovska** [comment]
Thank you! Closing the ticket.
