### ISSUE TITLE
[bug] Warning "Sanctioned target address" is no longer displayed after network is changed

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Warning "Sanctioned target address" is no longer displayed after network is changed. Please use [this link](https://drive.google.com/file/d/1VVet6kcUKNtbM7sJVQq7d0uPqlfh57AW/view?usp=sharing) to view the recording.

![image](https://github.com/user-attachments/assets/6e7b301f-9edb-4f0a-abd6-8a7bcdec566c)

### Expected Behavior

Warning "Sanctioned target address" is displayed. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ 
2. Prepare to send 0.01 AVAX from Avalanche (MetaMask) to Fantom (Wallet address from https://github.com/ultrasoundmoney/ofac-ethereum-addresses, 0x1da5821544e25c636c1417ba96ade4cf6d2f9b5a)
3. Click on "Approve and proceed with transaction" button
4. Change Fantom network to Celo
5. Click on "Approve and proceed with transaction" button
6. Check if warning "Sanctioned target address" is displayed

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.100 (Official Build) (arm64)
```

**Comment by yuli-ferna** [comment]
@danielisaacgeslin, what you say is true, but for now, to avoid interacting with sanctioned wallets, I am consulting on Ethereum also when it is an evm.

@tsadovska This should be fixed 

https://github.com/user-attachments/assets/68cf67f5-c5fc-4058-b5c2-286929ef924a

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/. 
Warning "Sanctioned target address" is displayed when account from https://github.com/ultrasoundmoney/ofac-ethereum-addresses page is entered. 
Ticket is closed.
