### ISSUE TITLE
[bug] "Amount" and "Gas fee" are not shown in "To" section when sending asset to Injective

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Amount" and "Gas fee" are not shown in "To" section.

Error in Console:
```
Error: Invalid string. Length must be a multiple of 4
    at getLens$1 (pb-index-D9hVyd9l.js:134:102015)
    at Object.toByteArray$1 (pb-index-D9hVyd9l.js:134:102330)
    at fromBase64$1 (pb-index-D9hVyd9l.js:519:158882)
    at decodeAttribute$1 (pb-index-D9hVyd9l.js:522:46052)
    at Array.map (<anonymous>)
    at decodeAttributes$4 (pb-index-D9hVyd9l.js:522:46248)
    at decodeEvent$4 (pb-index-D9hVyd9l.js:522:46343)
    at Array.map (<anonymous>)
    at decodeEvents$4 (pb-index-D9hVyd9l.js:522:46487)
    at decodeTxData$4 (pb-index-D9hVyd9l.js:522:46734)

```

![image](https://github.com/user-attachments/assets/6a693980-cb37-4468-a895-e3bc0c9f8e37)

### Expected Behavior

"Amount" and "Gas fee" are shown in "To" section.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/41c5f197e5/
2. Prepare to send 0.0001 WMATIC from Solana (Phantom) to Injective (Leap)
3. Click on "Approve and proceed with transaction" button
4. Check if "Amount" and "Gas fee" are shown in "To" section

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Phantom, Leap
- Browser: Google Chrome Version 127.0.6533.100 (Official Build) (arm64)
```

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/41c5f197e5/. 

- Sending 0.1 USDC from [Polygon](https://polygonscan.com/tx/0x0f7f480e116ba99c6aec0d947da178faa2eb7f1ea46e5864d3545252c26e427a) (MetaMask) to [Injective](https://explorer.injective.network/transaction/DAE912BEF1188B2D36D20EFA618A3BFBAA92DAEFD660C4D3010BA671BABAF447/) (Injective wallet address entered manually) 
- Sending 0.1 CELO from [Moonbeam](https://moonscan.io/tx/0x4d3ae9af8422d1fda111ba21ab7295d624306cce76d1ce7416f0512fe5fa6109) (MetaMask) to [Injective](https://explorer.injective.network/transaction/A53314A1AAA7DB6511D499ECF7C1CBD98537194D90E3F278CC865669744882B1/) (Leap).

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/321a610744/ and https://portalbridge.com/. 
Scenario checked: USDT from [Osmosis](https://www.mintscan.io/osmosis/transactions/7BC71041DBEF6642B41E3E71CB1BD8B3DB7529EDE5020D9E05149E5122CECA25) (Leap) to [Injective](https://explorer.injective.network/transaction/FBF13C9C51AFE0D8FDED38FE46E6CD9B0DC6B1287D1305BAEF0004E49B2742A8/) (Leap) 0.0001 USDT


![image](https://github.com/user-attachments/assets/865c6252-7723-4ace-9609-17368c6ba46a)

**Comment by tsadovska** [comment]
Closing the ticket, because currently Osmosis and Injective networks are not displayed in the networks list on https://portalbridge.com/.
