### ISSUE TITLE
[bug] URL remains unchanged and warning pop-up doesn't appear after clicking on Back button

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The URL remains unchanged, and the warning pop-up "Changes that you made may not be saved" does not display when the user clicks the Back button.

https://github.com/user-attachments/assets/58529a0c-fd09-40ca-8767-2fe4f28d2bbd

### Expected Behavior

Warning "Changes that you made may not be saved" is displayed or user is redirected to https://portalbridge.com/.

![image](https://github.com/user-attachments/assets/a070444e-b91c-46ec-9198-f6fc8d61340e)

### Steps To Reproduce

1. Open https://portalbridge.com/?sourceChain=solana&transactionId=5c1JYBCURihQZ2LHmonGzYZWRLKAQuAVtwnXFiFP6bBCWhRzFL2rKV1wM8px891bGw1GCTC7jCyGcCdEeT7sGbgs
2. Click on Back button

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: - 
- Browser: Google Chrome
```

**Comment by sebastianscatularo** [comment]
due technical limitations we can not address it easily, I'm going to close it and we could discuss it in our sync next week
