### ISSUE TITLE
[bug] Validation error during transfer to X Layer

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails. 
Error in Console:
```
Error validating transfer {chain: '', address: '0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012', error: TypeError: (intermediate value) is not iterable
    at isSanctioned (https://preview.portalbridge.c…}
```

![image](https://github.com/user-attachments/assets/817d34b9-ef83-4ec9-8fc1-05da9ecf0771)

### Expected Behavior

Transaction proceeds without errors. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/321a610744/
2. Prepare to send 0.001 WFTM from Fantom (MetaMask) to X Layer (MetaMask)
3. Click on "Approve and proceed with transaction" button

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.120 (Official Build) (arm64)
```

### Anything else?

Issue is also reproducible during following transferts:
* BNB from BSC (MetaMask) to X Layer (MetaMask)
* WGLMR from Avalanche (MetaMask) to X Layer (MetaMask)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/321a610744/ (Portal Bridge: v0.2.15-P7451a01963, Wormhole Connect: v^0.3.20-beta.3-development).

An error appears in Console after clicking on Approve button:
```
Error validating transfer {chain: '', address: '0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012', error: TypeError: (intermediate value) is not iterable
    at isSanctioned (https://preview.portalbridge.c…}
```

![image](https://github.com/user-attachments/assets/6bec4718-ff8a-4a09-aab4-b395ef265061)

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/321a610744/ (Portal Bridge: v0.2.15-P22997d4780, Wormhole Connect: v^0.3.20-beta.4-development). 

- 0.001 WFTM from [Fantom](https://ftmscan.com/tx/0xfeb0ee082149b7f312a12c5566a17a8dcc1ca8b0b2f75f00d84c6c35b0877a8c) (MetaMask) to [X Layer](https://www.okx.com/web3/explorer/xlayer/tx/0x99172c2f1d96664fbb233a30ad5244cefa9131465577bca408d21d9fe2b49080) (MetaMask) - successful 
- 0.0001 BNB from [BSC](https://bscscan.com/tx/0x2a9030ff9f15d5c3cd335168eac264b3e0dfcc419860d759fb45318a6022e936) (MetaMask) to [X Layer](https://www.okx.com/web3/explorer/xlayer/tx/0x2183fda07840f75ae26ab816a4fe5959f7be4980fea3da12262071de19f5b673) (MetaMask) - successful 
- 0.01 WGLMR from [Avalanche](https://avascan.info/blockchain/c/tx/0x433b72f18f97aa1f2313b716f6b9646bdf4165bef9e1bfc398d565383edf3708) (MetaMask) to [X Layer](https://www.okx.com/web3/explorer/xlayer/tx/0x666a015e74306438a38e66f5a6a7d899a6a49ac17a2035161f8ae899c2e2fd0c) (MetaMask) - successful

There was no error in the console and the transactions were successfully completed. 
The ticket can be closed.
