### ISSUE TITLE
[support] Cannot claim on BNB chain, transaction routed through wormhole gateway transfer <Discord ID - 1079917462881058876>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#1026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain: Base
- Source Chain Wallet: Metamask 
- Target Chain: BNB
- Target Chain Wallet: Metamask 
- Asset Type: Token
- Tx: https://basescan.org/tx/0xa6f57ba1730b18a04954a3403c34265e6d4bae8d8d21d3e1862ff42530eee9f8
```

### Current Behavior

Error comes up immediately after clicking on the claim button, no wallet prompt to approve a transaction.
![26a241a622e13996d5cc05e721ff32a2-1](https://github.com/user-attachments/assets/5750c581-4345-484b-a206-429d9e2952e1)

### Expected Behavior

Clicking on the claim button should prompt a wallet approval for the transaction.

### Anything else?

The transfer was routed through wormhole gateway; https://wormholescan.io/#/tx/0xa6f57ba1730b18a04954a3403c34265e6d4bae8d8d21d3e1862ff42530eee9f8
![img_20240811_171544](https://github.com/user-attachments/assets/f5da70c9-a718-4a52-b10f-0dc9ac695fda)

**Comment by mliu-xlabs** [comment]
Note here - not sure why a Base to BSC transfer went through gateway, as it should not have gone through gateway at all. I also notice that its a payload v3, which doesn't make sense here either. Looking at whscan, I did not find other instances of this

**Comment by sebastianscatularo** [comment]
we has been able to reproduce it 

- https://wormholescan.io/#/tx/0x62832d930dbd53d4a0a0cbaebe3d75338029a8136aa8bbc50e090b9e6a64c643?view=advanced

Steps to reproduce:
- Select an evm source chain
- Select cosmos a target chain
- Set networking throttling
- Select an evm chain again
- Click on approve and procced
- Wait for it
-

**Comment by sebastianscatularo** [comment]
PR to prevent this issue in the future https://github.com/wormhole-foundation/wormhole-connect/pull/2429

**Comment by tsadovska** [comment]
Fix looks good on https://preview.portalbridge.com/b3b7091778/, checked with 3G network throttling. Info "Resolving available routes" is shown and "Approve and proceed with transaction" button is not displayed until routes are resolved.


![Screenshot 2024-08-27 at 11 27 28](https://github.com/user-attachments/assets/754edd4b-13f0-4267-87b2-739339f6c083)

**Comment by sebastianscatularo** [comment]
Fix has been deployed
