### ISSUE TITLE
[bug] WKLAY and wrapped tokens balances are not loading on Klaytn

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WKLAY and wrapped tokens balances are not loading on Klaytn.

```
Failed to get token balances Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x5b08ac39EAED75c0439FC750d9FE7E1F9dD0193F","data":"0x1ff1e2860000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","accessList":null}, error={"code":-32062}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Cm.makeError (pb-index-CQl3SLEd.js:349:47781)
    at Cm.throwError (pb-index-CQl3SLEd.js:349:47914)
    at checkError$1 (pb-index-CQl3SLEd.js:359:89511)
    at JsonRpcBatchProvider.<anonymous> (pb-index-CQl3SLEd.js:359:100402)
    at Generator.throw (<anonymous>)
    at Gn (pb-index-CQl3SLEd.js:359:88786)
```

![image](https://github.com/user-attachments/assets/2f8be196-ac56-49ae-a1da-07b43b6f18c0)

### Expected Behavior

Token balances are displayed.

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Select Klaytn as source chain
3. Connect MetaMask wallet
3. Open Assets list

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.120 (Official Build) (arm64)
```

**Comment by danielisaacgeslin** [comment]
https://github.com/wormhole-foundation/wormhole-connect/pull/2423

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 


![image](https://github.com/user-attachments/assets/1c96df7a-5d8a-49ba-8d7d-7e5919767513)


Closing the ticket.

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/.
Issue is reproducible again. WKLAY and wrapped tokens balances are not loading on Klaytn.

Attachment:
<img width="1439" alt="Screenshot 2024-09-09 at 09 48 49" src="https://github.com/user-attachments/assets/06f990e2-8532-48bc-a5be-c278e259a8fd">
