### ISSUE TITLE
[bug] Incorrect token search result

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PYTH asset with contract address `0xFa4B761A1e07909Ba31331a5dfa12390E3ff5583` is found using `HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3` contract address.

![image](https://github.com/user-attachments/assets/67c2a950-e23a-4583-acd5-3d5a9e796aca)

### Expected Behavior

Token can be found only by contract address that is displayed in the option.

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Select Polygon as source chain and connect MetaMask wallet
3. Open Assets list
4. Search PYTH asset by token name
5. Check that option displays the contract address "0xFa4B...5583"
6. Enter different contract address, HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3
7. Check if PYTH asset is found

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.120 (Official Build) (arm64)
```

**Comment by danielisaacgeslin** [comment]
@tsadovska this is correct

* `HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3` this is PYTH address on its native chain (solana)
* `0xFa4B761A1e07909Ba31331a5dfa12390E3ff5583` this is PYTH address on polygon

Search is matching using both addresses so it's easier to find even if you're not sure what address is the appropriate one in that context

**Comment by tsadovska** [comment]
Thank you for the explanation!
Ticket is closed.
