### ISSUE TITLE
[bug] USDC.e (Polygon) asset is not displayed in the list

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

USDC.e (Polygon) asset is not displayed in the list.
Contract address: 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174, asset in [Explorer](https://polygonscan.com/token/0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174).
Previously, USDC.e (Polygon) asset was displayed in the list. 

![Screenshot 2024-08-21 at 14 15 04](https://github.com/user-attachments/assets/323da122-614d-4174-9419-42f58cb926eb)

### Expected Behavior

USDC.e (Polygon) asset is displayed in the list.

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Select Polygon as source chain
3. Connect MetaMask wallet
4. Open Assets list
5. Check if USDC.e asset is displayed in the list 

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.120 (Official Build) (arm64)
```

**Comment by danielisaacgeslin** [comment]
this is being intentionally omitted

https://github.com/wormhole-foundation/wormhole-connect/blob/release/wormhole-connect/src/config/utils.ts#L73

![image](https://github.com/user-attachments/assets/7eab721f-1d39-4a9a-be23-c09039342bb7)

**Comment by tsadovska** [comment]
Rechecked on https://portalbridge.com/. 
[USDC.e](https://polygonscan.com/address/0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174) token is displayed in the list.

![image](https://github.com/user-attachments/assets/39c91913-7a2e-4fec-b54a-175e650b9519)
