### ISSUE TITLE
[bug] Cannot add WETH (BSC) token to the wallet

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error appears in Console:
`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WETH) does not match the symbol in the contract (ETH)'}`

![Screenshot 2024-08-21 at 15 35 45](https://github.com/user-attachments/assets/72523c92-7fb3-4034-a065-5a281ba26b97)

### Expected Behavior

Token is successfully added to the wallet.

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Send 0.0001 WETH (Polygon) from Polygon (MetaMask) to BSC (MetaMask)
3. Click on "Add WETH (BSC) to your wallet" link

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.120 (Official Build) (arm64)
```

**Comment by danielisaacgeslin** [comment]
https://api.coingecko.com/api/v3/coins/bsc/contract/0x2170Ed0880ac9A755fd29B2688956BD959F933F8

<img width="614" alt="image" src="https://github.com/user-attachments/assets/ce0038c2-56d1-4123-8039-fe1369e8a466">

**Comment by tsadovska** [comment]
Issue is no longer relevant after redesign. Closing the ticket.
