### ISSUE TITLE
[bug] - Token verifier for Injective USDCet asset is not working as expected

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#104]
Current behavior:

using https://www.portalbridge.com/#/token-origin-verifier a user can not verify that 
`inj1q6zlut7gtkzknkk773jecujwsdkgq882akqksk` is a wrapped wormhole USDCet asset

Steps:

1 - Verify it is the right contract on Injective for USDCet

2 - if it is the right contract fix token verifier to report the origin contract on each chain

Technical Note:

check https://etherscan.io/address/0x3ee18b2214aff97000d974cf647e7c347e8fa585#readProxyContract#F28

**Comment by raop155** [comment]
After doing some testing I found out this:

When trying to call method: `queryExternalIdInjective` from "@certusone/wormhole-sdk", always returns `null`


## Test data:

Input:
```
 {
    "client": {
        "module": "chain-wasm",
        "client": {
            "rpc": {
                "host": "https://k8s.mainnet.chain.grpc-web.injective.network/",
                "options": {},
                "module": ""
            }
        }
    },
    "tokenBridgeAddress": "inj1ghd753shjuwexxywmgs4xz7x2q732vcnxxynfn",
    "assetAddress": "0080ea0471ebb1df0e84542b39394740e6d61c82f1b5c91d6ffa2a184db57cad"
}
```

Output: `null`

**Comment by sebastianscatularo** [comment]
we expect this PR to fix the issue https://github.com/wormhole-foundation/wormhole/pull/2961
