### ISSUE TITLE
Migrate from Material UI v4 to v5

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#105]
Migrate Material UI from v4 to v5

`Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.`

https://mui.com/material-ui/migration/migration-v4/

**Comment by mliu-xlabs** [comment]
@sebastianscatularo what are the downsides of not supporting this? how long will it take to upgrade?

**Comment by sebastianscatularo** [comment]
we could stop receiving bug fixes from the team maintaining the lib and that could increase the amount of work on our side, also the dependencies that this lib use could start getting deprecated, and we could start getting exposed to bugs, it is a matter of maintaining the base code.

**Comment by mliu-xlabs** [comment]
deprecating
