### ISSUE TITLE
[bug] Arrow keys should not be appearing in input field

### ISSUE THREAD

**Issue by Wesleyleung** [XLabs/portal-bridge-ui#1057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Describe the current behavior in detail

<img width="628" alt="Screenshot 2024-09-11 at 5 12 46 PM" src="https://github.com/user-attachments/assets/5aa94d52-13a0-4b12-8cf1-04fb2e76f761">

This seems to be only affecting Portal.

### Expected Behavior

The up/down arrows shouldn't appear in the Amount input field

### Environment

```markdown
- OS:
- Wallet:
- Browser:
```

**Comment by sebastianscatularo** [comment]
addressed at https://github.com/wormhole-foundation/wormhole-connect/pull/2627

**Comment by sebastianscatularo** [comment]
related to https://github.com/wormhole-foundation/wormhole-connect/issues/2573, so, closing it for now
