### ISSUE TITLE
[bug] Wallet address has inconsistent font style

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wallet address has inconsistent font style. 

![Screenshot 2024-09-12 at 09 29 07](https://github.com/user-attachments/assets/17eda4d5-9e02-4be9-906b-262c9fa0680c)

### Expected Behavior

All page elements use the same font style.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/0af992dedf/
2. Select Ethereum wallet
3. Connect MetaMask wallet
4. Check wallet address font style

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (arm64)
```

**Comment by Wesleyleung** [comment]
Agree, this looks like Portal issue. Not sure why it does not match what it appears in Connect.

<img width="1070" alt="Screenshot 2024-09-12 at 8 58 42 PM" src="https://github.com/user-attachments/assets/ab40fd16-c6d5-400e-b54c-0f7724077288">

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/b1f3c5115d/. 

![image](https://github.com/user-attachments/assets/93e3af1c-478a-48ee-b224-aae828cc0cae)


Closing the ticket.
