### ISSUE TITLE
[bug] Inconsistent Design - tBTC Bridge page has old design for transactions

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The tBTC Bridge page has the old design for transactions, leading to inconsistency in the user interface.

<img width="1439" alt="Screenshot 2024-09-12 at 09 48 35" src="https://github.com/user-attachments/assets/491491df-7fd8-48b7-97fb-6afa1dc67337">

### Expected Behavior

The tBTC Bridge page should have the same updated design for transactions as the other bridge pages.

<img width="1440" alt="Screenshot 2024-09-12 at 09 40 15" src="https://github.com/user-attachments/assets/bed85b1b-f2bf-48ff-89f6-623d6dbb0aef">

### Steps To Reproduce

1. Open https://preview.portalbridge.com/0af992dedf/
2. Select tBTC tab on the left side of the page
3. Compare the transaction design with other bridge pages (e.g., Bridge tab, USDC tab).

### Environment

```markdown
- OS: macOS Sonoma 14.6.1
- Wallet: -
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (x86_64)
```

**Comment by mliu-xlabs** [comment]
This is currently intentional. closing ticket
