### ISSUE TITLE
[bug] Styling for tokens and network is incorrect

### ISSUE THREAD

**Issue by Wesleyleung** [XLabs/portal-bridge-ui#1066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are extra visible borders between the chain and tokens

<img width="1190" alt="Screenshot 2024-09-12 at 8 52 32 PM" src="https://github.com/user-attachments/assets/d0ca2408-ef0b-4262-ac8f-e0e316a8e3bc">

### Expected Behavior

This is what is looks like on the latest version of Connect. Can we investigate why Portal is different?
<img width="1020" alt="Screenshot 2024-09-12 at 8 52 21 PM" src="https://github.com/user-attachments/assets/1c7c6302-71d0-4d3b-9ce2-82b0f439f387">

### Steps To Reproduce

Select any asset/chain pair on the preview of Portal: https://preview.portalbridge.com/b1f3c5115d/

### Environment

```markdown
- OS:
- Wallet:
- Browser:
```

**Comment by yuli-ferna** [comment]
@Wesleyleung 
It should be fixed :)
https://preview.portalbridge.com/b1f3c5115d/
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/2eeb3f88-7bde-48e5-b15b-422f33478087">
