### ISSUE TITLE
Access to SUI bridge not available from PTB on mobile

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#107]
**Environment:** https://www.portalbridge.com/#/transfer

**S.O:** iOs (iphone 11) + chrome

**Steps**
1. Go to https://www.portalbridge.com/#/transfer
2. Observe the header
3. Click on 

**Obtained result:**
From the Portal Token Bridge  the link to SUI Bridge is not visible for mobile devices.

**Evidence**

https://user-images.githubusercontent.com/69044575/236938912-1b2b6315-33e7-45e6-90ef-7ec6dffea9c6.MP4

![IMG_7160](https://user-images.githubusercontent.com/69044575/236939132-7874430a-1317-4e6a-bb5e-45be7ea2e96b.jpg)

**Comment by sebastianscatularo** [comment]
@SamantaCasal it is working as expected, we could review the UI in the future, but for now, I'm going to close it, and I've opened another issue to track the enhance https://github.com/XLabs/portal-bridge-ui/issues/122
