### ISSUE TITLE
[bug] CTA and other accent elements are grey vs the theme style

### ISSUE THREAD

**Issue by Wesleyleung** [XLabs/portal-bridge-ui#1077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When all the accents are grey, the user cannot tell the difference between whether the button is disabled or not. 

<img width="1644" alt="Screenshot 2024-09-15 at 11 49 04 PM" src="https://github.com/user-attachments/assets/0c9f0f13-ffb9-49cb-a4da-f991cd02a070">

### Expected Behavior

They should be using the theme color, not gray. Look at the CTA button for example

<img width="973" alt="Screenshot 2024-09-15 at 11 50 03 PM" src="https://github.com/user-attachments/assets/b87e38a2-2da4-4c86-aba8-8b30d3f16fc3">

### Environment

```markdown
- OS:
- Wallet:
- Browser:
```

**Comment by sebastianscatularo** [comment]
@Wesleyleung as we discussed, we've reset the styles to the default connect color, that did make dropdown visible and removed the gray at buttons, could this issue be considered as addressed?

**Comment by sebastianscatularo** [comment]
https://preview.portalbridge.com/b1f3c5115d/

**Comment by Wesleyleung** [comment]
Great!
