### ISSUE TITLE
[bug] Default dark background for container can be hard to see against Portal background

### ISSUE THREAD

**Issue by Wesleyleung** [XLabs/portal-bridge-ui#1078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Connect's default container color is a dark purple/translucent black rgb(24, 26, 45). When this container is placed over the Portal website's background, it may make the input fields for Connect hard to see. 

<img width="1016" alt="Screenshot 2024-09-15 at 11 57 58 PM" src="https://github.com/user-attachments/assets/d14e7b11-49d9-431a-8b52-98b82f61250b">

### Expected Behavior

Consider using a lighter Connect container background. At the minimum, could use the slightly lighter container color used in today's Portal.

<img width="1101" alt="Screenshot 2024-09-15 at 11 59 14 PM" src="https://github.com/user-attachments/assets/81287801-4014-4842-9a21-8ceb42cf77db">

### Environment

```markdown
- OS:
- Wallet:
- Browser:
```

**Comment by sebastianscatularo** [comment]
@Wesleyleung as we discussed, we've reset the styles to the default connect color, that did make dropdown visible and removed the gray at buttons, could this issue be considered as addressed?

**Comment by sebastianscatularo** [comment]
https://preview.portalbridge.com/b1f3c5115d/
