### ISSUE TITLE
[bug] Error "Wormhole Connect: error completing transfer" when sending USDC from Base

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error message "Error with transfer, please try again" is displayed, despite the transaction being successfully completed and the USDC arriving in the Arbitrum account (by checking transaction history and arbitrum account).

```
Wormhole Connect: error completing transfer Error: not coalesce error (error={ "code": -32603, "data": { "cause": null, "error": {"code": -32016, "message": "over rate limit" }, "id": 1954141174, "jsonrpc": "2.0"}, "message": "Non-200 status code: '429'" }, payload={ "id": 33, "jsonrpc": "2.0","method": "eth_getTransactionReceipt", "params": ["Q@x718482e59b78fe6414634cc18e43b0f56b524e1707d371a3bad43a557d131bd7" ] },code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (pb-index-B3KkGTnC.js:273:19452)
    at Ys.getRpcError (pb-index-B3KkGTnC.js:274:212791)
    at Ys.getRpcError (evm-C7Q3nys6-Cbgnhi2k.js:7:1702)
    at pb-index-B3KkGTnC.js:274:215073
``` 

```
MetaMask - RPC Error: Non-20@ status code: '429' 
``` 
<img width="1440" alt="Screenshot 2024-09-16 at 16 44 16" src="https://github.com/user-attachments/assets/26049b13-e76f-431e-af48-7bc2f5bcebc7">

<img width="1440" alt="Screenshot 2024-09-16 at 16 49 05" src="https://github.com/user-attachments/assets/7ca10d5a-0a77-4553-8194-29b4f5b644ee">

### Expected Behavior

The transactions should proceed without any error messages.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/b1f3c5115d/usdc-bridge/
2. Prepare to send 1 USDC from Base (MetaMask) to Arbitrum (MetaMask)
3. Put "Gas" on 10%
4. Initiate the transfer
5. Observe the error message displayed: "Error with transfer, please try again."
6. Check "Transaction history" and the Arbitrum account to confirm that the transaction has started and 1 USDC has been received into the account

### Environment

```markdown
- OS: macOS Sonoma 14.6.1
- Wallet: MetaMask
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (x86_64)
```

### Anything else?

- Send tx from: [Base](https://basescan.org/tx/0x718482e59b78fe6414634cc18e43b0f56b524e1707d371a3bad43a557d131bd7)
- Send tx to: [Arbitrum](https://arbiscan.io/tx/0x3bb3d97541e18aa7f8f62af16d6e230ac852b3c7b07d4af1fa7f5fb30133c758)
- [Wormholescan](https://wormholescan.io/#/tx/0x718482e59b78fe6414634cc18e43b0f56b524e1707d371a3bad43a557d131bd7)

**Comment by kev1n-peters** [comment]
My TX went through successfully: https://wormholescan.io/#/tx/0xd45ebecd3df393303bf898820dbcec00f7f846825e3f580647d097d30d76c010. Looking at the RPC error you got, I see `"message": "over rate limit"` which looks like the RPC rate limited the request. This was likely just an intermittent issue and not a bug in the code.

**Comment by agodlevska** [comment]
Re-checked on https://preview.portalbridge.com/b1f3c5115d/usdc-bridge/. 
The issue is no longer reproducible. The transaction of 1 USDC from Base (MetaMask) to Arbitrum (MetaMask) was successfully started and completed without any errors.  

Attachment:
<img width="1440" alt="Screenshot 2024-09-19 at 16 35 43" src="https://github.com/user-attachments/assets/b7bdab0f-9b11-4d97-8290-83149420838f">
