### ISSUE TITLE
[bug] Link to register a token is not clickable

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Link to register a token is not clickable. Please use [this link](https://drive.google.com/file/d/1YcIv0A-jx9Be7XUB5GuN45jT8MvMpfqe/view?usp=sharing) to view the recording.

![Screenshot 2024-09-17 at 17 46 00](https://github.com/user-attachments/assets/f958b9df-3b0e-49ec-b8df-52fa0579fae7)

### Expected Behavior

User is redirected to "Token registration" page. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/b1f3c5115d/
2. Prepare to swap USDC (0xA0...eB48) from Ethereum (MetaMask) to USDC (0x37...5cAd) on Celo (MetaMask)
3. Click on "register" link

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (arm64)
```

**Comment by kev1n-peters** [comment]
Fixed in https://github.com/wormhole-foundation/wormhole-connect/pull/2629

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/b1f3c5115d/. 

![image](https://github.com/user-attachments/assets/27ff2416-bbdb-4214-9813-372bb95a0b62)

Closing the ticket.
