### ISSUE TITLE
[bug] User can start transaction without registering token

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User can initiate the transfer when warning to register token is displayed. Link to [Wormholescan](https://wormholescan.io/#/tx/0x4ce27581c9fe16d409f19328ac6ac19721d3b3a71537366c73ffeba2b3f48e34).

Please use [this link ](https://drive.google.com/file/d/1NiQo1wTIc6MFk01NbHUVWsFxU6TB1G_V/view?usp=sharing)to view the recording. 

![Screenshot 2024-09-17 at 18 37 43](https://github.com/user-attachments/assets/2ee75c1c-72a8-4bb2-addf-a59eeb588400)

### Expected Behavior

User can initiate the transfer only after token is registered. 
Warning to register token should not be displayed when token is registered. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/b1f3c5115d/
2. Prepare to swap USDC (0xA0...eB48) from Ethereum to USDC (0x37...5cAd) on Celo (MetaMask)
3. **Observe that warning to register token is displayed**
4. Enter Amount, in my case 0.001
5. Select Manual route option
6. Click on "Review transaction" button
7. Click on "Confirm transaction" button
8. Confirm transfer in the wallet

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (arm64)
```

**Comment by kev1n-peters** [comment]
We shouldn't even be displaying that warning ever since the wrapped asset must exist for the route to even show up.
