### ISSUE TITLE
[bug] [High priority] Mayan MCTP route is not suggested

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mayan MCTP route is suggested on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQHUAEoZPnL1yEYDCKgAqOzFqwKQejYAkjIqALogAL5AA%3D%3D%3D) (Connect v2), but is not available on https://preview.portalbridge.com/b1f3c5115d/.

![Screenshot 2024-09-17 at 19 56 29](https://github.com/user-attachments/assets/c9a92df6-876b-4831-bee3-13d51cd445fa)

### Expected Behavior

Mayan MCTP route is suggested.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/b1f3c5115d/
2. Prepare to send 0,026964 ETH from Base (MetaMask) to Arbitrum (MetaMask)
3. Check suggested routes

### Environment

```markdown
- OS: mascOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (arm64)
```

**Comment by Wesleyleung** [comment]
This seems like a high priority issue to me.

**Comment by Wesleyleung** [comment]
this should be fixed now.
<img width="456" alt="Screenshot 2024-09-19 at 5 01 51 PM" src="https://github.com/user-attachments/assets/4a91e5a3-32a5-4717-82d8-c5ba3aa4c669">

**Comment by tsadovska** [comment]
"Mayan Swift" and "Mayan MCTP" routes are displayed on https://preview.portalbridge.com/b1f3c5115d/ when sending ETH from Base (MetaMask) to Arbitrum (MetaMask).
