### ISSUE TITLE
[bug] "tBTC Transfer" page should not contain Circle icon in the footer

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"tBTC Transfer" page contains Circle icon in the footer. 

![Screenshot 2024-09-20 at 15 50 12](https://github.com/user-attachments/assets/87ce12cb-8258-406c-ae7f-f2a3e4e728a7)

### Expected Behavior

"tBTC Transfer" page should not contain Circle icon in the footer. 

### Steps To Reproduce

1. Open https://portalbridge.com/tbtc-bridge/
2. Check the footer 

### Environment

```markdown
- OS: macOS Sonoma 14.5 
- Wallet: - 
- Browser: Google Chrome Version 129.0.6668.59 (Official Build) (arm64)
```

**Comment by sebastianscatularo** [comment]
should be addressed once https://github.com/XLabs/portal-bridge-ui/pull/1103 gets merged

**Comment by tsadovska** [comment]
Thank you for the fix! 
Looks great on https://portalbridge.com/tbtc-bridge/.
