### ISSUE TITLE
[bug] Can't bridge from/to osmosis anymore

### ISSUE THREAD

**Issue by rube-de** [XLabs/portal-bridge-ui#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Osmosis network isn't selectable.
neither on https://portalbridge.com/?sourceChain=cosmos which is the link for cosmos on https://portalbridge.com/advanced-tools/
nor on https://www.portalbridge.com/cosmos/ which is found on https://portalbridge.com/docs/tutorials/how-to-bridge-to-osmosis

### Expected Behavior

Osmosis network is selectable like in the tutorial docs

### Steps To Reproduce

1. go on https://portalbridge.com/docs/tutorials/how-to-bridge-to-osmosis
2. click on https://www.portalbridge.com/cosmos/
3. osmosis can't be selected

same
1. go on https://portalbridge.com/advanced-tools/
2. select "cosmos"
3. osmosis can't be selected

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet:
- Browser: Brave 1.70.117
```

**Comment by LIU9293** [comment]
+1

**Comment by sebastianscatularo** [comment]
@LIU9293 @rube-de https://portalbridge.com/cosmos/ app is available to use now, sorry for the inconvenience  :)
