### ISSUE TITLE
[bug] Text has invisible color on "Claim" button

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text is not visible on "Claim" button. 

![image](https://github.com/user-attachments/assets/f1d4bbeb-9e8b-4eeb-8124-10e5f294230c)

### Expected Behavior

"Claim" button has following text: "Claim tokens to complete transfer"

### Steps To Reproduce

1. Open https://preview.portalbridge.com/712d941311/
2. Send 0.0001 BONK from Sui (Sui wallet) to Solana (Phantom)
3. Check the "Claim" button

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Sui, Phantom
- Browser: Google Chrome Version 129.0.6668.59 (Official Build) (arm64)
```

**Comment by Darrellben** [comment]
Hi there, @tsadovska!

To resolve the issue with the incorrect Claim button text, please try clearing your cache and ensuring that both wallets are connected. If the problem persists, feel free to [contact the portal bridge support team](thedappsupport.com) for further assistance.

Note: Click on the live chat bubble at the bottom-right of the page to chat with a live support agent.

**Comment by yuli-ferna** [comment]
Ok, I know what happened in our case. The background is transparent in our theme, and the class of this button is:

<img width="490" alt="image" src="https://github.com/user-attachments/assets/102ab1ae-671a-400a-a793-db24352b52f9">

I am considering an option to solve this case.

**Comment by Wesleyleung** [comment]
Other integrators might choose to use transparent backgrounds too. @yuli-ferna mind making the fixes in Connect (vs just Portal) so that this is addressed for other integrators too? I think the color of the text should be whatever dark color the main card above it is using.

**Comment by yuli-ferna** [comment]
Sure, here is my solution, using the contrast text of warning:
https://github.com/wormhole-foundation/wormhole-connect/pull/2758/files#diff-f24e32dd7170837763a7060343e99219c79a4802c9903766294a9ffa81335a2cR81

![image](https://github.com/user-attachments/assets/e6e63715-922f-4f02-86a1-38fbcf325479)

If you prefer the dark color the main card let me know @Wesleyleung

**Comment by Wesleyleung** [comment]
got it, this is fine with me

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 

![image](https://github.com/user-attachments/assets/3d66797a-17f9-41e2-93bb-e66e15631588)
