### ISSUE TITLE
[QA] Error “Dry run failed, could not automatically determine a budget” appears in Console when user sends tBTC from Ethereum to Sui

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#113]
#### Build:
https://6d624a29.portal-bridge-ui.pages.dev/#/register [Testnet]

#### Precondition:
tBTC is not registered on Sui network

#### Steps:

1. Transfer 0.000001 tBTC from Ethereum Goerli (Metamask wallet) to Sui (Sui wallet)
2. Click “Register now” button in Step “2.Target”
3. Click “Attest” button in Step “3.Targer”
4. Approve notifications in Metamask wallet
5. Click “Create” button in Step “4.Create wrapped token”

#### Actual result:

- “Gas estimation failed” is displayed for the user in Sui wallet
- Transaction fails with error:

```
Error: Transaction failed with the following error. Dry run failed, could not automatically determine a budget: VMVerificationOrDeserializationError in command 0
    at dapp-interface.js:2:238360
    at dapp-interface.js:2:236509
    at a._next (dapp-interface.js:2:235817)
    at e.next (dapp-interface.js:2:233882)
    at dapp-interface.js:2:238276
    at a._next (dapp-interface.js:2:235817)
    at e.next (dapp-interface.js:2:233882)
    at dapp-interface.js:2:236502
    at a._next (dapp-interface.js:2:235817)
    at e.next (dapp-interface.js:2:233882)
```

#### Expected result:
Transaction proceeds without error.

#### Note:
Transaction details:
https://goerli.etherscan.io/tx/0x3a1cdefabcffea929d69ea86d3df93bcd88464d7ca06c71d9eace534b65201b6
https://goerli.etherscan.io/tx/0x2d88942dd890bec42472979d772397e7e63692760a80405e7c916b44dd3e1058  

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-10 at 14 01 31](https://github.com/XLabs/portal-bridge-ui/assets/10746654/c6ef23cc-b633-43b8-a63f-abf308782a62)
[Screen Recording 2023-05-10 at 13.31.06.zip](https://github.com/XLabs/portal-bridge-ui/files/11441100/Screen.Recording.2023-05-10.at.13.31.06.zip)

**Comment by sebastianscatularo** [comment]
I've tried it on testnet and it worked as expected, closing it.



![Image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/eb772d9a-a900-404e-82ff-3040beb3185e)
