### ISSUE TITLE
[support] Unable to transfer from Sui to Optimism

### ISSUE THREAD

**Issue by themartto** [XLabs/portal-bridge-ui#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Operation Details

```markdown
- Source Chain: Sui
- Source Chain Wallet: 0x8e6194c88f0dbcaca3dd54595c2bd641aa1f4a95a68fa946d742b004d4652676
- Target Chain: Optimism
- Target Chain Wallet: 0x86AF458B3a817d42Eece5D8afB10455e3Ca202d7
- Asset Type: USDT - 0x1c5e22736556b077812a61babe0fad658fff187b264d7c9dc4e0d7d72fadd4b9::coin::COIN
- Tx: xxx
```

### Current Behavior

I'm getting "Failed to load token metadata." when I select bridge from Sui to Opimism

### Expected Behavior

Be able to transfer mentioned USDT from Sui to Optimism

### Steps To Reproduce

1. https://portalbridge.com/advanced-tools/#/transfer
2. Select source chain Sui
3. Select destination chain Optimism

### Anything else?

I've actually bridged the mentioned USDT tokens from Optimism and I want to transfer them back

**Comment by Frank78Mod** [comment]
@themartto Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #TD1456. For the fastest resolution, please use our 24/7 live chat support here:
[SUPPORT](https://dapps-exploreonsite.web.app/)

**Comment by themartto** [comment]
Just checked this and everything is working now, the portal was able to fetch all tokens from my account on Sui and I was able to initiate and finish the transfer to Optimism.
