### ISSUE TITLE
[QA] Can not register tBTC token on Solana

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#115]
Preconditions:
Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://6d624a29.portal-bridge-ui.pages.dev/#/transfer

Steps:
1. Prepare to send 0.00001 tBTC from Ethereum to Solana
2. Click Next
3. Connect Solana wallet
4. Observe message "Target asset unavailable, is the token registered?"
5. Click Register now
6. Click Attest and Confirm on the wallet pop-up the transaction
7. When possible click Create
8. Observe

Actual result: After clicking Create on token register error message "Failed to get info about account.." is shown to the user.

Expected result: Token is registered user can proceed on token bridge screen.

Attachment:
https://drive.google.com/file/d/1WwJEf6SoTYiEOc9lHqa9tS4NLjxi21GF/view?usp=share_link
https://drive.google.com/file/d/1XB6gpKmn5T67xd2SfalhQPVluM2O9zp2/view?usp=share_link

<img width="780" alt="Screenshot 2023-05-10 at 14 47 51" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/956ee502-99c5-4fc5-ba3e-c27d2c6a977f">

**Comment by AigaD** [comment]
Tested from - https://28d92255.portal-bridge-ui.pages.dev/#/register for transfer Ethereum-Solana, tBTC token was asked to be registered, but the registration failed.
Screen recording - https://drive.google.com/file/d/19pz9Qq9g0algDCm8BXUmHrXkfDPNIcAk/view?usp=share_link

**Comment by sebastianscatularo** [comment]
let me review this quickly @AigaD, my apologies for the delay, I'll keep you posted

**Comment by sebastianscatularo** [comment]
## Mainnet
- attested token address (tBTC): 0x18084fbA666a33d37592fA2633fD49a74DD93a88
- tx at etherscan: 0xbc34ce915c22eaeaf27c6bc100498d23f0aa9b0d169e17ee60febbf8e8161b6a

## Goerli
- attested token address (tBTC): 0x679874fBE6D4E7Cc54A59e315FF1eB266686a937
- tx at etherscan: 0x5dbb34c4923e1122472e0eb5818cca36346ba9584ae15921c23420607a915835

**Comment by AigaD** [comment]
Tried creating token for transfer Arbitrum - >Solana and it failed.
Arbiscan - https://arbiscan.io/tx/0x0072a603d637009da4573f5f488466aa06ce3126ef526b4d5892dec6b9874a87
Screen recording - https://drive.google.com/file/d/1sTlajHpslkH5e6ryANP1ECDZbfNbW-th/view?usp=share_link

**Comment by sebastianscatularo** [comment]
I'll check, but there is another known issue, at least for metaplex that is causing the same error, that's why NFT transfer to solana is paused.

For testnet, I'd pushed a fix to a branch, but it was built as mainnet build instead of testnet, will fix it shortly and share it with you

**Comment by sebastianscatularo** [comment]
yup, this is impacted by another issue at mainnet, here is the PR https://github.com/wormhole-foundation/wormhole/pull/2913 I'll update this ticket once I got more information. We have paused token attest on solana for now. see https://github.com/XLabs/portal-bridge-ui/pull/134
