### ISSUE TITLE
[QA] [Medium] User is not able to select tBTC when wallet is connected through WalletConnect

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#123]
#### Build:
https://28d92255.portal-bridge-ui.pages.dev/#/transfer [Mainnet]

#### Preconditions:
* Binance application is installed on mobile
* DeFi wallet is created in Binance application

#### Steps:

1. Select Ethereum as Source chain
2. Select Polygon as destination chain
3. Click “Connect wallet” button and select “WalletConnect” option
4. Scan QR Code with mobile
5. Click “Select a token” button 
6. Select any token (in my case, tBTC)

#### Actual result:
Error is displayed for the user: “Unable to retrieve required information about this token. Ensure your wallet is connected, then refresh the list.”

#### Expected result:
User is able to select tBTC token.

#### Devices:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)
Samsung S20 Android 12, Chrome Version: 112.0.5615.136

#### Attachment:
![Screenshot 2023-05-11 at 17 56 23](https://github.com/XLabs/portal-bridge-ui/assets/10746654/c385ff86-4ad0-452e-8987-015610db70e3)

[Screen Recording 2023-05-11 at 17.51.43.zip](https://github.com/XLabs/portal-bridge-ui/files/11453519/Screen.Recording.2023-05-11.at.17.51.43.zip)

**Comment by SamantaCasal** [comment]
This bug still happens.

**Comment by sebastianscatularo** [comment]
as per the recording from @SamantaCasal, I'll close it.
