### ISSUE TITLE
[QA] [Medium]Token information box should not be displayed when user disconnects the wallet

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#124]
#### Builds:
https://7a7e292f.portal-bridge-ui.pages.dev/#/transfer [Testnet]
https://28d92255.portal-bridge-ui.pages.dev/#/transfer [Mainnet]

#### Steps:

1. Select Polygon as Source chain
2. Select Ethereum as destination chain
3. Connect Metamask wallet
4. Select MATIC asset
5. Click on “Disconnect” button
6. Observe if Token information box is displayed

#### Actual result:
Token information box is displayed.

#### Expected result:
Token information box should not be displayed.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.137 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-11 at 18 08 10](https://github.com/XLabs/portal-bridge-ui/assets/10746654/e7327c47-1180-4a66-ac1a-d1be1ce4a503)

[Screen Recording 2023-05-11 at 18.00.44.zip](https://github.com/XLabs/portal-bridge-ui/files/11453672/Screen.Recording.2023-05-11.at.18.00.44.zip)

**Comment by SamantaCasal** [comment]
This bug still happens. Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/d8e5283d-86e9-4109-8933-090b20c9003e

**Comment by SamantaCasal** [comment]
QA ok! Tested from: https://www.portalbridge.com/#/transfer

Evidence: 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/d4a5240d-ed75-45a0-b5a1-02e8c8bc95dc)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/09fb07d8-0995-4136-b552-10631348dda7)
