### ISSUE TITLE
[QA][Medium] User is not informed if funds are lacking for the transfer

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#131]
Preconditions:
Metamask Wallet is connected
Metamask wallet does not have any ETH

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://28d92255.portal-bridge-ui.pages.dev/#/transfer

Steps:
1. Prepare to transfer 0.00001 tBTC from Ethereum to Polygon
2. Click Next
3. Observe

Actual result: It is shown that for Manual Payment for fees user has to pay 0.0411 - 0.0460 MATIC, but the transfer is not moving forward, instead it shows endless loading. It seems that user also need to have ETH on Ethereum Network, but user is not informed regarding this. 

Expected result: Inform user what fees are needed to paid or indicate that user does not have enough assets for this transfer.

Attachment:

Screen recording: https://drive.google.com/file/d/1SkKRuKaLpiVOf7hUSqFICHogrLBeWmDc/view?usp=share_link

**Comment by SamantaCasal** [comment]
This bug is already fixed. Evidence 


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/91f379e1-de9d-42c3-82e8-24a158eb9c0b)
