### ISSUE TITLE
chore: bump @solana/wallet-adapter-react version package to support wallet standard

### ISSUE THREAD

**Issue by akash-frontier** [XLabs/portal-bridge-ui#140]
Since the Solana wallet adapter is no longer accepting PRs and recommends implementing the [Wallet Standard](https://github.com/solana-labs/wallet-adapter/blob/master/WALLET.md).we are facing an issue with listing the [Frontier Wallet](https://chrome.google.com/webstore/detail/frontier-wallet/kppfdiipphfccemcignhifpjkapfbihd) on the portal bridge.The current version of `@solana/wallet-adapter-react: 0.15.3` does not detect wallets that have implemented the wallet standard.
We need to update the package version of @solana/wallet-adapter-react to resolve this issue.
Any suggestions or assistance in resolving this problem would be greatly appreciated.

**Comment by sebastianscatularo** [comment]
Hi @akash-frontier, would this issue affect the portal bridge? I could update the version, but, so far my understanding we are up to date with the last version of that library @solana/wallet-adapter-react, could you give us more insight? 

thank you, Sebastian

**Comment by akash-frontier** [comment]
Hi @sebastianscatularo, the latest version of @solana/wallet-adapter-react is `0.15.32`. Currently, the wallets present in the wallet adapter package are being listed.
https://github.com/XLabs/portal-bridge-ui/blob/63c2602aa8d2f3c282a756dcd3c6e7a8794c04fb/src/contexts/SolanaWalletContext.tsx#L27-L39

However, the current scenario blocks the listing of wallets that have implemented the wallet standard. Upgrading the @solana/wallet-adapter-react package from version `0.15.3` to `0.15.32` will not affect the portal bridge.

After the upgrade, the Wallet Adapter will automatically detect wallets and list them on the dapp.

**Comment by sebastianscatularo** [comment]
@M-Picco any thoughts here? is it okay if we bump the version?

**Comment by punithbm** [comment]
@sebastianscatularo  @M-Picco  are you guys planning to bump the version here ?

**Comment by sebastianscatularo** [comment]
@akash-frontier @punithbm This has been updated, our apologies for the delay
