### ISSUE TITLE
[QA] [Visual, Low] Two vertical scrollbars are displayed on “Select a token” pop-up on the small screen

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#165]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/f148f1e66d/#/transfer  [Testnet]

#### Precondition:
User opens browser on small screen.

#### Steps:

1. Select any network as Source chain (in my case, Sei)
2. Select any network as Target chain (in my case, Avalanche)
3. Click Connect button and connect Keplr wallet
4. Click "Select a token" button

#### Actual result:
Two vertical scrollbars are displayed on “Select a token” pop-up.

#### Expected result:
One vertical scrollbar is displayed on “Select a token” pop-up.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-26 at 11 17 45](https://github.com/XLabs/portal-bridge-ui/assets/10746654/a6b508ad-0680-4a8c-9af3-34e45d3e79fc)

**Comment by SamantaCasal** [comment]
I can't reproduce this bug. 
FYI: @sebastianscatularo 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/92947617-c108-47e7-bb04-bd8479361bb4

**Comment by SamantaCasal** [comment]
QA OK! Tested from: https://testnet.portal-bridge-ui.pages.dev/f5d68d086f/#/transfer
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/9ddee786-7372-4ea1-9a62-35bd21c62f21
