### ISSUE TITLE
[QA] Portal Bridge suggests to add token with name “WMATI” instead of “WMATIC”

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#166]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/f148f1e66d/#/transfer  [Testnet]

#### Steps:

1. Select Sei network as Source chain
2. Select “Binance Smart Chain” as Target chain
3. Connect Keplr wallet
4. Send 0.0001 WMATIC
5. Click “Transfer” button in Step 3 and confirm wallet notification
6. Click “Redeem” button in Step 4 and confirm wallet notification
7. Click “Add to Metamask” button in Step 4

#### Actual result:
Token name is “WMATI”.

#### Expected result:
Token name is “WMATIC”.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachments:
![Screenshot 2023-05-26 at 11 58 47](https://github.com/XLabs/portal-bridge-ui/assets/10746654/547c79db-7c67-43c5-ac77-6a382f5203f8)

![Screenshot 2023-05-26 at 11 59 29](https://github.com/XLabs/portal-bridge-ui/assets/10746654/0b926808-6890-4221-a1e4-5e91b5e1c510)

**Comment by mliu-xlabs** [comment]
deprecating
