### ISSUE TITLE
[QA][Medium]Entered value is changed if user scrolls down the page while still located on the amount section

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#167]
Preconditions:
Wallet is connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://testnet.portal-bridge-ui.pages.dev/f148f1e66d/#/transfer

Steps:
1. Select Source and Target fields (e.g. Sei and CELO)
2. Enter the amount in the amount section
3. Not leaving the amount section with the cursor scroll down the page
4. Observe the amount section

Actual result: Amount gets changed if cursor is still at amount section and user scrolls down the page.

Expected result: Amount should not be changed when scrolling down/up the page

Attachment:
Screen recording: https://drive.google.com/file/d/1ndDCSKYBchMa1ffp27KT4cMi9Wz2jaEm/view?usp=share_link

**Comment by SamantaCasal** [comment]
This bug still happens.

**Comment by SamantaCasal** [comment]
QA OK: tested from https://testnet.portal-bridge-ui.pages.dev/f5d68d086f/#/transfer
Evidence: 


https://github.com/XLabs/portal-bridge-ui/assets/69044575/1fa2a0a7-cc1c-49d1-8bbf-390657db51c5
