### ISSUE TITLE
[QA] Transaction fails when user clicks on "Redeem" button

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#168]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/f148f1e66d/#/transfer  [Testnet]

#### Steps:

1. Select Arbitrum network as Source chain
2. Select Sei as Target chain
3. Connect Metamask wallet
4. Send 0.000001 tBTC
5. Connect Keplr wallet
6. Click “Transfer” button in Step 3 and confirm wallet notification
7. Click “Redeem” button in Step 4 

#### Actual result:
Error is displayed for the user:
`Error when broadcasting tx 1EBE696D39835D2AEDBEAD08F603F4AEC3A7D9B4555D7E5A0EB7849DD060DB6D at height 11808250. Code: 5; Raw log: failed to execute message; message index: 0: dispatch: submessages: Generic error: VaaAlreadyExecuted: execute wasm contract failed`

#### Expected result:
Transaction proceeds successfully. 

#### Note:
Transaction details:

- [Arbitrum 1](https://goerli.arbiscan.io/tx/0x8da0004ba7672023af4630a58029fe81559b95f7e1c019a6acca23490b251b6d)

- [Arbitrum 2](https://goerli.arbiscan.io/tx/0x381e7bfdc2898d64a9bc60c1227dc027e93f7903ccaee1d766ea3fa3ac800352) 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-26 at 16 44 29](https://github.com/XLabs/portal-bridge-ui/assets/10746654/8d09f7f9-e780-4ff5-9e0a-800a413ecc41)

**Comment by tsadovska** [comment]
Issue is also reproducible when sending WBNB from Polygon to Sei (Keplr wallet).
Polygon transaction ID: [Mumbai](https://mumbai.polygonscan.com/tx/0x92610292706200d4ffb920589c9cc1d63aed1175f25556ce39d928823efaf132)
Attachment:
![Screenshot 2023-05-26 at 17 53 41](https://github.com/XLabs/portal-bridge-ui/assets/10746654/97f1eb30-6971-4aa6-baf7-2fa692a4eb24)

**Comment by SamantaCasal** [comment]
https://github.com/orgs/XLabs/projects/2/views/1?filterQuery=%5BQA%5D&pane=issue&itemId=29410186

**Comment by sebastianscatularo** [comment]
@SamantaCasal could we re-check it since Sei has been at mainnet from a while

**Comment by tsadovska** [comment]
Issue is not reproducible on Portal Bridge Advanced tools. 
Asset was successfully received. 
* From tx: https://arbiscan.io/tx/0x0afc17d03ade968d779827416e097871eafb8b462d9e9c4577973a5af124f9fd
* To tx: https://seitrace.com/tx/35CDBCA104CEC5DB311E2CA6C4CFC109542BDBDB79A4615C47638808017C6DC7?chain=pacific-1

![image](https://github.com/user-attachments/assets/08553728-7da5-40ba-b408-3abd15741b04)


Ticket is closed.
