### ISSUE TITLE
[QA] List with wrapped assets is not displayed for Ethereum (Goerli) network

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#169]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/f148f1e66d/#/transfer  [Testnet]

#### Steps:

1. Select Sei network as Source chain
2. Select Ethereum (Goerli) as Target chain
3. Click Connect button and connect Keplr wallet
4. Click “Select a token” button
5. Observe

#### Actual result:
Only native asset ETH is displayed in the list.

#### Expected result:
Native asset ETH and wrapped tokens are displayed in the list.

#### Note:
Issue is not reproducible when following networks are selected as Source chain:

- Polygon
- Fantom
- Binance Smart Chain
- Solana

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-26 at 17 16 58](https://github.com/XLabs/portal-bridge-ui/assets/10746654/6f240e66-a98c-46c1-a00f-2d5ca40c9ec0)

**Comment by SamantaCasal** [comment]
This bug is in the https://github.com/orgs/XLabs/projects/2/views/1?pane=issue&itemId=33685043 scope.

**Comment by sebastianscatularo** [comment]
see https://github.com/XLabs/portal-bridge-ui/issues/255
