### ISSUE TITLE
[QA] Two MATIC options are displayed on “Select a token” pop-up

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#170]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/f148f1e66d/#/transfer  [Testnet]

#### Steps:

1. Select Polygon network as Source chain
2. Select Sei network as Target chain
3. Click Connect button and connect Metamask wallet
4. Click “Select a token” button
5. Observe

#### Actual result:
Two MATIC options are displayed on “Select a token” pop-up.

#### Expected result:
MATIC option should not be duplicated.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-05-26 at 17 45 58](https://github.com/XLabs/portal-bridge-ui/assets/10746654/6dd60736-75f1-41ef-9c01-4da2ec8e2f2c)

**Comment by SamantaCasal** [comment]
This bug still happens 


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/ce7b98e4-c664-4be8-867c-f219bec010c9)
