### ISSUE TITLE
[QA] -[Medium] Unable to connect phantom wallet on mobile

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#172]
Build:
- https://www.portalbridge.com

Steps:
- Select Solana on source chain
- Click Connect button and connect Phantom or Solflare

Observe:

Actual result:
- Phantom does not appear as an option and Solflare does not connect.

Expected result:
- The wallets gets connected 

Device:
iPhone, Chome, and Safari

**Comment by hernandiegosavio** [comment]
Get more info about how to reproduce.

**Comment by SamantaCasal** [comment]
**This bug still happens.** 

**Prerequisites:** Have an account in Phantom or Solflare

**Device used for the test:**
- iphone 11
- iOS version 16.5
- Browsers: Chrome+Safari

**Steps to reproduce:** 

1. Open https://www.portalbridge.com from mobile
2. Select Solana on the source chain
3. Click on the connect button 
4. Observe the list of wallets to connect that it offers
5. Observe the list of wallets to install
6. Click on Solflare 
7. Click on Connect

**Obtained result:** 
1 Does not include Phantom among the wallets to select (this wallet has already been added)
2 Solflare connects OK.

**Expected result**

Phantom should appear among the wallets to connect

**Evidence:** 


https://github.com/XLabs/portal-bridge-ui/assets/69044575/9b28c4db-fa82-404c-9cc5-d2bdd2ad6870

FYI: @sebastianscatularo

**Comment by mliu-xlabs** [comment]
deprecating
