### ISSUE TITLE
[QA] [Low] 'Cannonical token' message is not displayed on “Are you sure?” pop-up

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#175]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/c2e9787404/  [Testnet]

#### Steps:

1. Select Avalanche network as Source chain
2. Select Ethereum (Goerli) as Target chain
3. Click Connect button and connect Metamask wallet
4. Select tBTC asset (contract address 0x7E1779F65B644E5f98DdC4D2cB0A0106a7E6d9e1)
5. Type amount, in my case 0.0000001
6. Click Next button and approve Metamask notification
7. Click Next button in Step 2
8. Click Tranfer button in Step 3
9. Observe “Are you sure?” pop-up

#### Actual result:
'Cannonical token' message is not displayed. 

#### Expected result:
'Cannonical token' message should be displayed:  “You will receive tBTC as canonical tokens that are natively supported and ready to use! No need for unwrapping or exchanging for native assets.”

#### Note:
Issue is also reproducible when sending tBTC from Celo to Ethereum (Goerli)

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachments:
![Avalanche](https://github.com/XLabs/portal-bridge-ui/assets/10746654/9963551b-8494-4bc5-a663-706c3b67f3b3)
<img width="805" alt="Celo" src="https://github.com/XLabs/portal-bridge-ui/assets/10746654/25dc9172-aabd-4241-b7c1-e5da38a3a3c1">

**Comment by SamantaCasal** [comment]
This bug is already fixed. 
The message displayed is: 


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/dfb6533f-0f86-4937-b90a-93a5933ae039)

**Comment by SamantaCasal** [comment]
QA Fail: The message is still wrong. Evidence
Tested from: https://testnet.portal-bridge-ui.pages.dev/f5d68d086f/#/transfer

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/25c37983-4074-4605-8bc7-908883b19741)

**Comment by yuli-ferna** [comment]
@SamantaCasal Could you test this when you have time:
#304 
https://testnet.portal-bridge-ui.pages.dev/0e8549e166/

**Comment by SamantaCasal** [comment]
QA ok!
![Screenshot 2023-08-16 at 3 51 15 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/d58402a0-a4f2-4ebe-ade7-7603511c1d14)
