### ISSUE TITLE
[QA] [High] User is not able to send tBTC from Sui network

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#176]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/c2e9787404/  [Testnet]

#### Steps:

1. Select Sui network as Source chain
2. Select Optimism as Target chain
3. Click Connect button and connect Sui wallet
4. Select tBTC asset (contract address `0x0acf6784120b221a077ab0b84acc0b76930779eb55f157ea2492be4a60b808f6::coin::COIN`)
5. Type amount, in my case 0.00000001
6. Click Next button in Step 2
7. Click Tranfer button in Step 3 and confirm transaction in “Are you sure?” pop-up
8. Observe 

#### Actual result:

- “Sui transfer with payload not implemented” is displayed to the user
- Error is displayed in Console:

```
Error: Sui transfer with payload not implemented
    at transfer.js:511:19
    at Generator.next (<anonymous>)
    at transfer.js:7:71
    at new Promise (<anonymous>)
    at z (transfer.js:3:12)
    at re (transfer.js:509:12)
    at useHandleTransfer.tsx:816:22
```

#### Expected result:
Transaction proceeds without errors.

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
![Screenshot 2023-06-05 at 12 57 05](https://github.com/XLabs/portal-bridge-ui/assets/10746654/4cf324cc-57f3-4d5d-a44e-f0ab01159df3)

**Comment by SamantaCasal** [comment]
This bug still happens. Evidence: 


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/1aed9fbd-a0ff-4889-8558-583f9b53dde5)

**Comment by SamantaCasal** [comment]
QA OK !


https://github.com/XLabs/portal-bridge-ui/assets/69044575/e63d185d-94a8-430a-851b-dd45d6afa4bd
