### ISSUE TITLE
[QA] [High] Can not register tBTC token when sending from canonical chain to Aptos

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#177]
Preconditions:
Wallets are connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://testnet.portal-bridge-ui.pages.dev/c2e9787404/#/register

Steps:
1. Prepare to send tBTC token from Optimism to Aptos
2. Observe that Register Now is shown and click on it
3. Click Attest when option is given
4. Click Create when possible
5. Observe

Actual result: Error message "Cannot read properties of undefined (reading data)" is shown and token is not registered.

Expected result: Token is registered.

Comments:
Also reproduced: Ethereum -> Aptos
Polygon -> Aptos
Arbitrum -> Aptos

Attachment:

<img width="1320" alt="Screenshot 2023-06-05 at 15 43 26" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/8e64ba83-f3b6-4b5e-a924-8189b5a08eff">

Screen recording: https://drive.google.com/file/d/1DyCsjTk4DZaTxsIPabeuUw0C1ctUUO1g/view?usp=share_link

https://github.com/XLabs/portal-bridge-ui/assets/91047061/c26fc761-f747-4e1f-9ce5-7fff1c48319d

**Comment by SamantaCasal** [comment]
FYI: @sebastianscatularo 
**The test was performed from the Goerli-Aptos pair.*
**Results obtained:**
1 Click on Create -> The error message was displayed twice
2 The wallet is disconnected
3 After connecting the wallet, the registration of the token is carried out without inconvenience.(https://explorer.aptoslabs.com/txn/0xfef1ab17038aff58f5035af788154e96c051974f832965dcd6b4702c3dbbecd6?network=testnet)

**1st Part:**

https://github.com/XLabs/portal-bridge-ui/assets/69044575/9721b4a8-4ead-47a9-99cc-0b2b4f17d127

**2 Part:** 


https://github.com/XLabs/portal-bridge-ui/assets/69044575/463fb002-92e5-402d-8434-206a0417bd1e
