### ISSUE TITLE
FAQ | Include build inside pkg deployed for CF pages

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#190]
**Technical Story**
 Include build inside pkg deployed for CF pages

- [ ] Add steps to github actions to build the docs
- [ ] Include the docs build into the final package

**Comment by mliu-xlabs** [comment]
Will need help filling this out @sebastianscatularo

**Comment by mliu-xlabs** [comment]
use this https://www.portalbridge.com/docs 

should this URL go into this story or the link story?

**Comment by sebastianscatularo** [comment]
this was covered at commits

- https://github.com/XLabs/portal-bridge-ui/pull/196/commits/c9bfedf3303f2372fba7ec089d6bcb96ebed2808
