### ISSUE TITLE
FAQ | Update all links to point to correct content pages

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#191]
**User Story**
As a user, I want to be able to navigate to the different informational links on the Portal Bridge FAQ, so I can get more information and assistance on issues that I have with Portal Bridge.

**Acceptance Criteria**
- [x] All links should resolve to the correct URL
- [x] Any links that are broken should redirect back to the FAQ homepage
- [ ] All links with the same domain will open in current tab
- [ ] All links with external dowmain will open in new tab

**Link URLs**
> This will be read top down on the legacy webpage. referenced links are represented as green text on legacy page 
> format: `green text` (surrounding text reference) URL
- `the book` https://book.wormhole.com/
- `here` (referencing liquid markets) https://www.portalbridge.com/docs/liquid-markets
- `here` (check out our tutorial here) https://www.portalbridge.com/docs/tutorial-recovery-workflow
- `here` (How to add a token into your Metamask wallet here) https://www.portalbridge.com/docs/video-tutorial-how-to-manually-add-tokens-to-your-wallet
- `here` (You can find a comprehensive overview of liquid markets here) https://www.portalbridge.com/docs/liquid-markets
- `token migration tutorial` (some wormhole v1 assets are eligible for migration. To check, please use our token migration tutorial) ?? missing content here
- `discord`(Please reach out to our community managers on discord if the pools are empty) https://discord.com/invite/wormholecrypto

**Additional Information**
- https://www.notion.so/xlabsxyz/Portal-Bridge-FAQ-migration-f6d4c808755f4323a78e42417d0f4c86?pvs=4
- This will be our portal bridge faq URL: https://www.portalbridge.com/docs

**Comment by mliu-xlabs** [comment]
not sure why there is that error on the right column: https://preview.portal-bridge-ui.pages.dev/6946df0c93/docs/faqs/common-error-messages

![Image](https://github.com/XLabs/portal-bridge-ui/assets/130170527/58fecc03-57c6-49c7-a868-617c0f4e6bf8)

**Comment by mliu-xlabs** [comment]
https://preview.portal-bridge-ui.pages.dev/6946df0c93/docs/tutorials/how-to-do-token-register

styling is appearing as text


![Image](https://github.com/XLabs/portal-bridge-ui/assets/130170527/85ff966c-f1c4-4998-8c5e-0a562787c364)

**Comment by sebastianscatularo** [comment]
thanks, good call

**Comment by SamantaCasal** [comment]
✅ The book https://book.wormhole.com/


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/a73920f9-c5fb-4323-a4a3-25da25cd9bec)


✅  here (referencing liquid markets) https://www.portalbridge.com/docs/liquid-markets

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/fb19a2a3-a09b-491a-b2ae-c21a4e9621cb)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/a08fdf26-ed8e-49be-a6dc-b5847fb88955)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/33dab4b0-f5c4-40fd-bc12-f221f6755aa1)


✅  Redeem 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/7f786993-a67a-4ce0-93b6-626ab181c405)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/08aacecb-4d53-4815-a917-35ff92e564a9)


✅ here (check out our tutorial here) https://www.portalbridge.com/docs/tutorial-recovery-workflow

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/ca8b1bc6-18c3-47d0-a8a9-f6542d084cc3)

✅  On Liquid Markets Page: 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/251a57ee-7859-46fb-9d0b-292ccb671f66)

❗  **Saber links don't work and do not  redirect back to the FAQ homepage**

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/e4482c4e-c520-4db5-89d9-3a45e7ad2bf4)

✅  discord https://discord.com/invite/wormholecrypto

✅ Video Tutorials page
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/22facfde-7d10-472f-90bb-efe7f1f8ca1e)

✅ How to manually add tokens to your wallet Page: 
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/33a3eb37-d4d4-4f8b-9c35-f82d5b1139e8)

✅ How to send USDC from Ethereum to Solana page: 
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/7658a0bb-9dea-4bef-b692-9c2c97d149d9)

✅ How to send USDC from Solana to Ethereum page: 
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/a8633555-d262-4e49-a106-fa4a67f29bcd)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/60ec2cf7-9dd5-4470-ac5a-93eee84f3f05)

✅ Token/NFT Redeem Workflow page: 
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/30b298d8-18cb-415d-8d71-7f5696601ed4)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/12e37f72-4457-4210-a89a-a66c5ea5fa85)

✅ NFT Portal page:
https://portalbridge.com/#/nft
https://opensea.io/collection/wormhole-bridged-solana-nft

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/0127c9ce-6ae8-402b-990c-375146e07e57)

✅  NFT Origin tool page:
https://www.portalbridge.com/#/nft-origin-verifier
https://solanart.io/

✅  Token registration page:
https://www.portalbridge.com/#/register


Note: I can't find where is "token migration tutorial (some wormhole v1 assets are eligible for migration. To check, please use our token migration tutorial) ?? missing content here"
