### ISSUE TITLE
[DSR] Block users from sending PENDLE to certain chains via PortalBridge

### ISSUE THREAD

**Issue by ayobuenavista** [XLabs/portal-bridge-ui#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki

### Operation Details

```markdown
Block users from sending PENDLE token to ALL chains via PortalBridge EXCEPT the following routes:

Ethereum <-> BNBChain

This is to prevent unexpected bridging to other chains where the Pendle protocol is not deployed in yet.
```

### Current Behavior

Users is allowed to bridge PENDLE to all chains supported by Wormhole.

### Expected Behavior

Only allow users to bridge between Ethereum and BNBChain.

**Comment by sebastianscatularo** [comment]
Hi @ayobuenavista this was implemented and deployed, feel free to create another issue if you need future assistance :)
