### ISSUE TITLE
[QA] [Low]Visual error: error message persists after cleaning input

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#236]
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.

**Tested from:** 
https://www.portalbridge.com/#/transfer (Mainnet and testnet)

**Steps**

1. Go to https://www.portalbridge.com/#/transfer
2. Click on Redeem
3. Enter an invalid txHash or vaa
4. Clear the input
5. Observe the error message

**Obtained result:**
After deleting what was entered in the input, the error message is still displayed

**Expected result:**
The error message should clean when the input is empty

**Evidence:**

**Comment by mliu-xlabs** [comment]
deprecating
