### ISSUE TITLE
[UI Rec] Add content on # of transactions users will be required to sign

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#237]
Consider setting the users’ expectation by communicating them how many transactions they will be required to sign.
In this step you will approve the bridge to move your tokens from the Ethereum Network to the Solana Network. This will take [insert number] transactions on Ethereum.
Keep this tab open until you finished bridging your tokens. Red more
CTA [Approve and send]
5 of X

**Comment by mliu-xlabs** [comment]
Let the user know in advance that there will be 4 transactions on Solana.

**Comment by Gpluv** [comment]
This ticket needs to be reviewed for technical feasibility and library limits to narrow the scope. @sebastianscatularo @mliu-xlabs

**Comment by sebastianscatularo** [comment]
Tentative task list

- [ ] - Identify the origin of the current pop's requesting approvals
- [ ] - Apply UI/UX design from @Gpluv 
  - [ ] - Better informative widget

**Comment by sebastianscatularo** [comment]
to illustrate the idea here:

```
you have to approve 4 transactions to complete the redemption at the target chain:

1/4 - [x] (0.001 Sol)
2/4 - [x] (0.001 Sol)
3/4 - [ ] (0.001 Sol)
4/4 - [ ] (0.001 Sol)
```

**Comment by mliu-xlabs** [comment]
deprecating
