### ISSUE TITLE
[UI Rec] Separate wallet section from core content of dApp and move wallet disconnect

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#243]
Separate the wallet section from the core content of the dApp. Move the Disconnect button above the tab navigation or in the Steps that require wallet connection.

Change design to prevent people from selecting the disconnect wallet when they are trying to transfer tokens

![Image](https://user-images.githubusercontent.com/130170527/253047201-ef3695a0-ad19-4a8f-8b33-d01039112516.png)

**Comment by mliu-xlabs** [comment]
George input needed

**Comment by Gpluv** [comment]
Design [Here](https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=505-16271&mode=design&t=dhX6z3114T3BhTsq-4)

**Acceptance criteria**

1. Standardize the padding of the div.MuiStep-root to 32px.
2. Keep the size of the original div.

**Comment by mliu-xlabs** [comment]
deprecating
