### ISSUE TITLE
[UI Rec] The info box is text heavy, consider extracting the text and display it as a normal body copy/instructions for Step 3.

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#245]
The info box is text heavy, consider extracting the text and display it as a normal body copy/instructions for Step 3.

![Image](https://user-images.githubusercontent.com/130170527/253055348-362c8894-6179-4b1b-bbbe-494ebc93493c.png)

**Comment by mliu-xlabs** [comment]
design work talk to george

**Comment by Gpluv** [comment]
Please wait for the Solana transfer to finalize. Exiting the page before step 4 will require the recovery workflow to complete the transfer.

@mliu-xlabs @sebastianscatularo  what do you think?

**Comment by mliu-xlabs** [comment]
deprecated
