### ISSUE TITLE
[UX] - Better error handling/messaging to user for transfers not using portal bridge, on portal bridge

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#246]
**User Story**
As a user, when I am trying to redeem a token for a transfer that did not occur on portal bridge, I want to be shown appropriate error messaging, so I know why I am getting an error message in token bridge

**Acceptance Criteria**
- When it is a wallet connect or CCTP or other transfer, show following error message:
"This is not a token bridge transfer and cannot be recovered here"

**Comment by mliu-xlabs** [comment]
Need small design here:

Also -- do we have a way to identify if it is a wallet connect or cctp transaction?

**Comment by sebastianscatularo** [comment]
I think it will be enough to notify the users that the transaction is not compatible with the portal bridge.

**Comment by sebastianscatularo** [comment]
We need the text for the alert message and the location where it should be displayed. As for the rest, we can reuse the current alert style.
