### ISSUE TITLE
[UX] - earlier notice of notional limits and his implications

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#248]

**Comment by mliu-xlabs** [comment]
language to be updated

**Comment by mliu-xlabs** [comment]
existing style:


![Image](https://github.com/XLabs/portal-bridge-ui/assets/130170527/ed17a07c-75d2-41e9-a9c4-3465b704f7cb)

**Comment by sebastianscatularo** [comment]
we already have a warning for notional limits @mliu-xlabs maybe next time this happens we should evaluate the particular case

![Image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/86bfb87e-839a-4300-8fe8-e287beb0cd76)
