### ISSUE TITLE
Linking to Wormholescan transaction URL from Portal Bridge

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#250]
**User Story**
As a user, I want to be able to navigate and view my transaction, immediately after my portal bridge transaction has reached finality, so that I can verify my transaction details.

**Acceptance Criteria**
- Linking to Wormholescan transaction URL from Portal Bridge
- Add "beta" wording to the wormholescan link (as an idea)

![Image](https://user-images.githubusercontent.com/130170527/253382109-611f0df9-7ea7-4158-8222-d22201a6a253.png)

**Comment by Gpluv** [comment]
Design Here:  https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=1342-794&mode=design&t=lccXIOfUmQKz2iLY-4
