### ISSUE TITLE
[QA] [Medium]Only the native token is available to select

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#255]
**Tested from:** 

- MacBook Pro. MacOs Ventura version 13.3.1
- Version 114.0.5735.198 (Official Build) (arm64)

**Prerequisite:** 
Have a wallet (in my case metamask) with at least one token with balance > 0 in addition to the native one.
**Steps to reproduce:**

1. Go to https://testnet.portal-bridge-ui.pages.dev/4bd26bbc50/#/transfer
2. Select any chain as the source chain (In the video Goerli) 
3. Connect the wallet (in the video Metamask) 
4. Select another chain as the target chain
5. Click on Select a token
6. Observe the list 
7. Looking for one token different from the native one

**Obtained Result:** 
In the list, you can see only the native token with its corresponding balance
In the taxed case you can see USDC without the balance
Clicking on the non-native token shows the error "Unable to retrieve required information about this token. Ensure your wallet is connected, then refresh the list"
By entering the address of the token contract, it recognizes the asset and the correct balance.

NOTE: The same issue is with
ALGORAND

**Expected result:** 
It should show the list of assets with the corresponding balance that the connected wallet has
You should be able to select a token from the list

**Evidence:** 
Recorder ➡ https://github.com/XLabs/portal-bridge-ui/assets/69044575/42c3ee28-59cb-4c9f-8ea0-b7b382d59d6c

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/1f43356c-4172-4d5d-b2de-45cd041a280a)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/3fce6739-8693-469f-ad95-9d434d315158)

**Comment by tsadovska** [comment]
Issue is also reproducible on https://testnet.portal-bridge-ui.pages.dev/18c38dbb6a/#/transfer [Testnet] when Ethereum (Goerli) network is selected as Source chain. Only native token is displayed in the list. Other tokens can be selected by entering contract address.
Checked from macOS Monterey version 12.6.7, Google Chrome Version 115.0.5790.114 (Official Build) (x86_64).

![Screenshot 2023-08-02 at 09 26 04](https://github.com/XLabs/portal-bridge-ui/assets/10746654/c4c52b1c-cb3b-4ca0-8b28-889c1edf436b)
