### ISSUE TITLE
[UI Rec] Better explanations around Associated Account stands for. It may be easily explained in a tooltip or a Read more button.

### ISSUE THREAD

**Issue by hernandiegosavio** [XLabs/portal-bridge-ui#256]
Not sure what this one is, need to ask Threshold

**Comment by sebastianscatularo** [comment]
An explanation of what a Associated Token Account is from Alchemy https://www.alchemy.com/overviews/associated-token-account

**Comment by mliu-xlabs** [comment]
deprecating
