### ISSUE TITLE
WETH shows Zero address after transfer complete

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#259]
The UI is showing a Zero address for WETH token after the transfer is completed instead of the right WETH address on the target chain. 

Screenshot 

![Image](https://user-images.githubusercontent.com/1277510/255906081-d4a73b93-e629-44fc-87bc-c4fbb60d58a1.png)

See [Slack Chat](https://xlabs-org.slack.com/archives/C02JLN63403/p1689758170914809)

**Comment by mliu-xlabs** [comment]
deprecating
