### ISSUE TITLE
[bug] notional warning does not shows up for tBTC token

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#262]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### have you checked our wiki for common solutions?

- [x] I have searched the wiki or docs

### Operation Details

- Source Chain: Arbitrium
- Source Chain Wallet: N/A
- Target Chain: Optimism
- Target Chain Wallet: N/A
- Asset Type: tBTC
- Tx:
  - https://arbiscan.io/tx/0xa2dc3e7c7005d192ab94cfa5475985f339800e4f0a519dd7322b783ac86da31c
  - https://arbiscan.io/tx/0x7baea5fef0633f4b50dcdb8d7caeb15f07ac644a2afbc5957f15fdaf4e0f6da6#eventlog

### Current Behavior

Does not shows up a warning about notional limits 

### Expected Behavior

Show current notional warning

**Comment by sebastianscatularo** [comment]
related: https://github.com/XLabs/portal-bridge-ui/issues/248

**Comment by mliu-xlabs** [comment]
deprecating
