### ISSUE TITLE
[bug] RareTron.io token is showing in the asset list

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Token with a name RareTron.io is showing in the list, when selected balance for it is 666666

### Expected Behavior

No such token is present in the Metamask assets

### Steps To Reproduce

1. Select Avalanche as Source Network
2. Select Base as Target Network
3. Connect to Metamask wallet
4. Click on Select Token
5. Observe the list

### Environment

```markdown
Wallet: Metamask

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://testnet.portal-bridge-ui.pages.dev/18c38dbb6a/#/transfer
```

### Anything else?

<img width="1231" alt="Screenshot 2023-08-02 at 14 20 44" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/a9c31214-4f34-43ff-bbba-60fe8e26a302">
<img width="923" alt="Screenshot 2023-08-02 at 14 20 07" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/f5839a10-d407-4138-ad7c-f5ddcf599079">
<img width="1294" alt="Screenshot 2023-08-02 at 14 18 19" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/f20fe6d2-07d9-45e7-aae7-112844668d09">

**Comment by sebastianscatularo** [comment]
@AigaD could you share the wallet address?

**Comment by AigaD** [comment]
Of course. Metamask: 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01

**Comment by sebastianscatularo** [comment]
Checking the wallet at the explorer, the wallet holds this Token, which could be due to an airdrop or something else, I think we could add some kind of protection here, but it is not on our roadmap at this moment. I'll close it due it is not a Portal Bridge bug

cc: @mliu-xlabs 

<img width="1063" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/0e27b544-b234-4d93-886d-74a7e08ff464">

**Comment by AigaD** [comment]
Similar issue for transaction Base -> Polygon is shown. Tokens with random naming are present in the asset list.

Wallet Metamask: 0xd493066498aCe409059fDA4c1bCD2E73D8cffE01

<img width="1167" alt="Screenshot 2023-08-02 at 15 25 19" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/10a3ca24-0c9a-4384-8740-7a425b15795f">
<img width="1180" alt="Screenshot 2023-08-02 at 15 25 27" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/c91d16d4-0418-40e2-9c1d-e918a3d2f3e3">
