### ISSUE TITLE
[bug] Transaction doesn't move forward from Step 3 for more than 1 hour and 30 minutes

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction doesn't move forward from Step 3 for more than 1 hour and 30 minutes with following scenarios:
* when sending WETH from Base to Ethereum, tx [Base](https://goerli.basescan.org/tx/0x24c2753d025ab2045c37e1cf528aa0ec37a87847af386785448435d0d44d6c34)
* when sending SOL from Base to Solana, [Base](https://goerli.basescan.org/tx/0x9d58af196f88c1ee943be1bc12d97ad16c1562927a9bf4623f268e165d27c353)
* when sending WETH from Base to Avalanche, [Base](https://goerli.basescan.org/tx/0x6427f933163063af658af60dff2fddce3b1eb95c21b4e4bbd66d1c0c6f824403)

### Expected Behavior

User is able to successfully send tokens.

### Steps To Reproduce

1. Open https://testnet.portal-bridge-ui.pages.dev/18c38dbb6a/#/transfer
2. Select "Base (Goerli)" as source chain
3. Select "Avalanche" as destination chain
3. Connect Metamask wallet
4. Select a token (in my case WETH)
5. Type Amount (in my case 0.001)
6. Approve wallet notifications
7. Observe if transaction is completed 

### Environment

```markdown
- OS: macOS Monterey version 12.6.7
- Wallet: Metamask
- Browser: Google Chrome version 115.0.5790.114 (Official Build) (x86_64)
```

### Anything else?

Attachment: 
![Screenshot 2023-08-02 at 18 32 11](https://github.com/XLabs/portal-bridge-ui/assets/10746654/287658c8-1f27-4327-a1a0-9e2f4428a4fe)

**Comment by sebastianscatularo** [comment]
@tsadovska Guardian at Goerli Base was down, I'll asked to re-observe those tx, that should produce the VAAs and you should be able to finish the flow

**Comment by sebastianscatularo** [comment]
Seems to be, this up to 4 days to reach the block where those Tx are, so you should be able to finish it, in 4 days, I'll let you know if it is ready before.

**Comment by sebastianscatularo** [comment]
@tsadovska one of the VAAs got emitted

**Comment by tsadovska** [comment]
Thank you! Checked that WETH transfer from Base to Ethereum is completed ([Base](https://goerli.basescan.org/tx/0x24c2753d025ab2045c37e1cf528aa0ec37a87847af386785448435d0d44d6c34), [Ethereum](https://goerli.etherscan.io/tx/0xb242c46df57d8c01145b76f317c78836a3db8bc4be5712378b0ec0c3a443bb74)).

**Comment by SamantaCasal** [comment]
QA OK! 
Evidence:
Tx 1: [Base](https://goerli.basescan.org/tx/0xd1a68036cb068b8dfa91ef87230a515e314ea1af56d514e13f2e7b549c31434d), [Avax](https://testnet.snowtrace.io/tx/0xb593c31ca9cb8611ecfafb62e29c790cc4fa0e9e073a03d5b18db548cc1b7fb3)
Tx 2: 
Evidence:
https://github.com/XLabs/portal-bridge-ui/assets/69044575/2616baeb-7246-4291-9b78-399d905f3435
