### ISSUE TITLE
[support] unable to redeem Solana -> Injective

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Solana
- Source Chain Wallet: 
- Target Chain: Injective
- Target Chain Wallet:
- Asset Type: Transfer
- Tx:

Wallet (Solana): Phantom
Wallet (Injective): Kepler
```

### Current Behavior

Unable to redeem

### Expected Behavior

User able to redeem it

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/1da43ed8-adc2-4076-a36f-b26ab3f53901)

**Comment by Dahtank** [comment]
Hi @sebastianscatularo i believe this has been resolved without any action on our part, so likely it was a local issue
