### ISSUE TITLE
[support] Failed to load token metadata 

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: SUI
- Source Chain Wallet: Sui
- Target Chain: Polygon
- Target Chain Wallet: Metamask
- Asset Type: USDT
- Tx: N/A
```

### Current Behavior

User unable to see his assets

### Expected Behavior

User able to see his assets and pick one

### Steps To Reproduce

Attempt a transfer from SUI to Polygon using USDT as Asset

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/e5563b6a-a144-4c7a-ada9-9c680dafc0f5)

**Comment by yuli-ferna** [comment]
Given the tests performed on testnet, it was not possible to replicate the error. When adding the wallet and transferring the assets these are listed in the bridge portal. 

Evidence:
![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/8725f6f1-b8cd-40d5-80b9-cfed24fffa87)

**Comment by Dahtank** [comment]
Update! Today, there were several new tickets open regarding "Failed to load token metadata"
We had a workaround for users and it worked for all of them(paragraph below for workaround)

Workaround
FYI. There are some weird problems with SUI wallets not recognizing tokens when
1. Certain unrecognized tokens on SUI wallet(workaround to use a clean wallet, recommend Suiet)
2. Certain locations cannot connect to SUI mainnet(workaround to use different(custom) RPC or VPN to connect to USA)
https://sui-mainnet-us-1.cosmostation.io/
https://sui-mainnet-us-2.cosmostation.io/
https://sui-mainnet-rpc.allthatnode.com/

Now the workaround doesn't seems to work anymore
Previously, i could not replicate the error on my end, but today, i also encountered this error when connecting to SUI or SUIET to PortalBridge or SUI bridge, my location is in Thailand and the users who reported problems today are from either South Korea or Vietnam

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/b8e4be5e-559f-4d53-af6b-89b40ea42ca7)
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/03a0d560-0174-4fd4-a239-0a7d5fd0b3f6)

**Comment by dry2022** [comment]
More and more user in the same situation.

**Comment by dry2022** [comment]
From a user : "is there a way to manually input the tokken data instead of fetching it from RPC?"

**Comment by sebastianscatularo** [comment]
in theory, if the users have the address, they can paste it

<img width="490" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/068518ee-85c6-4283-a1be-5d826aba2164">

**Comment by SamantaCasal** [comment]
It gives the error mentioned above trying to send tokens from Sui to Polygon with Sui Wallet, Nightly, and Suiet wallets.
Evidence:

https://github.com/XLabs/portal-bridge-ui/assets/69044575/659d8fe7-b234-45b3-8021-e2bb0c949fe0


https://github.com/XLabs/portal-bridge-ui/assets/69044575/3744660f-649a-4408-81c4-c8f831638abb

![Screenshot 2023-08-14 at 5 21 29 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/fa48b00e-cf49-4236-8661-f04edab4384c)

**Comment by SamantaCasal** [comment]
FYI: @yuli-ferna  
Sui Wallet and others can be connected, but tokens are not displayed
![Screenshot 2023-08-14 at 9 34 58 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/a547a9d0-0077-4b6d-b6ce-9053775873f6)

**Comment by yuli-ferna** [comment]
FYI: @SamantaCasal 
Sure, It was an URL problem, I think with this change It can work https://testnet.portal-bridge-ui.pages.dev/167aff0c53/

**Comment by SamantaCasal** [comment]
QA ok! 
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/bba2abc3-9b56-44d9-8cbe-014dfa767221
