### ISSUE TITLE
[enhance] Update banner text at the top to include "Arbitrum"

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#286]
**Task**
Update banner at the top of portalbridge.com to include "Arbitrum" in the text

**Acceptance Criteria**
- Existing text should be updated to "Experience frictionless USDC transfers between Ethereum, Avalanche, and Arbitrum with Circle's CCTP."

**Comment by mliu-xlabs** [comment]
![Image](https://github.com/XLabs/portal-bridge-ui/assets/130170527/c594a18b-afa5-4156-bbc1-4085ecc1f059)

**Comment by SamantaCasal** [comment]
Tested from: https://testnet.portal-bridge-ui.pages.dev/cc2cce4272/#/transfer
**Evidence:** 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/9d610d81-62a1-4ec0-849c-0c154b292624)


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/0a36bce5-9b94-4bd4-a340-4b93713b1b99)
