### ISSUE TITLE
[enhance] add support for FIN wallet (Sei) in Portal Bridge

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#297]
**Task**
Add support to Fin wallet for Portal Bridge. Fin is a wallet for Sei network.

**Comment by mliu-xlabs** [comment]
is this something that Yuli can do? @sebastianscatularo

**Comment by sebastianscatularo** [comment]
yep, 
- we need to import the module from the sei wallet aggregator [@xlabs-libs/wallet-aggregator-sei](https://github.com/XLabs/wallet-aggregator-sdk/blob/master/packages/wallets/sei/package.json)
- and add a context [src/contexts/SeiWalletContext.tsx]([src/contexts/SeiWalletContext.tsx](https://github.com/XLabs/portal-bridge-ui/pull/157/files#diff-067ec4886ebf60218cd7440e3477dfa5ee54e06b4b6d5987ac1987c98b195174))

I think this was done by the folks on the [add sui support pr](https://github.com/XLabs/portal-bridge-ui/pull/157/files)

**Comment by sebastianscatularo** [comment]
it would be included as part of #199

**Comment by sebastianscatularo** [comment]
completed as part of https://github.com/XLabs/portal-bridge-ui/pull/403
