### ISSUE TITLE
[support] unable to redeem Sui -> Polygon（Ticket #7483）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Information: Cannot redeem the token to the target chain.
Error message : "cannot estimate gas; transaction may fail or may require manual gas limit"
Source chain : Sui
Target chain: Polygon
Source Address: 0x29c05c0d92be3463ab90b5b74409cc74bd3785ba786096a2903013c362cdce94
Source service: Suiswap
Asset type: Token
Source Tx: 8hboQ2hJnp9PQRu86dutTcHKMzQ1ui5efawYcvn74VMt
```

### Current Behavior

Unable to redeem

### Expected Behavior

Manually redeem for users

### Anything else?

<img width="1120" alt="1" src="https://github.com/XLabs/portal-bridge-ui/assets/83527164/c49cbc77-3fc6-4953-9be9-5d4daf99e840">

**Comment by sebastianscatularo** [comment]
@willis20188 this is a transfer with payload and seems to be a transfer that needs to be redeemed by a relayer, please ask at Slack channel for support on this

**Comment by willis20188** [comment]
It was lodged on Slack three days ago, but no response or solution has been received.

**Comment by sebastianscatularo** [comment]
this tx was relayed, closing it
