### ISSUE TITLE
[support] <Metamask sometimes fails to connect>https://github.com/XLabs/portal-bridge-ui/labels/medium

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: ALL
- Source Chain Wallet: ALL
- Target Chain: ALL
- Target Chain Wallet: ALL
- Asset Type: ALL
- Tx:
```

### Current Behavior

From the user: "when click on Metamask nothing happens, it does not connect". 
I experience this on my end sometimes and it think it is probably a local issue with metamask.
 
**workaround : Hard refresh/opening a new window on incognito mode.**

![metamask_prompt](https://github.com/XLabs/portal-bridge-ui/assets/64994788/33155896-cd10-41d0-8628-b3e03a8e059d)

**Comment by sebastianscatularo** [comment]
duplicates: https://github.com/XLabs/portal-bridge-ui/issues/306, refer to https://github.com/XLabs/portal-bridge-ui/issues/306 for updates
