### ISSUE TITLE
[support] Metamask can't connect to Portalbridge（Ticket #7574）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:ALL
- Source Chain Wallet:
- Target Chain:ALL
- Target Chain Wallet:Metamask
- Asset Type:Token
- Tx:
```

### Current Behavior

The user has been trying to use Portal Bridge since Friday,but on clicking Metamask to connect my account, the user get `User rejected the request` without getting the popup of Metamask.

The user said: if I click on 'connect' - MM does not show up, but Wallet Connect works.

### Anything else?

![1](https://github.com/XLabs/portal-bridge-ui/assets/83527164/fb25d85c-7ae2-4647-9fd3-5093ad303939)
![2](https://github.com/XLabs/portal-bridge-ui/assets/83527164/d7bc2a09-a6a9-4521-9416-1dde8bdd7b7b)

**Comment by willis20188** [comment]
User report: He is able to connect MM if he chooses the source network as BSC, but if he chooses BSC as the target chain, MM does not show up.

**Comment by Dahtank** [comment]
Another user Ticket #7587 encountering problems with MM

https://github.com/XLabs/portal-bridge-ui/assets/141799468/1a74a8ea-7a73-413c-9ad2-786a274ffcc8

**Comment by sebastianscatularo** [comment]
also reported at: #305

**Comment by SamantaCasal** [comment]
Tested from: https://preview.portal-bridge-ui.pages.dev/b9697fd91f/#/transfer
QA OK!
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/2a839b17-1a02-47ad-9ecd-275ca07f1262


https://github.com/XLabs/portal-bridge-ui/assets/69044575/b18e3b22-4a2c-4c92-8640-31eac261e7e2

**Comment by yuli-ferna** [comment]
This problem is related with: #295 

I think the problem is when we mix an EVM's wallets in source and target like Phantom and Metamask. [Here you have an example](https://github.com/XLabs/portal-bridge-ui/issues/295#issuecomment-1675012272)

I test also in this link: https://testnet.portal-bridge-ui.pages.dev/b9697fd91f/#/transfer

**Comment by SamantaCasal** [comment]
QA Fail: The bug still happens with SOL-BNB connecting Phantom and Metamask wallet.
Tested from: https://testnet.portal-bridge-ui.pages.dev/b9697fd91f/#/transfer
Evidence:
https://github.com/XLabs/portal-bridge-ui/assets/69044575/d905e1ab-7196-47c6-8f9b-3c23438befa7

**Comment by yuli-ferna** [comment]
For now, I can give you an alternative solution in the meantime. By following the steps below:

* Open phantom and change the "Default App Wallet" setting and select.
* Reload the page and check that you have updated the settings.
* Choose the assets that gave the bug in the first place, and go to step 2, which should no longer have a problem when selecting Metamask.

Tested from: https://testnet.portal-bridge-ui.pages.dev/b9697fd91f/#/transfer

Evidence:

https://github.com/XLabs/portal-bridge-ui/assets/35125931/cf3193c6-e8c1-4e8d-ac4c-3a6a449a7e92
