### ISSUE TITLE
[support]  cannot redeem USDC on arb（Ticket #7576）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Although successfully redeemed, it shows as the Solana chain, not the Arb chain
Information: cannot redeem USDC on arb
Steps to recreate: redeem workflow
Expected output: 4400 USDC on arb
Source chain: eth
Target chain: arb
Source Address: 0xc9a6db6a724de85ef5be79ba04b7d144dc387801
Target Address: 0xC9A6dB6a724dE85Ef5BE79BA04B7d144dC387801
Source service: warmhole portal usdc bridge
VPN : yes mullvad vpn
Asset type: Token
Token : USDC
Source Tx: 0xd2fe04a0949083dd3283aa4d33f14f9bde20eb4b472b03008ab9ce41d0533294
```

### Anything else?

![123](https://github.com/XLabs/portal-bridge-ui/assets/83527164/915e411c-3e82-4d93-99b5-a5cd4dd986b8)

**Comment by sebastianscatularo** [comment]
@willis20188 Yes, it is because it is a CCTP VAA, which has a different format than the token bridge. So basically, this tool is not meant to check CCTP transfer status/details. @mliu-xlabs, @hernandiegosavio, maybe we could explore this a bit more to add support for CCTP. Adding you to this discussion so you're aware of it.

**Comment by willis20188** [comment]
cool !  thans a lot! @sebastianscatularo

**Comment by mliu-xlabs** [comment]
@willis20188 what is the user trying to get to? Are they looking for specific CCTP information regarding their transaction?

the solution will be two-fold if they are looking for more detailed information on their transaction:
1) We could explore adding a banner when we detect CCTP transaction -> point them to whscan
2) Support CCTP transactions in whscan (which we are planning for already anyways)
