### ISSUE TITLE
Can't receive fund in target wallet (source chain SEI) TICKET : 7596 l 7595 l 7593 l 7592 l 7591

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown

TICKET 7595

Source chain : Sei
Wallet source chain: sei1m23s7lqj4n2rsz8nnxqazptnyptr25mkycc7vk 
Target chain: Arbitrum
Wallet target chain: 0x4731223a7B5aC0C425f1f35D0BDF6D340a93a181
Transaction: https://www.seiscan.app/pacific-1/txs/D63539FB5321BD94B161132B49A44B5BEC1029151AF667C9F9D0FC60270BA6F4
```

### Current Behavior

hey, fund are not arriving in target wallet (here its arbitrum, but 6 others users have as target chain : Polygon and same issue) 

when they refresh it said "error transaction declined"

![0f745f5df06da45e21da22fc7a77d1f0](https://github.com/XLabs/portal-bridge-ui/assets/102968460/97de7f76-cb93-4d4b-a8fe-9a9adcc51d5f)

### Expected Behavior

receive fund in target chain

**Comment by dry2022** [comment]
Source chain : SEI Network
Wallet Source chain : sei1zet42n890rjafda3py0dq7h7sm3wlj8tfhyzep

Target chain : Polygon (Matic)
Wallet target chain : 0x5BE405bC18f129e7bf7c19b818C501A3bd87f2A7

Tx: A95665F780D81A57E5358240C46E169DEE9B5191729B5EB42624C6025AE48BFA

same issue for this user!

**Comment by dry2022** [comment]
Source Chain: SEI

Wallet: sei1gvwap80kr4wet88z99chrhpzxneh4kfnqeketx

Targat chain: Matic

0x039430a44Cf6610CFf018d562C660D010eA1A4e1

tx
https://www.seiscan.app/pacific-1/txs/CD7B7C857C24972935C096C7DF958C9F81590216744C5777852DB2714517B4A3

same here too

**Comment by dry2022** [comment]
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/c72aca78-2df9-4434-a82a-9fc69cd3f5f6)

most of the user see this before refreshing

**Comment by dry2022** [comment]
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/5b123fc7-201e-46a3-85c2-9d2fc7780ee6)
most of the user see this as error

**Comment by dry2022** [comment]
TICKET 7592 : 

Source chain : SEI
Wallet Source chain : sei1fystf3mra8y2mqt0etwrsw0y4cvl04h30hnlsz
Target chain : Polygon
Wallet target chain : 0x836f5473B40F6E9581ae18D4821Ec1892dEE5ccC
Tx: https://www.seiscan.app/pacific-1/txs/1E918E3C60FE45DCDB8402C0D530E2683FAA4A112A3E80EBE7AFCC91E16BE944

**Comment by dry2022** [comment]
I have no contact with them, as its a wormhole UX all the user come to us

**Comment by dry2022** [comment]
sei support blocked all their channel so nobody can contact them

**Comment by yzang2019** [comment]
@dry2022 We(Sei) are looking into this issue and discuss a solution, stay tuned, we will keep you updated

**Comment by dry2022** [comment]
thanks for your message @yzang2019 let us know when u have something :)

**Comment by sebastianscatularo** [comment]
the team is investigating this, I'll keep you posted

**Comment by philipsu522** [comment]
Hey folks,

The issue came up because the Wormchain (maintained by the Wormhole Guardians) backed up due to the fact that the configuration set by the relayers resulted in batch transactions missing. We've worked with the relayers to update the configs to resolve this issue. We've also updated the sei app to allow you to find VAAs using your sei transaction https://app.sei.io/bridge/recovery which you can then go to https://www.portalbridge.com/#/redeem to redeem your funds.

**Comment by drisAloma** [comment]
Okay cool, thank you!!

**Comment by Dahtank** [comment]
I think its should be ok to close this :)
