### ISSUE TITLE
[support] During the redeem process, an error page appeared（Ticket #7639）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Information: During the redeem process, an error page appeared.
Error message : An unexpected error has occurred. Please refresh the page.
Steps to recreate: redeem workflow
Expected output: 
Source chain : Aritrum
Target chain: Sei
Source Address: 0x7dda9cda91dd8115cc1c3406ebf34bdb00678838
Target Address: sei1j2pffy6acqpjs24rkh7sucsv04qdguth3r5qkd
Target wallet : 
Source service: https://app.sei.io/bridge
VPN : 
Asset type: Token
Token :
Source Tx: 0x74538e75be3cafc931d651a84444105efec382f32f785cc2a5a9b77fb0a0dc37
```

**Comment by willis20188** [comment]
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/bae42f43-b720-4202-af67-a00e811bc95a)

**Comment by sebastianscatularo** [comment]
@willis20188 could you attach the developer console output?

**Comment by Dahtank** [comment]
Hi all, I believe this is because SEI is not launched on PortalBridge yet

**Comment by sebastianscatularo** [comment]
@Dahtank Sei users will be able to redeem some VAA through Portal Bridge. Just an FYI, it would be good to have the error details displayed, so we can provide a better error description or handle the case more effectively

**Comment by willis20188** [comment]
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/bd1b95b3-ad8d-4c55-8f86-1a9f769357f5)

**Comment by Dahtank** [comment]
@sebastianscatularo Does redeem VAA through Portal Bridge only works for outgoing SEI transactions? Can we generate the VAA for incoming SEI transactions as the SEI bridge recovery doesn't allow users to generate SEI incoming TXs

**Comment by Dahtank** [comment]
I think it should be ok to close this 😃
