### ISSUE TITLE
[Planned Outage] Banner messaging for outage - Heads up message/downtime warning message

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#318]
**Task**
There will be a planed outage coming up - we will need to add a banner message during this outage window that token transfers will not work. Warp and the Foundation is currently working on messaging.

Guardian upgrades will start Monday 8/21 at 6AM UTC so we should plan messaging close to that

**Requirements**
- heads up message
    - **Friday 8/18 8PM UTC**
⚠️ Wormhole Upgrade Approaching - Expect Temporary Downtime: A required upgrade is being coordinated and executed by the network of Wormhole Guardian (validator) nodes to add Gateway to the Wormhole stack. Please take note that token bridging will pause for several hours on Monday, August 21 around 6AM UTC during the upgrade.

**Comment by mliu-xlabs** [comment]
Bullet point summary:

- Gateway launch requires a consensus-breaking change to wormchain
- Accountant runs as a contract on wormchain, and blocks token transfers until approved
- The way Cosmos chains performs consensus-breaking changes is to use an in-protocol method of specifying a block height at which the chain is paused until a node upgrade
- We're recommending to Guardians a specific window starting at this block height after which they should upgrade their node
- All WH token bridge functionality (Portal, Carrier, Connect, other dApps) will stop working until 13+ Guardians upgrade their wormchain nodes

**Comment by Gpluv** [comment]
[Design Here](https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=761-349&mode=design&t=yikw8OSuHHHFXYrM-4)
