### ISSUE TITLE
[Planned Outage] Banner messaging during outage

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#319]
**Task**
During downtime for guardian upgrade, use this banner:

- downtime message 
    -  **August 21, 2023 6AM UTC**
⛔️ Wormhole Upgrade In Progress - Temporary Downtime In Effect: A required upgrade is being executed by the network of Wormhole Guardian (validator) nodes to add Gateway to the Wormhole stack. Token bridging is currently paused. Monitor the live status of the upgrade [here](https://docs.wormhole.com/wormhole/reference/upgrade).

**Comment by Gpluv** [comment]
[Design Here](https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=771-536&mode=design&t=yikw8OSuHHHFXYrM-4) @mliu-xlabs @sebastianscatularo
