### ISSUE TITLE
[Planned Outage] Banner message after upgrade is complete (after downtime)

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#320]
**Task** 
Banner messaging after downtime has been complete:

- uptime message - whenever things are back online, keep banner up for 24 hours
    - **August 21, 2023 9AM UTC**
✅ Wormhole Upgrade Completed - Back Online: A required upgrade was completed by the network of Wormhole Guardian (validator) nodes to add Gateway to the Wormhole stack. Token bridging is now live.

Longer than Expected Message (just in case)
- 
Date and Time TBD
⛔️Wormhole Upgrade In Progress - Temporary Downtime In Effect:** The upgrade is resulting in slightly longer than expected downtimes, please continue to be patient while the Guardian network completes this network upgrade.

**Comment by Gpluv** [comment]
[Design Here ](https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=771-618&mode=design&t=yikw8OSuHHHFXYrM-4)@mliu-xlabs @sebastianscatularo

**Comment by mliu-xlabs** [comment]
@sebastianscatularo we will need to watch this one just in case it goes back live after this time.
