### ISSUE TITLE
[support] usdc sui to usdc eth relayer bridge. but tx stuck（Ticket #8033）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Error message : cannot estimate gas
Steps to recreate: redeem
Source chain : SUI
Target chain: ETH
Source Address: 0x919229f0766292eddaa6e092fb87589a79ceba5527f096a0d78b87a60ac616b9
Target Address: 0xDA44D84f8DE69fEBDa4C4e0B89fF24077413f4b0
Target wallet : METAMASK
Source service: https://www.portalbridge.com/sui/
VPN : no
Asset type: USDC_SUI
Token : USDC
Source Tx: H18FVuSRz2uTqhYgyEoEgTXnYgV5jsKVodes9rdoLZRs
```

### Current Behavior

usdc sui to usdc eth relayer bridge. but tx stuck

### Expected Behavior

Automatic Redeem or manual Redeem

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/c18a42de-c160-4281-9b69-4ec59317d5e1)

**Comment by dry2022** [comment]
any update ?

**Comment by sebastianscatularo** [comment]
tx shows redeemed, closing this

![Image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/b1b70ccb-57c7-4069-a404-207d9fd84a33)
