### ISSUE TITLE
[feat] [cctp] Add support for Optimism to USDC Bridge page [Deploy Sept 4]

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#337]
**Task** 
Add CCTP Optimism support to USDC-Bridge

**Acceptance Criteria**
Include Optimism as options as source and target for USDC bridging via CCTP on the USDC Bridge page

![Image](https://user-images.githubusercontent.com/130170527/262780148-8fdceed2-5223-435a-9939-878b85c3c729.png)

GO LIVE SEPT 4

**Comment by SamantaCasal** [comment]
FYI: @valentinoConti @mliu-xlabs 
Hi! Could you pass me the URL to test this feature? I checked in prod, but I still don't see it implemented ⬇ 


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/6f251c90-f0a0-4b68-b58f-4580840ba200)
