### ISSUE TITLE
[feat] Add Cosmos Bridge link to main page [Go-live: Sep 5]

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#342]
**Task**
Add Cosmos  link to main page

URL: https://www.portalbridge.com/#/transfer
- See top right links for USDC, Sui - put to the right of 'Sui'
- Link name is: Cosmos 

![Image](https://user-images.githubusercontent.com/130170527/263306737-f61719ac-5bcd-4d89-a0f5-4d19637f68af.png)

**Comment by mliu-xlabs** [comment]
This is NOT to go live until August 31st

**Comment by Gpluv** [comment]
[Design Here ](https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=822-394&mode=design&t=VB1NusuP3Uad62ns-4) @mliu-xlabs @sebastianscatularo

**Comment by sebastianscatularo** [comment]
@SamantaCasal https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/#/transfer

**Comment by SamantaCasal** [comment]
FYI: @sebastianscatularo 
✅ The design applies it's  OK! 
❗ The TRY IT NOW link redirects to https://portalbridge.com/cosmos#/transfer, Is that URL correct?

https://github.com/XLabs/portal-bridge-ui/assets/69044575/539f674f-a7ab-462c-a1f6-2f5e4fce18c6

**Comment by sebastianscatularo** [comment]
please, try again @SamantaCasal :)

**Comment by SamantaCasal** [comment]
✅  TRY IT NOW redirect to [Cosmos page](https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/)
❗ After selecting SUI, the page shows the hover effect to COSMOS and SUI, I point it out in the video.
FYI: @sebastian-xlabs @mliu-xlabs 



https://github.com/XLabs/portal-bridge-ui/assets/69044575/fe9edde2-d6e0-4e13-9e1e-8f9f17b0ff17

**Comment by SamantaCasal** [comment]
QA OK! 

✅  After selecting SUI, the page shows the hover effect to COSMOS and SUI, I point it out in the video.

https://github.com/XLabs/portal-bridge-ui/assets/69044575/5af729d3-5dc6-4b29-8fce-41fbe30ded0e
