### ISSUE TITLE
[feat] update bridge name links on main page to not include 'bridge' [Go-live: Sep 5]

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#343]
**Task**
Update link names so that they appear as the following:

- Token Bridge
- USDC
- Sui
- Cosmos

![Image](https://user-images.githubusercontent.com/130170527/263307720-d30698c2-8a94-4908-b57b-9d8f2218dd98.png)

**Comment by Gpluv** [comment]
[Desing Here](https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=822-394&mode=design&t=VB1NusuP3Uad62ns-4) @mliu-xlabs @sebastianscatularo

**Comment by sebastianscatularo** [comment]
@SamantaCasal https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/#/transfer

**Comment by mliu-xlabs** [comment]
@sebastianscatularo hey lets also remove "bridge" from token bridge

**Comment by SamantaCasal** [comment]
QA OK! 
Evidence:
![Screenshot 2023-08-30 at 3 40 34 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/69f2d19f-e077-4470-a73f-c921b58227cd)

**Comment by sebastianscatularo** [comment]
yes, that was a last time change requested

**Comment by SamantaCasal** [comment]
QA OK! 
This is the last version approved ⬇ 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/e93d4e6a-c8b8-4844-92ff-e6aa17c22095)
