### ISSUE TITLE
[feat] new banner for Osmosis Launch [Go-live: Sep 5]

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#344]
**Task**
Replace banner for a few days for the Osmosis launch on the portal bridge main page. Swap back to the new CCTP banner on Sept 4th

New banner:
Wormhole Gateway is now live on mainnet! Bridge your assets to Osmosis today.

**Comment by Gpluv** [comment]
@sebastianscatularo [Design Here](https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=822-383&mode=design&t=NCATx4d2BShzk4a1-4) 
![image](https://github.com/XLabs/portal-bridge-ui/assets/132391878/738aaed9-564d-4a44-887b-c9ae16d86b06)

**Comment by sebastianscatularo** [comment]
@SamantaCasal https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/#/transfer

**Comment by SamantaCasal** [comment]
Now we see the Osmosis banner and it is ok. I will try this ticket again on Sep 4th

**Comment by SamantaCasal** [comment]
This was postponed, I'm leaving it on hold until we have a new date.
