### ISSUE TITLE
[support] Cannot redeem transaction <ticket-9163>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Polygon 
- Source Chain Wallet: Metamask 
- Target Chain: Ethereum 
- Target Chain Wallet: Metamask 
- Asset Type: Token
- Tx: https://polygonscan.com/tx/0x2972b4167f49b3f65305dca5d3090ba17c87f18cc074551349c5cb6b644ae7f1
```

### Current Behavior

Error: "Cannot read properties". The user claimed the transaction was initiated on the token bridge but it is not showing on the explorer.
Usually, this error message would imply wrong transaction hash or wrong source chain chosen.

### Expected Behavior

Recover

### Steps To Reproduce

Redeem workflow 

### Anything else?

I am not entirely sure the user used the token bridge as the transaction method shows "withdraw" instead of "transfer tokens" as usual and the "to" info shows a wrapped ether contract.
Also, an approval transaction to use the bridge was recorded on-chain after the supposedly transaction hash the user provided.
https://polygonscan.com/address/0xfe9e1c5641c431e378124107f8ba00e529979e9e
![withdraw](https://github.com/XLabs/portal-bridge-ui/assets/64994788/26fb13ad-ef84-47e3-beac-a3edf4f3f4f2)

**Comment by sebastianscatularo** [comment]
not sure if this applies, As you said, I do not see a tx with Core Bridge or Token Bridge contracts

**Comment by drisAloma** [comment]
Right, the user is all good now though, pretty sure he/she did something else entirely.
