### ISSUE TITLE
[bug] Cannot register tokens for Osmosis transaction

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is not possible to register BSC, Polygon, Avalanche, Fantom, Celo, Moonbeam tokens for transaction to Osmosis

### Expected Behavior

User is able to register new token for transaction

### Steps To Reproduce

1. Prepare to send 0.001 FTM from Fantom to Osmosis
2. Observe that token needs to be registered
3. Click on Register
4. Observe that https://www.portalbridge.com/#/register is opened
5. Select Fantom as source and FTM as asset
6. Connect wallet
7. Open Target asset list
8. Search for Osmosis
9. Observe

### Environment

```markdown
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ / https://www.portalbridge.com/#/register
```

### Anything else?

[Screen recording](https://drive.google.com/file/d/1R6zm3FeY_4m7GWQS9VVsZihvzlmQ61IJ/view?usp=share_link)

**Comment by sebastianscatularo** [comment]
there was already registered a curated set of assets, as it was planned to not be supported by portal bridge at this moment
