### ISSUE TITLE
[bug] Search is not working in All Tokens tab

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Search is not filtering out results

### Expected Behavior

Search result are filtered out

### Steps To Reproduce

1. Select Network (e.g. Fantom)
2. Click on Assets
3. Select All tokens
4. Click in Search window
5. Start typing in Asset name
6. Observe

### Environment

```markdown
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
```

### Anything else?

[Screen recording](https://drive.google.com/file/d/1Z76pPylAhgOUitgMDbD3yKOR43cyDQXd/view?usp=share_link)

**Comment by M-Picco** [comment]
Moving this to https://github.com/wormhole-foundation/wormhole-connect/issues/844
