### ISSUE TITLE
[bug] "Source chain gas estimate" value is not calculated

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Source chain gas estimate" is not calculated when sending WETH from Osmosis (Leap) to Ethereum (Metamask). 

### Expected Behavior

"Source chain gas estimate" value is calculated.

### Steps To Reproduce

1. Connect Leap wallet in From section
2. Connect Metamask wallet in To section
3. Prepare to send 0.00001 WETH (Ethereum) from Osmosis to Ethereum
4. Expand "Total fee estimates" section in Preview
5. Observe if fee is calculated

### Environment

```markdown
- OS: macOS Monterey Version 12.6.7
- Wallets:
  Leap osmo167mxuwxeqs0cg6kf7s92l7uxrkhzzeky5s0f4t 
  Metamask 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
- Browser: Google Chrome Version 116.0.5845.110 (Official Build) (x86_64)
- Build: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
```

### Anything else?

Attachment:

![Screenshot 2023-08-31 at 12 17 46](https://github.com/XLabs/portal-bridge-ui/assets/10746654/32643a76-b63b-46df-a5a0-af1af7e08f2d)

**Comment by M-Picco** [comment]
Moving this to https://github.com/wormhole-foundation/wormhole-connect/issues/852
