### ISSUE TITLE
[bug] Transaction Solana -> Osmosis fails

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Error: 403 :  {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}, "id": "755cba1d-ed53-4029-a6a9-2deb791d99e5" } ` is shown after button Approve and proceed with transaction is pressed

### Expected Behavior

Transaction moves forward and is completed

### Steps To Reproduce

1. Prepare to send 0.001 SOL from Solana to Osmosis
2. Click Approve and proceed with transaction
3. Observe

### Environment

```markdown
Phantom wallet connected at Sending From Section
Keplr wallet connected at Sending To Section
Console is opened
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
```

### Anything else?

https://drive.google.com/file/d/1aM_b7WjiSS8u5dfe95ONHcc5lRU3HCah/view?usp=share_link

<img width="1352" alt="Screenshot 2023-08-31 at 12 24 59" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/dda9bec6-2fb1-4769-b1d0-1de18d750926">

**Comment by M-Picco** [comment]
@AigaD The solana RPCs should be modified now. Please give it another try and let us know if you run into the same problem again.

**Comment by AigaD** [comment]
Seems good now, closing the issue.
https://explorer.solana.com/tx/2TKQhHfVMHkXVT5jS8fpbJZ5Ev513wDBYTRo5PY78pjwDNMxCoFkkkmbnR2Q632vUBG9Va64RoE7bfuPgbCU7Jzt
<img width="1337" alt="Screenshot 2023-08-31 at 18 08 24" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/c036d0ac-47ca-429e-98bb-e444dd7478f4">
