### ISSUE TITLE
[bug] Balance is incorrectly shown in Metamask notification "Add suggested tokens"

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Balance is incorrectly shown in Metamask notification "Add suggested tokens".

Send from tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/B845FEA8C4F1300E4D1044171D4E1817CDA0D2C9ACF403A0F8B99D2CE5DF2764)
Send to tx: [Etherscan](https://etherscan.io/tx/0x69a8a9879cd11b2095f69b754fd480c0f1ef3b70b67da663c57014f4b8852e3b)

### Expected Behavior

The correct balance is shown in Metamask notification "Add suggested tokens".

### Steps To Reproduce

1. Prepare to send 0.00001 WETH (Ethereum) from Osmosis (Leap) to Ethereum (Metamask)
2. Click "Approve and proceed with transaction" button
3. Click "Claim" button on Redeem screen
4. Click link "Add WETH to your wallet"
5. Observe WETH balance in Metamask notification 

### Environment

```markdown
- OS: macOS Monterey Version 12.6.7
- Wallets:
  Leap osmo167mxuwxeqs0cg6kf7s92l7uxrkhzzeky5s0f4t 
  Metamask 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
- Browser: Google Chrome Version 116.0.5845.110 (Official Build) (x86_64)
- Build: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
```

### Anything else?

![Screenshot 2023-08-31 at 13 00 17](https://github.com/XLabs/portal-bridge-ui/assets/10746654/9e4e52e5-5179-4c5e-9109-74018be2af4b)

**Comment by M-Picco** [comment]
Moving this to https://github.com/wormhole-foundation/wormhole-connect/issues/892
