### ISSUE TITLE
[bug] Transaction Osmosis-> Aptos fails at Claim

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`TypeError: Cannot read properties of undefined (reading 'data')` is shown in the console and transaction fails at claim

### Expected Behavior

Transaction is successful 

### Steps To Reproduce

1. Prepare to send 0.001 APT from Osmosis to Aptos
2. Click Approve and proceed with transaction
3. When option is give, click Claim
4. Observe

### Environment

```markdown
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
Keplr wallet connected at sending From section
Nightly wallet connected at sending To section
```

### Anything else?

[Screen recording](https://drive.google.com/file/d/1Q8acdpp0KK2TXvlb4juBUG2pcHGyMi4r/view?usp=share_link)
https://www.mintscan.io/osmosis/transactions/D54F23240CB2F02B24E6B69C9D61E4107B5276D6534A276A96AABBE022996463

**Comment by tsadovska** [comment]
@AigaD Ticket can be closed to keep track on https://github.com/wormhole-foundation/wormhole-connect/issues/669
