### ISSUE TITLE
[bug] Osmosis Network left connected at Sending To section with non-supported wallet

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Osmosis Network is left connected at sending To section, even if Osmosis non supported wallet is connected

### Expected Behavior

Only wallets are left connected when user returns to bridge screen, or if Osmosis network is by default left connected at sending To section, disconnect non-supported wallets

### Steps To Reproduce

1. Prepare to send 0.001 SUI from Osmosis to Sui
2. Click Approve and proceed with transaction
3. When option is give, click Claim
4. Click on Bridge more assets
5. Observe wallet / network connected at sending To section

### Environment

```markdown
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
Keplr wallet connected at sending From section
Sui wallet connected at sending To section
```

### Anything else?

[Screen recording](https://drive.google.com/file/d/11Yef4Hqm1lRRobGNBHudUzBoI_3QDJ6R/view?usp=share_link)

**Comment by AigaD** [comment]
If user wants to switch sections after transaction was completed the connected wallet and Network both switches places, even if the Network is not supported by the connected wallet.
In attachment Osmosis Network switches together with Metamask wallet.
Attachment:

https://github.com/XLabs/portal-bridge-ui/assets/91047061/35ab0e2d-daad-4b6a-a76b-4a425de23930

**Comment by tsadovska** [comment]
Issue is also reproducible on https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/ [Mainnet] when user prepares transaction details, clicks on "Terms of Use" link and navigates Back to the main screen. Osmosis network and Metamask wallet remained connected in "To" section with the following scenario:

1. Click Swap button (actual result: Osmosis network is in From section)
2. Connect Leap wallet in "From" section
3. Select Ethereum network in "To" section
4. Connect Metamask wallet in "To" section
5. Prepare to send 0.00001 WBTC 
6. Click "Terms of Use" link
7. Click Back button
8. Observe "To" section


https://github.com/XLabs/portal-bridge-ui/assets/10746654/e7f49ca8-4122-488f-8432-7662bd9f9bcf

**Comment by AigaD** [comment]
Closing, issue is no longer reproduced.
Tested from: https://portalbridge.com/

Attachment:
Scenario when clicking on Terms of Use button:
https://github.com/XLabs/portal-bridge-ui/assets/91047061/7d748de5-e147-4a8d-b97c-9f85ece19d82

When returning from transaction screen:


https://github.com/XLabs/portal-bridge-ui/assets/91047061/4fddeb33-6469-4a16-a323-351e00cb8c74
