### ISSUE TITLE
Ticket 9182 Multiple TXs -> Aptos

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:BSC/POL/ETH
- Source Chain Wallet:
BSC/ETH:0xE58564b8Ce8344AFDFE3a111bC0B541ee7F5f7Fa
POL:0x5a58505a96d1dbf8df91cb21b54419fc36e93fde
- Target Chain:Aptos
- Target Chain Wallet:0xcc7d980aebd54d942fed5609e28df6ee9688df23111f55cfedbf3b42ff68c05b
- Asset Type:BUSD,USDC,WETH
- Tx:
0xc67a3e36255125c86d72a8d554150ea266c04c725f12dba6cb952453e0d22bfc
0x310f71eac61be3834caad0b87edbc8fd5123aa705d9e3f8bb27e9d489460dde4
0x31a56b92a2a537dd3a80ac4c27ab20188ee28183afc871a75b70eb756824c07c
0x2bc78a540425d1803a7f4cab2ea5057483872353307b331729ec9a6a88ad093b
```

### Current Behavior

Error while redeeming
"There are not enough valid signatures to repair."
Transactions are all almost 300 days old

### Expected Behavior

Able to redeem without issuees

### Steps To Reproduce

1. https://www.portalbridge.com/#/redeem
2. Connect Source wallets BSC/POL/ETH and TXID
3. Error "There are not enough valid signatures to repair."

### Anything else?

![Screenshot 2023-09-01 at 16 46 11](https://github.com/XLabs/portal-bridge-ui/assets/141799468/3cceb294-8368-4d22-80eb-712f409ca88b)

**Comment by sebastianscatularo** [comment]
@Dahtank those tx need to be re-observed, I've asked the team to do it, I'll keep you posted

**Comment by Dahtank** [comment]
Can i check for an update for this?

**Comment by drisAloma** [comment]
Hello! @sebastianscatularo 
Any update on this?, the user is getting bittered about it

**Comment by sebastianscatularo** [comment]
@drisAloma I'll check tomorrow with the team, and get back to you

**Comment by drisAloma** [comment]
Ah, okay
Thank you!🙏🏽

**Comment by sebastianscatularo** [comment]
@drisAloma here are the new vaas that the user should be able to use to finish his transfers

|tx|vaa|
|--|--|
|0xc67a3e36255125c86d72a8d554150ea266c04c725f12dba6cb952453e0d22bfc|01000000030d00be8ac084783eb58392bb9eb6863044d7a05e0982adc0eec2f6c07fcf3e1fdf452a0536a88f3acf8a686d2b9e92c143654b81c440e8d8cc7ddb995e297ab68ef60101a3852871e07130d81f4dba7e1b5a4df163824f74c4b85d12993bff69a7c69cb079552e23538ef2f52ee783ea6a3afb92dbd7c889e5cd1d361896b7ca79afb0ea0103fa60ede65473fc5f9ae765ed2f6ae1bb31ac4da6d98b702544dfa1a10393b1040f09b28379ab1f6c5888c575249bc49de6d1914b96ce2595a19f2179fc69a5c201053b8814057b928a84029dcc3565415778da6eef683fc7531e5cf0192213bccd5e0f6ad821b19bd473720d702e4100eb73db1ace1d1faa4ec2b929b445f20292860106119cad5fe7b369207eea7ff7fbe8f80acd0a2385acc3a1228e3bceeb7b6529d26396a7c0d5ce93f0c6c0a129eca01272ac3cbc37d90f34f911f6016f5aafeec90107a0436dade0eff0d1772756a74824b861d553e96d0290332a3e157b6474cea4f6448c0e2774edb366216fad78fcce0b62debc3ebc079a3eec0f1e3d5202e0daf40109919c0d9cbe6fb72604bc532689104d835638ea5375ff7be8a7e1a9978ac5439462c188d081ada5392a0d396f6f4d1c75cac11b687fab860d249e6b907892381d000a8c3579d354246ab5b995d634d3d498d16a4dffab9f0ebc459a6f7c329b1c34b85d2b8ea6d64d7d8175627d0ef63db44d4d21197c21e74607af77a19fc337f37d000ba9b62a483971e77e4c1182e9788946c624c37fbe170c902c0ebef629d88c4a582938b4e6eb67942f791de23b5cce6f49220c772cd29bfe5a7cb9f82f1a97bb95000dffd7100231744a007ba187d065c9022ab5459aeab4f32afdcd833db8e7fbb91b18911b91b4ef5079ded4568f3724e64bebec2acbe1e9f2130a221efab9f119d1000fb17fe092c075a26fe72091fb4b258f091defb7faacdf2fee9796268f0f4b790443d799a28cca3e4b902b41ddad852949ec6a9591c7722a67ed4e74d4d8bb2ed20011e71a0a15264711e14fcb2f76e0390dc1cd95ee3c1f8aa8ed5c495a1814ecdccb6556e99350edc6757814e9cc45a9a192720afaf0e17653409abf298ebadf2927001203f79e796c19d54d7de649009e00391e2929b7be53178c60b74053edc0142ff8276f0fa1c69782c4529192e06ce38a213e39314c2d5ba779658c81b1cfc9c5d101636be4d1bb3b00000004000000000000000000000000b6f6d86a8f9879a9c87f643768d9efc38c1da6e700000000000349e10f0100000000000000000000000000000000000000000000000000000000b2d05e0000000000000000000000000055d398326f99059ff775485246999027b31979550004cc7d980aebd54d942fed5609e28df6ee9688df23111f55cfedbf3b42ff68c05b00160000000000000000000000000000000000000000000000000000000000000000|
|0x310f71eac61be3834caad0b87edbc8fd5123aa705d9e3f8bb27e9d489460dde4|01000000030d014e259426c66966d32d931cb6a454441ae7cb9331dc0089145cdd47650e0f106d0f4fd23f728389ebeba1a09da46014989d7a95e7850af80fc63292f67c9b62c60102b5cec6f849a2edbe17ff61bf1f881ffcae2d8b4c57c5dac9ff9db9f7c71ec7453c23f114251c9edecd68141ed475bfd723fc836a9b0959a0c81df77a0c27e92c000329028d2af3bb493ba75a751c1b466d5747f954f615a937dee8096a21032d918530054966f0572e4427b4600df330f170980ad172491a70e18edb60cfd17874eb0104f9424173325f6f502b3143a86160255fb91b17b50a7ecebe6bcbe98900e369c12c6c7f2c02926826b336e86d433738033d89895038683cb24c2c620ef3999b7e0106690cb1ccf8a8af65bd9e03acade652db50b55362491ae4a98b66a3220aac14b61baaddc0fb930ccd818e1deeed8210b048c5f01027498aae3c0156129163dc220007118c7c6f4a0f2d1e88c134d06f0083c8cd75c6f68700036ed8522a6f55df18990de87265e503eca665571ccf1fec2cdec6f9d48b1eb382d9197e60437d9b12f7010b962a7077502f3ac4e608f44a23e306355eb8e7604785f7b4c3d2d326207ddc650bd461f8225ba6e14f04a6d906f42161697dd95b35bfcf1282033b5a74213136010c1b50c1655ed5ecdd67814ea4c9f31956307a3ccc3f5ce359da66cfba9c8961211fcade04d1b5ad2a4cd9c6ffb73b7bda4cfed56b4d070dc4bdcc689b26b6dd6c010e0b00cef6a480655c362dde2e93027d74850705025279254cc94ed531aad295c604cdf1f58186654fb3a2ae44d0f1134cffc32fa449af663410379329c734b3e2010f19649b4e78fcbf48bbbb2220e052ab67892d3a1e193d3fc90553ddd3ddc18f77603d099e16989a3587b833d2837c56758c4f3284dc145b93bb21d499884d7d56011059600084019b8925b4b8fe9347f2fddcbd9eeb7b1401942f0b7aa8b8378e78d01c861077696138a44222c848ea19022c27031fb9f024e8147a9b4bdce8da7c8500112ce6a47394f422bd0ddb2f8e386876236a841882ba9290eaa4ff0dcff40cad0745c45411db7b9a3248ad82245a477d1466366973d18cb6b866d2cbe38be92a7e0012e20d1dc5e97a2ad330a11700d8408f2c322cd7c239d3966cd7c3c5ae9c72b71e6756ad9dbba244734a057c1d27190d9b3543c0626e3d1857d0c816a5d7e6cd6c00636ff740e444000000050000000000000000000000005a58505a96d1dbf8df91cb21b54419fc36e93fde0000000000013a8c0f0100000000000000000000000000000000000000000000000000000000000f42400000000000000000000000007ceb23fd6bc0add59e62ac25578270cff1b9f6190005cc7d980aebd54d942fed5609e28df6ee9688df23111f55cfedbf3b42ff68c05b00160000000000000000000000000000000000000000000000000000000000000000
|0x31a56b92a2a537dd3a80ac4c27ab20188ee28183afc871a75b70eb756824c07c|01000000030d00a206cca7bb8d668ac22929f3990fb0f78b2c68bbecaab80e0a36cd82f0dccfa25c46216a3e3791118face738c5cd1e3b8d0b44d05086ac9746ab22dc3f3c079300028363a48c2fe0016f4c76e662f5593843611a262170eca49a97d538b97da8f1300a2272bec639d2a1a79e895173abdbee2ff38918f992c441a91c73dd4df02fbb01030f9283b7c9ed23aefb1f61bcd7741c82e8caf6963100f36c2925fee68c13f762782b49db1794880fce0465bd727db27f7a4d48fa6c10edbab3bdb534650c1be3000490815c8942678f66107d3f0e44877ad91e92e960318a7d956e2ac4611c62616631a448d9ef92dc14908bfd26cc67937439eb7f8da3c7a5479037650eeca5224a0106687d44ee3e95786c533c7d2829ead141f4faef62bfff5a543302c28b413257e50ed0a1cfe6350c1d7f8db0de5ee90c82ec97aa3dc1f613628220956f3a55752e01077c885f5e05dca338d8fada7996e9277c5b84d88110ef6b9c01ba277fcba278b7418db04b12c9327155709b7b203f2ee05085a2514f2fc82136e932d384b19b86010c9e8e2c97f5a067150243b87308949dd2870e34da327592eac385c8a7a66358de7545d4c325c2f03da6351ad098eff5418e716ada93d4ef40574d8df311bb02d7010d56afc7683c5f59273cebaab471cf7a12305655e55512d3a99fb07b52b9f659eb514686bcd226fbe8969ee24842522e8f6ba04813761e2ad9f4439ca1bf0a72b9010ecfb157d5dea2824b77fa465c929658295a2198c68284edcd17a381a1f57c255635ad63d7f58ba7a90f468821bd5508f0717f49ed6a86191485f46e26cbe7671e000f429edb02747e439ed374dbd3f5562cfa0e1f07326c323e227934dc6ea6a6df600161ff1c5453b647dfd0fea668144d10986af4880d2488b28d038edda240e0760010b23e272571d7e470365912673c45425885d507ee07161bd3c343d8f8bb08dd27496e2a41402e702b7773c9ce16caf72e42af10edfbe297c45a20daa5250eced300111d8e9788d97f59b47bc47d4ea8f485ef2f7f4a15b306c263db55cbf732027644787197b6f32e90f1ae704010d1a12af1e0d7d3355e7e028d8d12a6e066bf5c6a0112a21560770d9b48a4c21ac06777a62460639dca74a13e27c0fcf0225a0f5c4a92762c533b8766856184a0bf7b33505ccd121225f4da67b21f5bb09ee6e79e254200636fb36f5d6c000000020000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa5850000000000016594010100000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480002cc7d980aebd54d942fed5609e28df6ee9688df23111f55cfedbf3b42ff68c05b00160000000000000000000000000000000000000000000000000000000000000000|
|0x2bc78a540425d1803a7f4cab2ea5057483872353307b331729ec9a6a88ad093b|01000000030d00909f14dd7eea76983121df8aab1d74e3258e15fa0be6bd3dd0b033c3ebfacfd559f59b1510cd23fded5afbdf5e5e44c31f898912b8cc6227ecc2493d9c17e82a0002b303981f43be9bda484d52c663ff558e7f73b1f400f9ce33636ae2f98bc8a4ae4be46192a8ba7877322a7a9ece4261b7f97d60f594fb62387bbb897c53fe2e8100030204b9089f68db7312f072c6471dc8a2892aa839b3892f54f38ca83caa295c984e5604c37a892e6a6d39b4c506de8b0046b31a49a34e30d84f16b459c0a046e101040cb364993e2a83d9fa9c0c26d40b8e131c8c0d9976475e004db896a51ca8cbd856b2e3bce7a4a2da91d5f21e175dcec54f93b9c29a23f60d9019c7c51bbf1734000503b11cbe9543362c0345fa86b619ad64accb38080af3624b39e2259d63f2619375c232b0a53c516c06c1fd5d7cc9bdd2c8c77ee1a9f224b0086b6c028e1a82b00107c64a9e9f38ef69d08684c149bf6a5a6142263d22ee9b62962b9ca2bb55a1db5553d6d6fce6974fad91b796288bb89e43330987093a58ababc41088c7b86bab8a010c6642819bc73560c8480576d93102f0f152776b3680de59cead491b9bc28f6a89222fb765a0cba3f068352a62440245341684e7671c7d4380fdfd70828fdea462010d22c7a7d0321ecef61f392f756bafc45308bd185474d405b398558ec0ee8ec2963c0959bec9bc0b8d58d2936e3119be388bee2f6765409336da9dab506828918c000e6f5ae364ebba5b0b6f8de0330e96b05bd12bb108df831301407ee35751ce38d56c457e542b613a78c97e497c71154a6d4e28467d0cec3ae1928d1d86a4394a25000f5696706c24a6afa5b929d82bddc756dfbd53f37587e04af5530ef33d963247b368a815e9b96a356bc461f11f4f8aa04c45544f867fb693bc4ca0b62a5814410c00104c84c9f93aa544bb8bd375c189f2da4b7c11704573fa1c5a7444ebb5f3e88579754a7073b97387cf0f2832bb0801ea3cff70b17d7057966720116dddb23a1c8001116ed4aeddf083f6d99d1fc4e891c91f4811042611c1905426bd613d569553eb9f6770679765c41df759ff888ca9d2db508dba0893f5aac13619f901931ecac34d0012feac1047c285aff585265bb7ac929386db8d92a6609646004876fbbcc0775c7c7e8be497412e5425cde6b7d33d5c5013be603d3c3f50c2d17a87d392df352b8a01636fe96f5333010000020000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa58500000000000165bb010100000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20002cc7d980aebd54d942fed5609e28df6ee9688df23111f55cfedbf3b42ff68c05b00160000000000000000000000000000000000000000000000000000000000000000|

**Comment by drisAloma** [comment]
Okay, thank you!
