### ISSUE TITLE
[bug] <The modal to connect Pear Web wallet opens 2 times>

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#376]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

User cannot enter password to unlock and use their Pera Web Wallet due to modal opening 2 times and password cannot be entered.

### Expected Behavior

That the user can enter the correct password and connect to the Pera web wallet

### Steps To Reproduce

1. In https://www.portalbridge.com/#/transfer
2. Select ALGORAND as the source chain
3. Select another chain as target 
4. Click on connect
5. Select Pera Wallet
6.  Click on Enter the passcode 

### Environment

- OS: macOS Ventura v13.3.1(a)
- Wallet: Pera Web Wallet 
- Browser: Chrome. Version 116.0.5845.140 (Official Build) (arm64)

### Anything else?

Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/9e62f0f0-d630-49d7-b069-06c07863c8f1

**Comment by mliu-xlabs** [comment]
deprecating
