### ISSUE TITLE
[support] cannot redeem Ones(NFT) on BSC<Ticket #9208>

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:SOL
- Source Chain Wallet:8n778RGpvNphHLuXJfSCeHKRhYHM149cfSxnsniVpLeK
- Target Chain:BSC
- Target Chain Wallet:0x49b9b8A64C433D8c6409c4dF1b7699a1129F27aD
- Asset Type:NFT
- Tx:https://solscan.io/tx/3c4mUcHNZpRLWTM87Svv2BvTeWBiGV858sMAZTgX5BbPf2qti9avWet9TR6aaxqNBXbyCRHiEQh8xxtDMTowYM8b
```

### Current Behavior

Information: cannot redeem Ones(NFT) on BSC
Error message : cannot estimate gas

### Expected Behavior

Redeem

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/817547a1-aca9-4af3-9cb9-e76ade145e4a)

**Comment by sebastianscatularo** [comment]
the NFT has been redeemed, check here https://bscscan.com/tx/0x7ba3ea396c3219c483998b708462163dad81c30727f0738cccc62d670a4d8ae5, I'll create a ticket to follow up the issue relate to the UI not showing the correct information.

<img width="1465" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/c64e027e-bafb-4d41-82f8-a59edfa5e0e1">

Tx VAA below
```
0x01000000030d006a20d097c35f97c0a8952257a9df554127ceee3b16e007e58cbe9fdaf87766ff20374f4f6867c8da5f726e47b94b97337827c059b2f48b62750eba302c2587a500010764f499b5b4dd0aa812e6dd028d0c2fc7de6055fbf7924008807482d5fa894a6f82c82ee64546a38c82fe96fa622cfe14fbd293c6b7dbddcfe57d3a7a3a62d601022c1c6c71befb91e622399bd23991c0c2e664882ea5357d47beb5dbcf7435da2e2fad6b3345e2a0d1fc6f6142ea5261ab44bc801f4612ed46e59738674e1b7092000485d69267b67dacd027cde78ec9ddc5e94599ec0e0bb6550ef8eeb3edb6491b277f7b335b45999b48b9e137c2d4f6ed3a069c2db656c3ce9a0682c62f24ea494d0106bffb81b362574332627a2a69466562b7aedebd43cb05670980ee3148713319d621435afc354bfcccdee1760cc6e50b24f5d53806d5781f2fa95cf458f619b3680108465fdbe4a72eda2beee759682421eea4bd2e83ec665618b96010d64e9a935c8c390e33ce063e7f8025378ec7b10114f2cbf0a8b37b2af6b7aed5edc6c08fb1290009636c7259b3378260df81b4a96461f6b07a8e29241403c2f5490bd77472a473081fc6ca35015d9ceb4d65122f55bafab3af23debbfe3a6f1b46a5c76cefa83ec5010ad4848c383d645c910e1391238f91a4e6f23575023699495ae8b59d1294e5679d42b8b8bcd5de5408ff2c343786b14ee6380cf2a1f4bfb2b6829b5c6ddb394fb1000ba6a08ba4579eeb0e6e9874bfbcc8b2ad1db64a8e1a13351f176d14a5a39803d03addb8fcce8ca617cf90844012112e5eb1ec64b1b331df6f87a07f05589340fb000c5a24c8b5e4918bddc10db4d75f13bb5c745fa07b4139830472201163d26d5e76743fba76ecddb825edc022f9e1c40794d947ced9d7d44a94c9f030a3f76ad3ed000d0ba40b798fb93edfe0d3411ceae368eb46c6932809dce09ab1383dd1aa718fb55edf95ffa357b9f96c767d3e2c6aa0f6104824500a8fa554cb5e0cd39d9937620011deb5b4f1622db63725943479dedd06b7f9792d498f2dc6e3eb69c4384a0809b2609a46dc4dc2d5c3146c106b2df7a260a343a3698d046896cbde6af8399fc062011244dd8b443a761c0451781299363004de3f59303612285c585fabd71dc0a779656e317933076617a4505dae0067e620823699e92a33c35e43d357fa3dd759832c0064f46dfb00015c3400010def15a24423e1edd1a5ab16f557b9060303ddbab8c803d2ee48f4b78a1cfd6b00000000000054172001010101010101010101010101010101010101010101010101010101010101010100014f4e455300000000000000000000000000000000000000000000000000000000546865204f6e6573202336363736000000000000000000000000000000000000260c002163de1c64d8bda3c8b141985c175c13e33295e8920214b8a701ffa375c868747470733a2f2f617277656176652e6e65742f664d73556c2d54796c6562774f726f554c466e4e7a66683642386f3857336f464b6e62345f724166704641000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000049b9b8a64c433d8c6409c4df1b7699a1129f27ad0004```

<img width="1209" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/8f5d2144-f087-42ce-a725-bd7c68f8523c">

is the same as Portal Bridge recovery page

``` 
01000000030d006a20d097c35f97c0a8952257a9df554127ceee3b16e007e58cbe9fdaf87766ff20374f4f6867c8da5f726e47b94b97337827c059b2f48b62750eba302c2587a500010764f499b5b4dd0aa812e6dd028d0c2fc7de6055fbf7924008807482d5fa894a6f82c82ee64546a38c82fe96fa622cfe14fbd293c6b7dbddcfe57d3a7a3a62d601022c1c6c71befb91e622399bd23991c0c2e664882ea5357d47beb5dbcf7435da2e2fad6b3345e2a0d1fc6f6142ea5261ab44bc801f4612ed46e59738674e1b7092000485d69267b67dacd027cde78ec9ddc5e94599ec0e0bb6550ef8eeb3edb6491b277f7b335b45999b48b9e137c2d4f6ed3a069c2db656c3ce9a0682c62f24ea494d0106bffb81b362574332627a2a69466562b7aedebd43cb05670980ee3148713319d621435afc354bfcccdee1760cc6e50b24f5d53806d5781f2fa95cf458f619b3680108465fdbe4a72eda2beee759682421eea4bd2e83ec665618b96010d64e9a935c8c390e33ce063e7f8025378ec7b10114f2cbf0a8b37b2af6b7aed5edc6c08fb1290009636c7259b3378260df81b4a96461f6b07a8e29241403c2f5490bd77472a473081fc6ca35015d9ceb4d65122f55bafab3af23debbfe3a6f1b46a5c76cefa83ec5010ad4848c383d645c910e1391238f91a4e6f23575023699495ae8b59d1294e5679d42b8b8bcd5de5408ff2c343786b14ee6380cf2a1f4bfb2b6829b5c6ddb394fb1000ba6a08ba4579eeb0e6e9874bfbcc8b2ad1db64a8e1a13351f176d14a5a39803d03addb8fcce8ca617cf90844012112e5eb1ec64b1b331df6f87a07f05589340fb000c5a24c8b5e4918bddc10db4d75f13bb5c745fa07b4139830472201163d26d5e76743fba76ecddb825edc022f9e1c40794d947ced9d7d44a94c9f030a3f76ad3ed000d0ba40b798fb93edfe0d3411ceae368eb46c6932809dce09ab1383dd1aa718fb55edf95ffa357b9f96c767d3e2c6aa0f6104824500a8fa554cb5e0cd39d9937620011deb5b4f1622db63725943479dedd06b7f9792d498f2dc6e3eb69c4384a0809b2609a46dc4dc2d5c3146c106b2df7a260a343a3698d046896cbde6af8399fc062011244dd8b443a761c0451781299363004de3f59303612285c585fabd71dc0a779656e317933076617a4505dae0067e620823699e92a33c35e43d357fa3dd759832c0064f46dfb00015c3400010def15a24423e1edd1a5ab16f557b9060303ddbab8c803d2ee48f4b78a1cfd6b00000000000054172001010101010101010101010101010101010101010101010101010101010101010100014f4e455300000000000000000000000000000000000000000000000000000000546865204f6e6573202336363736000000000000000000000000000000000000260c002163de1c64d8bda3c8b141985c175c13e33295e8920214b8a701ffa375c868747470733a2f2f617277656176652e6e65742f664d73556c2d54796c6562774f726f554c466e4e7a66683642386f3857336f464b6e62345f724166704641000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000049b9b8a64c433d8c6409c4df1b7699a1129f27ad0004
```

**Comment by sebastianscatularo** [comment]
ref https://github.com/XLabs/portal-bridge-ui/issues/378
