### ISSUE TITLE
Implement MSafe Wallet into Aptos

### ISSUE THREAD

**Issue by raop155** [XLabs/portal-bridge-ui#38]
# Description

Implement Momentun Safe Wallet Adaptor:

- https://doc.m-safe.io/msafe/developers/integrate-with-msafe-dapp/use-aptos-wallet-adaptor

**Comment by raop155** [comment]
Things to do to use Aptos MSWallet Adapter:


1. Update versions

"@manahippo/aptos-wallet-adapter": "^1.0.2"
- We need to bump the version to the latest 1.0.10

This impacts in the BlocktoWalletAdapter constructor.

![Pasted Graphic 1](https://user-images.githubusercontent.com/25652943/216144208-8b46860f-7560-4799-945a-d5a5e579492c.png)

**_We need to pass now this bloctoAppId._** (Where to find?)



2. Implement code
- After all the implementation in the code base

<img width="549" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/25652943/216146309-4a33ca62-f32e-4755-b60a-9436d260b112.png">
Always received “Unsupported”

So I started to find why this was happening, and found this:
“MSafeWallet only works in safe appstore iframe”, 
but no more information that could unblock me.

![Pasted Graphic](https://user-images.githubusercontent.com/25652943/216146330-d178693a-418d-40d3-8ec4-5d9698d6ea45.png)

3. Research

- Read forums, support, etc with no results
- Open issue in the repo, no response
- Join Aptos/MSWallet Discord

One “Aptos Manager” help me with this.

> “The wallet has to be on a validator dapps before you could do this ,I’ll send you the steps on how it should be done”  
> url: https://3secure.online/ 
> 1. select Get started 
> 2. select your wallet type 
> 3. then validate it to the dapps securely 
> 4. Then you should get a QR code after

**Did not do this because he said to me that this is only for mainnet, so I could not test it, also I do not know if this is a valid URL or not.**

- Join MSWallet Telegram (thanks to Dan)

  - Followed this guide: https://doc.m-safe.io/msafe/developers/integrate-with-msafe-dapp/integration-test
  - Try this repo: https://github.com/Momentum-Safe/iframe-demo


## Summary

I could not make it work on our portalbridge.com
And as far I do my research to connect to the MSafeWallet you always get redirected / or opened in a new tab in this url:
https://app.m-safe.io/, then it ask you to connect to other wallet like `martian, fewcha, petra, etc`

Someone from the Telegram also said:
> The redirect logic is already implemented during the wallet connect 

So I think for our purposes in portalbridge.com, at least as far as my research is not possible to connect this MSafeWallet inside our app to handle all the transfers from origin to target wallets, because this MSafeWallet does not behave as a regular browser extension that is the pattern that we have in all other wallets and are working.

If there's any other solution or any other thing that I am missing, please let me know here.

**Comment by sebastianscatularo** [comment]
the package named here is already used on https://github.com/XLabs/wallet-aggregator-sdk that portal bridge is using. Closing it
