### ISSUE TITLE
9238 - Cannot read properties of undefined (reading 'name') - ARB -> APTOS

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: ARB
- Source Chain Wallet:0x7c11f47cc61cc72823b524b6932c42185a64c083
- Target Chain: APTOS
- Target Chain Wallet: 0xdfedddbbb4c8638345df17a8f1520834715e60c993ae0dbf0035d3e05ffa2a85
- Asset Type:TOKEN 
- Tx:0x03a76ec501df559e012302a86cc347547ed806d2fc9d6c3344dc519e03c9d3dd
```

### Current Behavior

can't redeem my tokens on Aptos chain:

Transaction error
Cannot read properties of undefined (reading 'name')

### Expected Behavior

REDEEM

### Steps To Reproduce

1) NO VPN
2) BROWSER CHROME
3) WALLET ARB : MM
4) WALLET APTOS PETRA & MARTIAN

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/49b6140e-3403-489f-995c-3d434e343bad)
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/644852e5-698c-49a5-b4f1-7b9ec5539470)

**Comment by drisAloma** [comment]
I think it must have been a local issue on the user's end, I was to redeem it to the user's address just now. We can close the ticket.

**Comment by sebastianscatularo** [comment]
oh cool!, We were working on trying to reproduce it, let's close it then. thank you @drisAloma 
cc: @yuli-ferna
