### ISSUE TITLE
[support] (Keplr + Ledger) Ticket #9269 OSMO -> BSC and #9360 OSMO -> SOL and #9542 OSMO -> AVAX

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: OSMO
- Source Chain Wallet:
- Target Chain: BSC
- Target Chain Wallet:
- Asset Type: BNB Token
- Tx: 
546734F633BF23C57B1ECDD1EFA8824CD02EBC8D215419366FCAF32D11175BF1
09D13B63BFC772A0F52FF9FD149E237ABF77FBE98152A4B9A4AAC7C3199F9F78

User trying to send back the WBNB token to BSC but TX cannot complete
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/c1a0f059-9dbc-4067-ad98-1f8544ee265b)
https://www.mintscan.io/osmosis/transactions/546734F633BF23C57B1ECDD1EFA8824CD02EBC8D215419366FCAF32D11175BF1
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/e4da3718-b689-4e21-bb66-7e646bdf8854)
https://www.mintscan.io/osmosis/transactions/09D13B63BFC772A0F52FF9FD149E237ABF77FBE98152A4B9A4AAC7C3199F9F78

The UI indicates that it needs a second transaction on the target chain and it never comes... 

### Expected Behavior

OSMO -> any chain should have a 2nd TX to appear to complete the TXs

### Steps To Reproduce

1. https://www.portalbridge.com/cosmos/
2. Connect OSMO wallet Keplr + Ledger to bridge
3. Second transaction on the target chain doesn't come
4. Using the TXIDs to resume TX doesn't work(Bridge transaction not found, check that you have the correct chain and transaction ID)

546734F633BF23C57B1ECDD1EFA8824CD02EBC8D215419366FCAF32D11175BF1
09D13B63BFC772A0F52FF9FD149E237ABF77FBE98152A4B9A4AAC7C3199F9F78

### Anything else?

Keplr + Ledger on Wormhole might be the problem
Tried to ask user to move to a wallet with no Ledger to test 
But the token cannot be moved through Ledger with Keplr neither with Leap, it's stucked 🙃

**Comment by Dahtank** [comment]
- Source Chain: OSMO
- Source Chain Wallet:
- Target Chain: ETH
- Target Chain Wallet:
- Asset Type: BNB Token
- Tx: 
90054229195DBE3640D142FEBB853A938215400C9FBC7CEEA894FBF02FD7692B 
Ticket #9276
User trying to resume TXs but gets error(Bridge transaction not found, check that you have the correct chain and transaction ID)

**Comment by dry2022** [comment]
Hello! Any update for this? :) do you need more informations?

**Comment by Dahtank** [comment]
Ticket #9360 OSMO -> SOL
- Source Chain: OSMO
- Source Chain Wallet: osmo125pgxq7w8hrkqy59kas7stcxzlxwuukjqp7ah0
- Target Chain: SOL
- Target Chain Wallet: 55pPhcCcp8gEKvKWr1JUkAcdwMeemmNhTHmkWNR9sJib
- Asset Type: WSOL
- Tx: AEA07F79951E6E0FCC162A4FC7ACDF292AB1E5DC9DBD40D6E0CAB4E884AC17FE
TX cannot be found on Wormhole Explorer nor Wormholescan

https://www.mintscan.io/osmosis/transactions/AEA07F79951E6E0FCC162A4FC7ACDF292AB1E5DC9DBD40D6E0CAB4E884AC17FE

https://wormhole.com/explorer?txId=AEA07F79951E6E0FCC162A4FC7ACDF292AB1E5DC9DBD40D6E0CAB4E884AC17FE

https://wormholescan.io/#/search-not-found/AEA07F79951E6E0FCC162A4FC7ACDF292AB1E5DC9DBD40D6E0CAB4E884AC17FE

Seems like same problem as the above TX with Keplr+Ledger

**Comment by drisAloma** [comment]
User #9360 was able to get around it by using a hot wallet but user #9269 got the error message in the image when he tried to send the bridged tokens (WBNB) to a hot wallet.

I think this issue might be from Kepler directly.
![image-53](https://github.com/XLabs/portal-bridge-ui/assets/64994788/bd6e6bca-e772-4ca6-8806-47144a14fb7d)

**Comment by drisAloma** [comment]
Hello!
Another user using a HW (Ledger) could not bridge from Osmosis to Solana. The user only got the approval transaction and not the follow up prompt to actually send the token.

**Comment by Dahtank** [comment]
Another user facing problems with Keplr wallet + Ledger
Keplr loads the TX as normal and can be signed on Ledger, but the the portalbridge is stuck on loading, no target wallet TXs

Ticket #9542 OSMO -> AVAX
Source Chain: OSMO
Source Chain Wallet: osmo16nsxy6mwevx2lj8z8jfrphy0x4d9zpc8v9yqyt
Target Chain: AVAX
Target Chain Wallet: 0x98406Ab28310B423C54B021dE0602f9a64941C57
Asset Type: USDC.wh
Tx: BEB12C7B31F44C165C5D0FCC3B575ABD6536B6E72134F009CA901B0163A2DD74

**Comment by sebastianscatularo** [comment]
@M-Picco this was related to the memo, right?

**Comment by drisAloma** [comment]
Hello, another user has similar issue, OSMO -> BNB. 
The transaction shows completed but yet to arrive on the destination chain. It was initiated over 4 hours ago
I tried the resume workflow on cosmos bridge but the transaction couldn't be found.
https://wormholescan.io/#/tx/85dcbe72f498d7710270f4e82d7f2568c185ec66420ad5d0e703d26683e54204

**Comment by sebastianscatularo** [comment]
@drisAloma this could be an issue regarding the IBC relayer, @M-Picco do you know how to check if it is the case?

**Comment by drisAloma** [comment]
Oh, okay noted!

**Comment by dry2022** [comment]
hello @M-Picco @sebastianscatularo do you have an update for us? :) thanks!

**Comment by dry2022** [comment]
@sebastianscatularo @M-Picco hey! any deadline or ETA we can give to the users?

**Comment by M-Picco** [comment]
@dry2022 Hi! Sorry for the delays. I think it should be fixed by now. Could you give it a try?

**Comment by dry2022** [comment]
hello @M-Picco checking with the user right now :)

**Comment by Dahtank** [comment]
Fixed by update on 3rd party libraries not including memos
