### ISSUE TITLE
[support] Ticket #9276 and #9540 OSMO -> ETH

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source Chain: OSMO
Source Chain Wallet:
Target Chain: ETH
Target Chain Wallet:
Asset Type: ETH Token
Tx: 90054229195DBE3640D142FEBB853A938215400C9FBC7CEEA894FBF02FD7692B

https://www.mintscan.io/osmosis/transactions/90054229195DBE3640D142FEBB853A938215400C9FBC7CEEA894FBF02FD7692B
```

### Current Behavior

User trying to resume TXs but gets error(Bridge transaction not found, check that you have the correct chain and transaction ID)

### Expected Behavior

User should be able to resume/redeem TX from https://www.portalbridge.com/cosmos/ Resume TX menu

### Steps To Reproduce

1. https://www.portalbridge.com/cosmos/
2. Resume TX
3. Using the TXIDs to resume TX doesn't work(Bridge transaction not found, check that you have the correct chain and transaction ID)

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/f1fd099f-4d40-4cbd-9b5b-2dc655e25f4f)

**Comment by nik-suri** [comment]
It looks like this user improperly attempted to bridge their `wstETH` back out.

The Osmosis transfer doesn't seem to have the proper wormhole gateway memo payload attached. Since cosmos wallets and UIs such as keplr and leap don't yet support performing gateway transfers natively, users need to use Portal bridge (wormhole connect) to bridge their tokens back out.

cc @M-Picco to confirm this analysis.

**Comment by dry2022** [comment]
Hello! Any update on this?

**Comment by omniwired** [comment]
seems the memo is not being populated

keplr msg:

```
{
  "account_number": "833339",
  "chain_id": "osmosis-1",
  "fee": {
    "gas": "1000000",
    "amount": [
      {
        "amount": "1387018",
        "denom": "ibc/EB7FB9C8B425F289B63703413327C2051030E848CE4EAAEA2E51199D6D39D3EC"
      }
    ]
  },
  "memo": "",
  "msgs": [
    {
      "type": "cosmos-sdk/MsgTransfer",
      "value": {
        "receiver": "wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx",
        "sender": "osmo1rz93546e2sx8g0dap0t66gx70sqk5r2d2kac72",
        "source_channel": "channel-2186",
        "source_port": "transfer",
        "timeout_height": {},
        "timeout_timestamp": "1694609143622000128",
        "token": {
          "amount": "118508800",
          "denom": "ibc/BF75AE1500CB7EC458E91A11731F1B6AC1F1FE1FA937A88564955ED6A83CA2FB"
        }
      }
    }
  ],
  "sequence": "74"
}
```

**Comment by omniwired** [comment]
hola @sebastianscatularo let me know if you need any other information about this.

**Comment by sebastianscatularo** [comment]
Hi @omniwired my apologies for the delay, I'll try to check it tomorrow , we didn't review it yet

**Comment by omniwired** [comment]
feel free to add me in telegram, same username as github 🙇‍♂️🇦🇷

**Comment by omniwired** [comment]
Memo is empty here:

https://github.com/wormhole-foundation/wormhole-connect/blob/f1397fada83e4c182a03d9938691b24338586402/wormhole-connect/src/utils/routes/cosmosGateway.ts#L285

**Comment by omniwired** [comment]
@M-Picco @sebastianscatularo Seba, Martin, algun update sobre este issue?
gracias

**Comment by M-Picco** [comment]
@dry2022 @omniwired @sebastianscatularo Hi! Yes, the memo is not being populated. This looks like an issue on one of the javascript cosmos libraries. I've reached out to the devs in order to request a fix (see this [issue](https://github.com/cosmos/cosmjs/issues/1461))

**Comment by omniwired** [comment]
Merged!

**Comment by omniwired** [comment]
@M-Picco hi, any updates on this issue? thanks

**Comment by omniwired** [comment]
The fix got merged https://github.com/cosmos/cosmjs/pull/1477

**Comment by omniwired** [comment]
hi @dry2022 @M-Picco  @sebastianscatularo seems they merged the required changes.

> @dry2022 @omniwired @sebastianscatularo Hi! Yes, the memo is not being populated. This looks like an issue on one of the javascript cosmos libraries. I've reached out to the devs in order to request a fix (see this [issue](https://github.com/cosmos/cosmjs/issues/1461))

**Comment by omniwired** [comment]
tried with a hot wallet today, this is the tx.
Still not working https://www.mintscan.io/osmosis/tx/0396E9EF40FF04422478BB0149F59F7C910B50F19AA27EAFFC591017F7E64CD5

**Comment by omniwired** [comment]
@M-Picco using a hot-wallet I've got the following
```
{
  "amount": "118508800",
  "denom": "transfer/channel-2186/factory/wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx/5TSQTEhJ5Q6r1YqCmCxTRSPiV2pGx5rZUQf6g2XH4e1b",
  "memo": "{\"gateway_ibc_token_bridge_payload\":{\"gateway_transfer\":{\"chain\":2,\"nonce\":9185,\"recipient\":\"AAAAAAAAAAAAAAAAPv6LvvnLjFy2yWI7iFY5ERqaZoE=\",\"fee\":\"0\"}}}",
  "receiver": "wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx",
  "sender": "osmo1c2t58ydw6ww7ukrm66xu67y2hmz66der30elg8"
}
```

**Comment by Dahtank** [comment]
Another user with the same problem, made multiple TXs and didn't receive and unable to redeem
OSMO -> ETH
Token: USDC
TXID: 2AB03FE81DFFC55CCB6AD66D351E5AF8A58023D415EF0FC7EE470C7EF2AB1B63

**Comment by Dahtank** [comment]
#9276 User was able to fix more than one month ago with the help of the lead developer of the project Nikhil Suri
#9540 Token was refunded to user's wallet
