### ISSUE TITLE
[support] Cannot redeem the token to the target chain（Ticket #9127）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:Terra Classic
- Source Chain Wallet:terra1ekntas3us2alhf4qwkzqj4tzg6v7tcx69h9auw
- Target Chain:Etherium
- Target Chain Wallet:0x1Dc41529bE1Bee188f26c84b67556486F1Dbfe52
- Asset Type:Token
- Tx:https://finder.terra.money/classic/tx/d38f885b5df3150719e1bcdd513f13c504667abe7b21e8266ef90192c857dad5
```

### Current Behavior

Redeem failed

https://etherscan.io/tx/0x5cec0d630eb262b4a0dbe7395e2591533deef8eec2e12b46995496889dfdc6cb

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you try to redeem this tx and see if you are able to reproduce the issue? Could be possible the user entered low-gas amount

**Comment by SamantaCasal** [comment]
@willis20188 Could you get the wallets that the user is using? Just to reproduce the same scenario

**Comment by SamantaCasal** [comment]
FYI: @sebastianscatularo 
It seems that the transaction is already redeemed.
@willis20188 Could you verify with the user?
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/16a5012c-89e3-42dc-a56e-755b715eb496
![Screenshot 2023-10-02 at 1 20 09 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/39715d93-5a23-4c92-a1a5-9f03543dfe57)

**Comment by SamantaCasal** [comment]
hi! I am using the txID( https://finder.terra.money/classic/tx/d38f885b5df3150719e1bcdd513f13c504667abe7b21e8266ef90192c857dad5) that the user provides to test, please take a look into the video to see the full process. 


https://github.com/XLabs/portal-bridge-ui/assets/69044575/eaa64bc9-2d1e-4ea2-a044-bbb16ab0960f

**Comment by dry2022** [comment]
Yeah I see... that's weird https://etherscan.io/tx/0x5cec0d630eb262b4a0dbe7395e2591533deef8eec2e12b46995496889dfdc6cb

That's his fail redeem process
