### ISSUE TITLE
[Update/Replace] Swap CCTP for Connect CCTP version

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#409]
**Task**
- Replace current CCTP with Connect CCTP
- Visual design must be the same as existing USDC bridge page
- ENsure that the title of the page says "USDC Bridge"
- Ensure that the CCTP and Wormhole logos at the footer look the same

**Comment by mliu-xlabs** [comment]
Currently waiting for connect to give us the go ahead

**Comment by mliu-xlabs** [comment]
Meet with Martin to verify

**Comment by mliu-xlabs** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.0.13-beta.2-development

**Comment by mliu-xlabs** [comment]
The expectation for this is for it to be quick

**Comment by sebastianscatularo** [comment]
@mliu-xlabs what do you thing is pending on this to be closed?

**Comment by sebastianscatularo** [comment]
Closing this due to the cctp portal has been updated to use Wormhole Connect version/option.
