### ISSUE TITLE
[support] Ticket #9357 BSC -> ARB

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: BSC
- Source Chain Wallet: 0x3d45deafd7bfbe52d2fb0db402d675ec5de4ad14
- Target Chain: ARB
- Target Chain Wallet: 0xdc00e700b1709a9b7a0032f3c84373c2de00e620
- Asset Type: EQB
- Tx: 0xaef49e2bc291d02cd1e6e2b03f45b5db2ea830e7d9afe42256406dd2420d9180
```

### Current Behavior

cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: no wrapper for this token created yet", method="estimateGas", 

### Expected Behavior

User has already "attest token" and create wrapped token" as instructed but still receive "cannot estimate gas" error message during redeeming

User's target wallet address show all TX involved
https://arbiscan.io/address/0x0b2402144bb366a632d14b83f244d2e0e21bd39c

### Steps To Reproduce

1. https://www.portalbridge.com/#/redeem
2. Select BNB chain as source
3. Connect wallet and enter TXID 0xaef49e2bc291d02cd1e6e2b03f45b5db2ea830e7d9afe42256406dd2420d9180
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/20e85b32-faf8-4a3c-b61c-1af745ec75b8)

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/820eae1c-5a6c-46e7-b3bc-7368f8834acd)

Previously he got the error
"Fail with error 'no wrapper for this token created yet'"

Directed user to register token here and try again to redeem after 20mins but still failed with "cannot estimate gas"
https://www.portalbridge.com/docs/tutorials/how-to-do-token-register#token-registration-process

**Comment by drisAloma** [comment]
Hello,
Any update on this!?

**Comment by willis20188** [comment]
Hi,
Any updates?

**Comment by sebastianscatularo** [comment]
the user needs to attest the token first, what app the user has used to interact with Token Bridge?

`execution reverted: no wrapper for this token created yet`

**Comment by drisAloma** [comment]
Yeah, the user registered the token and created the wrapper
https://arbiscan.io/tx/0x655d7832fd80a28b2fcd36263f85f97fc820ba0d66957787ebd2319abf146fdf
I will ask for the dapp used now

**Comment by drisAloma** [comment]
The user interacted with the code base directly, sent a raw transaction, didn't use any service/app.

**Comment by sebastianscatularo** [comment]
I can review the register tx, but, could be possible that the registration didn't go well for some reason. The user should be able to register the same token for as much time as he/she wants, it is an interesting way to burn tokens

**Comment by drisAloma** [comment]
Ah, okay cool, noted!
I will notify the user now.

**Comment by drisAloma** [comment]
The user has done the token registration again but still getting the same error message.

**Comment by dry2022** [comment]
@sebastianscatularo still same error message, what do you think?

**Comment by sebastianscatularo** [comment]
I'll review and let you know @dry2022

**Comment by dry2022** [comment]
thanks :)

**Comment by dry2022** [comment]
hello another user BASE to ETHEREUM "reason="execution reverted: no wrapper for this token created yet", method="estimateGas", transaction=" 

this is the tx : https://basescan.org/tx/0x24646f3ffbff49475a1250d852f8387153cf23668edb8bd8cec076a559ea6d5b

I can open a different ticket if you want!

**Comment by drisAloma** [comment]
Hello @sebastianscatularo
Is there any update on this that we can pass along to the users?

**Comment by willis20188** [comment]
Hey, @sebastianscatularo 
Any updates?

**Comment by Dahtank** [comment]
User uses his/her own code to bridge tokens around with Wormhole. Unable to assist the user further as he is not using PortalBridge UI
