### ISSUE TITLE
[bug] RPC validation error when trying to redeem a tx

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#421]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When I try to redeem **txHash: 0x5226a1a4f9530fce44f358a3bce895deec1191cd30681d32070cb5b5079985a3** (Send tBtc from Avalanche -> Sui) you can see a toast whit the message 
`" Transaction failed with the following error. Package object does not exist with ID 0xf47329f4344f3bf0f8e436e2f7b485466cff300f12a166563995d3888c296a94"` , and in the console: 
```
Error: Error: RPC Validation Error: The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server.
Cause: r: At path: error.parent_object_id -- Expected a value of type `never`, but received: `"0x63075d5be4af685e1dcca4ccb65a90497f213437f8839bf96aebdcf52bec0650"`
Reponse Received: {
  "error": {
    "code": "dynamicFieldNotFound",
    "parent_object_id": "0x63075d5be4af685e1dcca4ccb65a90497f213437f8839bf96aebdcf52bec0650"
  }
}
    at client.requestWithType (client.ts:110:11)
    at async ci.getDynamicFieldObject (json-rpc-provider.ts:695:5)
```

### Expected Behavior

The user should be able to redeem the tx

### Steps To Reproduce

1. Go to https://testnet.portalbridge.com/305ff71a2e/#/redeem
2. Select Avalanche as the Source chain
3. Connect the wallet (In my case Metamask) 
4. Paste the txID ( 0x5226a1a4f9530fce44f358a3bce895deec1191cd30681d32070cb5b5079985a3) 
5. Click on recover
6. Click on redeem
7. Approve the tx
8. Observe the message on the toast 

### Environment

- OS: macOS Ventura 13.5.2
- Wallet: Metamask
- Browser: Chrome Version 116.0.5845.187 (Official Build) (arm64)

### Anything else?

**Evidence:** 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/f3e7adb7-a9aa-4ef0-966f-01931518ca15)
![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/57311c8b-745a-4b72-b4ea-2ca68d60d98b)

**Comment by SamantaCasal** [comment]
The same error when send tBtc from Base -> SUi
TxID: 0x6103c67df4c9fc919cb9b9c5bb6533d95e97d2812d201bf4dcd0cd96e24f891a
Evidence: 


![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/769bf122-2c36-4a9b-a739-8aeccba07ce5)

**Comment by SamantaCasal** [comment]
Also send tBtc from Eth to SUI.
TxId: 0xaef484c1a8c68cc3008d891cc9ba3a1b7ae56f677708501024a421685ce859fb

**Comment by SamantaCasal** [comment]
Update: 
FYI: @yuli-ferna  @sebastianscatularo 
I was able to redeem the mentioned transactions, however, I left the ticket open with low priority, so you can analyze it when you have a chance. After that,  you can close it. 

ETH-> SUI
TxID: 0xaef484c1a8c68cc3008d891cc9ba3a1b7ae56f677708501024a421685ce859fb

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/0eb29dfd-c3b4-4367-a3fa-9707156ada8e)

BASE -> SUI 
TxID: 0x6103c67df4c9fc919cb9b9c5bb6533d95e97d2812d201bf4dcd0cd96e24f891a

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/7f5a83d4-f4c1-481c-adf4-a0204c7e0a77)

AVALANCHE-> SUI
TxID: 0x5226a1a4f9530fce44f358a3bce895deec1191cd30681d32070cb5b5079985a3

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/6e25197c-8e6a-41cb-8fce-dbf16879334a)

**Comment by mliu-xlabs** [comment]
deprecating
