### ISSUE TITLE
[bug] <In the modal for selecting a token, the loading is shown after clearing the search>

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#424]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When you enter a keyword to search for a token and clear it before displaying the result, the modal continues as looking for a result, even when you update the page or close the modal and open it again you can still see the the spinner with the loading message. 

### Expected Behavior

The user should be able to:
Looking for a token through a token address, name or just selecting one of the list. 
When you enter a name or address and clear it before you get the result, the search should end and show the list of tokens. 

### Steps To Reproduce

**Prerequisite:** Have more than two tokens added to the list. 
2. 1. Go to https://www.portalbridge.com/#/transfer
3. Select a source chain that meets the requirements mentioned above.
4. Connect the corresponding wallet
5. Click on SELEC A TOKEN
6. Enter whatever word in the search input
7. Clear it
8. Observe the modal

### Environment

- OS: macOS Ventura 13.5.2
- Wallet: Metamask
- Browser: Chrome Version 116.0.5845.187 (Official Build) (arm64)

### Anything else?

**Evidence**

https://github.com/XLabs/portal-bridge-ui/assets/69044575/4f80fea6-6312-4929-bc3b-c7001f4f9239

**Comment by mliu-xlabs** [comment]
deprecating
