### ISSUE TITLE
[bug] <Token redeem fails in transaction to SEI>

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#427]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The redeem fails and a message is displayed that says: 
`"Error when broadcasting tx A2E631472C4BA7BB46D0909D6A65799F294FFC3E7BFAC0937B86E49AF3D868B1 at height 26659843. Code: 5; Raw log: failed to execute message; message index: 0: Generic error: VaaAlreadyExecuted : execute wasm contract failed"`

AND **when trying to redeem manually** from https://preview.portalbridge.com/2198fe7d06/#/redeem the message "This VAA was not generated from Token Bridge, or the type is not supported yet. If you have any questions or believe this is a mistake, please open a support ticket on Discord."

### Expected Behavior

The users should be able to redeem their token 

### Steps To Reproduce

1. Go to https://preview.portalbridge.com/2198fe7d06/#/transfer
2. Select SOLANA as the source chain
3. Select Sei as the target chain
4. Following the instructions up to step 4
5. In Step 4, click on REDEEM 
6. Observe the message on the toast 

### Environment

- OS: macOS Ventura 13.5.2
- Wallet: Phantom/Fin
- Browser: Chrome

### Anything else?

Evidence: 
TXID
https://solscan.io/tx/2zTxzYYc1rHrtN8Czi1oBsDejHREKhxTX5xdZUrekq9CkBGRFXUh4UWveA2Vuay2tcpB8t4LFTvEQxhveAGrXUwX
TXID: https://solscan.io/tx/4SLPiJKrLJYE272gEW1U3DoJQMNhsZ1uQdJDm7eymjPCUu9Q4Gjs7fnanbr4e2yFTpePi5UjSE6bzzymRkehotFV

https://github.com/XLabs/portal-bridge-ui/assets/69044575/37017549-81cb-4306-ba6a-58ac7b0bbd7a

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/7cfa6e6a-d0a9-4fdb-96ad-41d3b2c16140)

**Comment by SamantaCasal** [comment]
The same issue happens with BNB -> SEI 
Tx: https://bscscan.com/tx/0x434b39fbb11a72ed74340d80aea416ae318d2a0fd23f5e86a4af2a88b12f4d8b
Error message: 

`Error when broadcasting tx F4A7B25560633C0317A07450A1FF70784A4C566E05AD882B3AFEEF0BF4AAB3EC at height 26668781. Code: 5; Raw log: failed to execute message; message index: 0: dispatch: submessages: Generic error: VaaAlreadyExecuted: execute wasm contract failed`

**Comment by SamantaCasal** [comment]
The Same issue happens when sending Sei from    BASE to SEI 
TxID: https://basescan.org/tx/0xd46dbdb84ae3ef2937c6aa5b5dcf3804a7b84339e5c198f3088fc4a8a17aac9d
`Error when broadcasting tx B85FE134EAA5A7E1949CF419385D320BA08EC99DDE97B11356EC779BDC9962A0 at height 26767472. Code: 5; Raw log: failed to execute message; message index: 0: alloc::vec::Vec<u8> not found: execute wasm contract failed`

**Comment by SamantaCasal** [comment]
The same issue happens when sending Sei From ARBITRUM to SEI 
TxID: 0x680e92f3bdc70c7ed66a3900cdd41b68875ef9c37b51b80ddce477b4ffeec96f
`Error when broadcasting tx 0135A83236A6DF68BCA47BF8AC6293C508F1500049C3837EEBAEBF15543FF5ED at height 26771293. Code: 5; Raw log: failed to execute message; message index: 0: Generic error: VaaAlreadyExecuted: execute wasm contract failed`

**Comment by SamantaCasal** [comment]
The Same issue happens when sending Avax From Avalanche to SEI
TxID: https://snowtrace.io/tx/0x3468bc24495a7e049ad2f689065bdd4698acad2a845df26158066bdff2a5b46f
`Error when broadcasting tx B12CFD391E0633C358C0C3CA7E04DFC920F5A1CB5B78B0B67583D69D74A8571D at height 26772579. Code: 5; Raw log: failed to execute message; message index: 0: dispatch: submessages: Generic error: VaaAlreadyExecuted: execute wasm contract failed`

**Comment by SamantaCasal** [comment]
The Same issue happens when sending Sei From ETHEREUM to SEI
TxID: https://etherscan.io/tx/0x666f2e13a39d556f2b2cd3bfec22c6a856793ea481d703fd3be6d79663d0bcf4
Error when broadcasting tx B12CFD391E0633C358C0C3CA7E04DFC920F5A1CB5B78B0B67583D69D74A8571D at height 26772579. Code: 5; Raw log: failed to execute message; message index: 0: dispatch: submessages: Generic error: VaaAlreadyExecuted: execute wasm contract failed

**Comment by M-Picco** [comment]
If you are getting a `VaaAlreadyExecuted` it means that the transfer was already completed. If I'm not mistaken there are relayers set in place to listen for transfers to Sei. It's probable that these redeemed the transfers before you could do it manually. The portal bridge may not be checking for this before trying to start the claim.

**Comment by sebastianscatularo** [comment]
But, that does mean, there is a pulling relayer, that is watching on token bridge vaas to relay them for free, that sounds odd to me, without a gateway contract to grab some fee for the op?

**Comment by sebastianscatularo** [comment]
native Sei is end through the SEI_TRANSLATOR contract, that seems to be is running some kind of relayer logic, I'll double check

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you re-test it



https://github.com/XLabs/portal-bridge-ui/assets/1277510/1f77fa2f-48f9-41b5-bdaf-b6ec6612ca0d

**Comment by SamantaCasal** [comment]
FYI: 
❗ The transaction is carried out OK, But the error message is still displaying in the Portal Bridge 
Evidence: 
Send Sol From SOLANA -> SEI ( [SOLSCAN](https://solscan.io/tx/4B2n9xMPjfh4wNzx5RRsy96R3rdzhdXNMN3jQa2cHQvLPtXnU23274tKCLQSgYzfzeGf5GE5QR32BTg9u4XWkFqe) /[SEISCAN](https://www.seiscan.app/pacific-1/txs/BCDDAC09286EE7644E52634502D62FB87679F263E3CBEFF249816884DD0B903F))

https://github.com/XLabs/portal-bridge-ui/assets/69044575/362970c1-181a-4367-9ad1-0a2e6ac90bf3

**Comment by SamantaCasal** [comment]
With  Sei as the Target chain:
FYI: @sebastianscatularo @mliu-xlabs  I will approve this ticket because the transactions that fail, are already recorded in other tickets. 

**Not working:**

- Arbitrum -> Sei (Bug in token register)  [TICKET HERE](https://github.com/orgs/XLabs/projects/2/views/6?filterQuery=-status%3Adone++-is%3Apr+-status%3A%22On+Hold%22+sei&pane=issue&itemId=39095639)
- Base -> Sei (Bug in token register ). [TICKET HERE](https://github.com/orgs/XLabs/projects/2/views/6?filterQuery=-status%3Adone++-is%3Apr+-status%3A%22On+Hold%22+sei&pane=issue&itemId=39095639)
- Aptos -> Sei ( In step 3 show "Transfer with payload is unsupported on Aptos" ) 

**Working:**

- BNB -> Sei [BSCSCAN](https://bscscan.com/tx/0xa3daca037d9a9dfecf74a54587593e8716302e81234a99e4e07678ff7aa34d27) / [SEISCAN](https://www.seiscan.app/pacific-1/txs/3333BDC0EE895DF7CDCF296EE6B307677907539C1753DF3A298D87CA7DEAB7FE)

- Send Sei From AVALANCHE -> Sei [SNOWTRACE](https://snowtrace.io/tx/0x29ea62e0314541c030874aba3e8f1ae47655bd76b70354eecca3c2bcbd698534)/ [SEISCAN](https://www.seiscan.app/pacific-1/txs/CB848CD641F431585A0CA02CE52284B9DEB467F1B7BA784C0ED67E1DEBE25E81)

- Send USDC From Eth -> Sei  [ETHERSCAN](https://etherscan.io/tx/0xc2e899f2a387118c1bc07362ea80553b693afe32f02e6ac2da9260e0866b0666)/ [SEISCAN](https://www.seiscan.app/pacific-1/txs/29E0B5859D2644A70E376A8CA3700CE819A3B7D87838A0711BCE90A8AA55414F)

- Send Sol from SOLANA -> Sei [SOLSCAN](https://solscan.io/tx/37LRC7qNYYrpuAk4D3jmwxhxFsTGKTLUMroTmdwxYExvTk1aH6XRt5otQGduaijsFgQSF4us8RD1kigY31UV3tNj)/ [SEISCAN](https://www.seiscan.app/pacific-1/txs/2BC73E6133D6DC239019ECABA8CB731D6888FA511AE8E8CB0048912C6A59C76D)
