### ISSUE TITLE
[bug] <Send tokens fails for tx from SUI to SEI>

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#428]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

In step 3 it shows a toast with the message **"senderAddress is required for transfer with payload"** and the **transaction cannot be carried out **
In the console you can see:
```
useHandleTransfer.tsx:186 Error: senderAddress is required for transfer with payload
     at transfer.js:580:23
     at Generator.next (<anonymous>)
     at o (transfer.js:4:58)
Wf@useHandleTransfer.tsx:186
(anonymous) @ useHandleTransfer.tsx:1018
await in (anonymous) (async)
(anonymous) @useHandleTransfer.tsx:1305
(anonymous) @Send.tsx:49
Ge @ react-dom.production.min.js:52
Ze@react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Po@react-dom.production.min.js:100
Eo @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Oe @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Oo @ react-dom.production.min.js:105
Xt@react-dom.production.min.js:75
Qt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ks@react-dom.production.min.js:122
From @react-dom.production.min.js:292
qt@react-dom.production.min.js:73
```

### Expected Behavior

The users should be able to send SUI from SUI to SEI.

### Steps To Reproduce

1. Go to https://preview.portalbridge.com/2198fe7d06/#/transfer
2. Select SUI as the source chain
3. Select SEI as the target chain
4. Following the instruction up to step 3
5. On step 3 click on TRANSFER
6. Observe the message on the toast

### Environment

- OS: macOS 13.5.2
- Wallet: SUI wallet/Fin, Martian/Fin and Martian/Leap
- Browser: Chrome

### Anything else?

Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/4406d01c-6c4c-42ca-aeb8-4e4f859d56db

**Comment by yuli-ferna** [comment]
I think this issue is related with https://github.com/XLabs/portal-bridge-ui/issues/176

**Comment by SamantaCasal** [comment]
@yuli-ferna  
Yes, it seems the same issue, but testing from https://preview.portalbridge.com/2198fe7d06/#/transfer  I can't transfer SUI from SUI to SEI, please check the video.

**Comment by SamantaCasal** [comment]
QA OK! 


https://github.com/XLabs/portal-bridge-ui/assets/69044575/fcacd709-be47-4cf8-8609-bdef460d6f10
