### ISSUE TITLE
[support] Ticket #9402 Target Asset Unavailable, is the token registered?

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: ETH
- Source Chain Wallet: 0x51c38627d4bd4034f3FA9e5D2D96E0f5f76A478E
- Target Chain: BASE
- Target Chain Wallet: 0x51c38627d4bd4034f3FA9e5D2D96E0f5f76A478E
- Asset Type: AGOV
- Tx:
etherscan : https://etherscan.io/tx/0xc12b66b7ef8037f941cec40168cc17b13b8c3571450ae3114b37b056f9349d07
basescan : https://basescan.org/tx/0x0347c4a78eac8cf8d615ec7a6cc00b8b6a17fccea1e603fe7dc97d202e3fb65e
```

### Current Behavior

User unable to send tokens after Attest
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/fe43b41a-1fad-4939-b917-9d0858f4dce0)
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/67a2eaef-e95a-46ec-8a98-df11a40a4c12)

### Expected Behavior

User should be able to send the tokens (AGOV) after registration at https://www.portalbridge.com/#/register

### Steps To Reproduce

1. https://www.portalbridge.com/#/transfer
2. Select ETH as Source Chain and connect wallet
3. Select Base as Target Chain and connect wallet
4. Enter token address AGOV(Erc20) : 0xd1420AF453Fd7bf940573431D416cAcE7fF8280c
5. Unable to send tokens with error (Target Asset Unavailable, is the token registered?)

**Comment by yuli-ferna** [comment]
@Dahtank We tried to reproduce the error following the above steps, but we can go to step 3 without the error message. Could we ask the user to try again?

**Comment by Dahtank** [comment]
I will ask the user to try again, thanks for testing!

**Comment by Dahtank** [comment]
Closed as user did not respond after a long time
