### ISSUE TITLE
[support] Cannot be recovered （Ticket #9412）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:sui
- Source Chain Wallet:0xc8f55f6b0762c9fc0968ff424d8ea2c62b792b740dc1d94cacc99f6f7ea8268a
- Target Chain:polygon
- Target Chain Wallet:0xE976dC0157F83c59a1E591CFf88Ce68EB87BeADe
- Asset Type:Token
- Tx:https://suiscan.xyz/mainnet/tx/F5xptBVvw2dFEyJa6GdVKp4dLaYKgvksvNFzuCEiZPKg
```

### Current Behavior

Cannot be recovered
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/768ca184-aaf6-49ce-b1a9-ca2ca8f2fce6)

### Steps To Reproduce

redeem workflow

**Comment by sebastianscatularo** [comment]
reviewing the VAA associated with this op ([vaa.dev](https://vaa.dev/#/parse/AQAAAAMNAHyNM5kYhJbHYqJP1D%2B5M%2BnoxafKyeO5yZbVPBe8HGP5bYJGv2iMUozhOQ6b%2FSnuVOlxyBxoFI2RkNYHG5ZL4SEAAqrkhTtEb1PoMl8sHoqVfyR5hK%2FzcFIR5Ih7Itl9dWK6cfZ9xcjQj%2B9lk3Zxp%2FyduK8M0M769J4S0A%2BMAA4g9hMBA10mG0iEWrKrgdUgnC8X2V8xn2W8hWJCr6KEDfNZxg9Abjefnsxyqg%2BjQZq3GwM0VQ%2F45SFFBwy2N%2BR2WeieGq0ABGH2xsjbz2lk51vb%2BCH5DYWDFIdCahL7Ua61Ov88h7QcABZrf2FdA6nq%2B8pR2XlYim7EtgDoTeOaJHn1LPn6LwUABiZiJS5OjoydTgosqnr4VkdKNi0yFXAI8uvxo101TMUqP4Fc%2BmFQdGspGmtBvGjNDjyreu2bSJJIV3HASy89AugBB1IuAhjCpuvJZ0d4Ep97LrL6q1LeJju5f8kJtNnjLDDlOduy3ScoJCwq2N5TJr0sCqPUHABQtMwoO41dTI4NCBEAClMncz8ieecNDhkYXlZ7boQ1%2Fc0YugKNI1u9Yj%2Ba%2BIlBeJXSu60%2FccZY5ySOU6bW7B4AdSoFCilGYIChWqeVFPoADc1CCuxjda95t1Z6g1y%2BDlkKhDlowDGaE7FusBdjPPSGGWltSfdrYRrWWOrPfmwe3w8F5nU77dTRnxMgM1etW0MADu4GjenpvDiZMCoTWtpSrPJjzhBjSv2OUM0cYoIV2hGMU8y31kfrJleo1h%2FuT6%2FBBGcG%2BHJl2Z%2BnylmiwiuhvyoBDxBUFMQuXtCtits9591LtaairCjqUj1ijLaW4YsJzow3PxYt7WXh%2Bow6ZN70gFBrr1wL8FtcDKSDKQN9VZJvnuYAEACfmR7Q%2F0wHY%2FTakod8UOfOeNgvxLOCZsO4trcQuVv6fk51Ik29LUvERlMMye8HRjcdWOUQvD0U9rJbeobgPXMBER1M%2F5u%2FPVwVznWvgs5fgIlDTl1uAR%2FnM7UCJNggqskXBE3f08ydZUqZAxx5YeurTvut8%2Bm7nVPMSPJBEllpw9YAEs6Lly6ONI9fztSq9MPCo7XvIVgiQq3m1T5WKxy3akFSCcatSS%2ByqPomKVJdQvx96%2Fl1NVYQM5rWsmsFL%2FoWpSUAZPRmrwAAAAAAFd0coL0LnkSf9VJZ5bz34Pwbi3q0mqutIYaBzM57ICvWAAAAAAAADugAAAAAIgAAyPVfawdiyfwJaP9CTY6ixit5K3QNwdlMrMmfb36oJooCAC8AAAAAAAAAAA7iACIAAMj1X2sHYsn8CWj%2FQk2OosYreSt0DcHZTKzJn29%2BqCaKAA%3D%3D%22%2C)) seems to be not compatible with portal bridge, could you ask the user for the App that they have used to bridge it?

**Comment by sebastianscatularo** [comment]
Y got the VAA from [here](https://wormholescan.io/#/tx/F5xptBVvw2dFEyJa6GdVKp4dLaYKgvksvNFzuCEiZPKg)

**Comment by willis20188** [comment]
> reviewing the VAA associated with this op ([vaa.dev](https://vaa.dev/#/parse/AQAAAAMNAHyNM5kYhJbHYqJP1D%2B5M%2BnoxafKyeO5yZbVPBe8HGP5bYJGv2iMUozhOQ6b%2FSnuVOlxyBxoFI2RkNYHG5ZL4SEAAqrkhTtEb1PoMl8sHoqVfyR5hK%2FzcFIR5Ih7Itl9dWK6cfZ9xcjQj%2B9lk3Zxp%2FyduK8M0M769J4S0A%2BMAA4g9hMBA10mG0iEWrKrgdUgnC8X2V8xn2W8hWJCr6KEDfNZxg9Abjefnsxyqg%2BjQZq3GwM0VQ%2F45SFFBwy2N%2BR2WeieGq0ABGH2xsjbz2lk51vb%2BCH5DYWDFIdCahL7Ua61Ov88h7QcABZrf2FdA6nq%2B8pR2XlYim7EtgDoTeOaJHn1LPn6LwUABiZiJS5OjoydTgosqnr4VkdKNi0yFXAI8uvxo101TMUqP4Fc%2BmFQdGspGmtBvGjNDjyreu2bSJJIV3HASy89AugBB1IuAhjCpuvJZ0d4Ep97LrL6q1LeJju5f8kJtNnjLDDlOduy3ScoJCwq2N5TJr0sCqPUHABQtMwoO41dTI4NCBEAClMncz8ieecNDhkYXlZ7boQ1%2Fc0YugKNI1u9Yj%2Ba%2BIlBeJXSu60%2FccZY5ySOU6bW7B4AdSoFCilGYIChWqeVFPoADc1CCuxjda95t1Z6g1y%2BDlkKhDlowDGaE7FusBdjPPSGGWltSfdrYRrWWOrPfmwe3w8F5nU77dTRnxMgM1etW0MADu4GjenpvDiZMCoTWtpSrPJjzhBjSv2OUM0cYoIV2hGMU8y31kfrJleo1h%2FuT6%2FBBGcG%2BHJl2Z%2BnylmiwiuhvyoBDxBUFMQuXtCtits9591LtaairCjqUj1ijLaW4YsJzow3PxYt7WXh%2Bow6ZN70gFBrr1wL8FtcDKSDKQN9VZJvnuYAEACfmR7Q%2F0wHY%2FTakod8UOfOeNgvxLOCZsO4trcQuVv6fk51Ik29LUvERlMMye8HRjcdWOUQvD0U9rJbeobgPXMBER1M%2F5u%2FPVwVznWvgs5fgIlDTl1uAR%2FnM7UCJNggqskXBE3f08ydZUqZAxx5YeurTvut8%2Bm7nVPMSPJBEllpw9YAEs6Lly6ONI9fztSq9MPCo7XvIVgiQq3m1T5WKxy3akFSCcatSS%2ByqPomKVJdQvx96%2Fl1NVYQM5rWsmsFL%2FoWpSUAZPRmrwAAAAAAFd0coL0LnkSf9VJZ5bz34Pwbi3q0mqutIYaBzM57ICvWAAAAAAAADugAAAAAIgAAyPVfawdiyfwJaP9CTY6ixit5K3QNwdlMrMmfb36oJooCAC8AAAAAAAAAAA7iACIAAMj1X2sHYsn8CWj%2FQk2OosYreSt0DcHZTKzJn29%2BqCaKAA%3D%3D%22%2C)) seems to be not compatible with portal bridge, could you ask the user for the App that they have used to bridge it?

Navi

**Comment by sebastianscatularo** [comment]
I see, if this is the app, https://app.naviprotocol.io/bridge seems they are using Wormhole Connect, I suggest also contacting Wormhole Connect team at Slack or at https://github.com/wormhole-foundation/wormhole-connect/issues

I'll see if I can get some understanding of this in the meantime.

**Comment by willis20188** [comment]
> I see, if this is the app, https://app.naviprotocol.io/bridge seems they are using Wormhole Connect, I suggest also contacting Wormhole Connect team at Slack or at https://github.com/wormhole-foundation/wormhole-connect/issues
> 
> I'll see if I can get some understanding of this in the meantime.

Thank you, I've posted in Slack but haven't received a reply yet.

**Comment by anondev2323** [comment]
The Connect team investigated this transaction.  There seems to be an error, because this does not interact with the Token Bridge or Token Bridge Relayer at all.  So it could not have been made using Connect

**Comment by Dahtank** [comment]
Wormhole Connect was used on the site
https://app.naviprotocol.io/bridge
