### ISSUE TITLE
[bug] <Token registration fails for BASE -> SEI >

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/portal-bridge-ui#443]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When try to create the token it shows the following message: 
`Error when broadcasting tx 58E6719810F29BD364CD95FB391FF503246984AF410B797C857E5366C808E77A at height 27253904. Code: 5; Raw log: failed to execute message; message index: 0: alloc::vec::Vec<u8> not found: execute wasm contract failed`

### Expected Behavior

The user should be able to register a token from BASE to SEI 

### Steps To Reproduce

1. Go to https://preview.portalbridge.com/2198fe7d06/#/register
2. Select BASE as  the source chain
3. Select SEI as the target chain
4. Connect the wallet
5. Select a token that is not registered on SEI 
6. With the wallet connected, click on Register Now
7. Click on Attest
8. Click on Create
9. Observe the error message in the toast

### Environment

- OS: macOS Ventura 13.5.2 
- Wallet: Metamask/Fin
- Browser: Chrome Version 117.0.5938.88 (Official Build) (arm64)

### Anything else?

Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/0f43d5a8-cde4-4d57-a48b-aad1cf14e1b5

**Comment by sebastianscatularo** [comment]
Base was not registered at Sei network, we are working to register Base on Sei

**Comment by SamantaCasal** [comment]
The token is registered successfully, but we see the message on the PTB screen: "Transaction with ID B041E9199957FC99A95E8A6E14D5EF814055E65A7A12D0084B1B035B3B44CE03 was submitted but was not yet found on the chain. You might want to check later. There was a wait of 60 seconds."
Maybe we should add that it shows a loading until the transaction is carried out instead of that message.


https://github.com/XLabs/portal-bridge-ui/assets/69044575/1a43aa53-db17-4063-8372-816a3f549ab2
