### ISSUE TITLE
[support] Redeem error: Not enough valid signature to repair<ticket-9475>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Ethereum
- Source Chain Wallet: Metamask
- Target Chain: BNB
- Target Chain Wallet: Metamask 
- Asset Type: Token
- Tx: https://etherscan.io/tx/0xa3922966b4cc076d30560bd079b5de9e84944a75d4f9cb45a98d135233b889a0
```

### Current Behavior

Throws the error "There are not enough valid signatures to repair" after pasting in the transaction hash

![chainswap](https://github.com/XLabs/portal-bridge-ui/assets/64994788/d16a4cdc-a259-4f2f-8669-bbca089763e0)

### Expected Behavior

Show recover button

### Steps To Reproduce

- Go to https://www.portalbridge.com/#/redeem
- Choose ethereum as source chain
- Paste in the transaction hash

### Anything else?

The user said they used chainswap but their website shows wormhole is not live on the protocol
https://exchange.chainswap.com/#/dashboard

**Comment by sebastianscatularo** [comment]
@drisAloma I've asked our infra team to re-sign/re-observe this message, I hope it gets done soon :)

**Comment by drisAloma** [comment]
Cool, thank you!🙏🏽

**Comment by sebastianscatularo** [comment]
@drisAloma here is the resigned vaa 

|tx|vaa|
|-|:-|
|0xa3922966b4cc076d30560bd079b5de9e84944a75d4f9cb45a98d135233b889a0|01000000030d00c21a4859c2ef35a5e3c2423cae678992c95aafb51239f66a0a2a9952cb5868e77f0019b12307dea109aca5d6b09548353f676ce9e1a6898850c7c2ddd191332e0103305c1ee48cff82ee72fef24812909da6e742e37b335fadebe4e493fe2823f8511860c12679a339eca912b45b9b6336a45697c0b2e677051c56c2beafbbe0c498010445ebc829d1ad182fac7eb83bf24004ecf758d42fa12b9fbc0d41211d7f46b9dd2ea8dd63487d4f79b0d725b220b1b93cb824b307160c4ee341560da9ea2b05f90006791120d42560179749bcc004ee546a9ec330ee749ec1470e5a37adacc1ee016420d3179b1e8042cc8075d4808e98373451ffa28dbab3de95254874024cde137c01079a2f0d2c9fe6319f9b88f1037c584e92861dddce3653825f80aa48cd4f1959290ce33e264876134aac4c55926d413d88faad3f0b17bf2660fb26beb80f35e25d010965756198e55e541472e3facaf3bb0d11b1d9bc211c34ea74d8cdb29578531e5406aacc64d1e135950c4a2d484db4fa698a04fd5e89d66127972c033211dbcd94010aec1d555b5ee14939f5192013f3a3ec7b1a1861c59ecda4c51ba7b2691a7d36884c3941c925d99e39dd73d7fea1c4ae0caae6fa8bcaec0b7877928a403fce7d64000c3555e2d27084ea0750b1eabd5afedaf3fcc2e16957c432ee48207c4e983e0be5220be52dfac0f668ebf799689841e7f6f06c84d21638819524ce027ba0024c59000ed81e05bba4660da9585fcff1ba85c3b01a93e53b69ffd89466d6f2dacf8e5e971558f8af993391f9155c4a9e462fdd4f619b5a8d20e8d97294435f9055328d5b000ff0d97ed53df9c33e87b3023e08d5676cd7e3c9865460a01a1d9219cfaa2872346b763159fafd060870cc0a7ceff75b2e87d83dbcf7f8813f6251cd15044ce4a2011028c9de6fb2eeeea9945266f0b074bc7d5960975ea935bb918d706f4ea1979611011271ad68c03777cf16350f0cfc95f016457bea16a18096517bbab55fdad87b011147eb0b8034aad860d8f44bb44c787b24ad861d64523310493959275cbae2dbd236f356b4eca31ae89d4951c600d19e9b4e61351c1dfffb52304a0e0ced7c4d5400124d5d701042d37040f2217913aa0dc832b0abdd211567c4641eebaaa3a296052866b511fa6c06f151a99c668940c8a94630441f25ff1ab774327213ac83800ccc006306232fde57000000020000000000000000000000003ee18b2214aff97000d974cf647e7c347e8fa585000000000001344f0f01000000000000000000000000000000000000000000000000000000000b26acec000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0004000000000000000000000000de9d341f0f44c4c8c02000a3b3481ef6370f1a2e00040000000000000000000000000000000000000000000000000000000000000000|

**Comment by drisAloma** [comment]
Thank you!
I tried redeeming for the user but it showed "tokens have been redeemed" immediately I connected by BNB wallet and the tokens are not in the user designated wallet address.

![IMG_20230929_222208](https://github.com/XLabs/portal-bridge-ui/assets/64994788/5d735b72-8e00-407f-b662-d516d7d153f7)

**Comment by drisAloma** [comment]
Is it an error on the UI or it is still being processed somehow? @sebastianscatularo

**Comment by Dahtank** [comment]
I get the same message "tokens have been redeemed" when trying to redeem with the Signed VAA provided, using the SignedVAABytes converted from BASE64 to HEXcode yields the same result..

**Comment by sebastianscatularo** [comment]
🤔 curious, no, it should not be an error on the UI, not sure what could be happening here

**Comment by Dahtank** [comment]
Should we reopen this support issue or log a new one? The TX is still not redeemed based on a check on his target wallet @sebastianscatularo @drisAloma

**Comment by drisAloma** [comment]
Hello @sebastianscatularo @Dahtank 
Apparently the transaction had already been redeemed over a year ago.
https://bscscan.com/tx/0x4458cdc0c4b479390892c5ebb224f50415f473f69ab2cf4ca7f40dd54b080cd1
