### ISSUE TITLE
[support] Can't Resume（Ticket #9522）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:OSMO
- Source Chain Wallet:osmo1a29tx88hnyt9wext8hnnl2ewpsf4k4s90u45cs
- Target Chain:SUI
- Target Chain Wallet:0xbc8daddde9985bc8489045b2e26ca36678bcd26face5d9687eab2c218006d61e
- Asset Type:SUI
- Tx:https://www.mintscan.io/osmosis/tx/D2CAFCB3FF449DDA933D85976C09FA44598C589A16B49CD710FBFEF41FBA3DFC
```

### Current Behavior

Can't Resume
Error message：Bridge transaction not found, check that you have the correct chain and transaction ID

### Expected Behavior

Resume

### Steps To Reproduce

https://www.portalbridge.com/cosmos/
Open Menu, Resume TX
Select OSMO and Paste the TX D2CAFCB3FF449DDA933D85976C09FA44598C589A16B49CD710FBFEF41FBA3DFC
Bridge transaction not found, check that you have the correct chain and transaction ID

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/353f9a7e-2d3a-4b77-8ec1-a1881b2ecf3f)

**Comment by dry2022** [comment]
its always the same user who has problem from Osmosis, he opened like 5-6 ticket since 2 weeks, all his bridge tx are "not found"

**Comment by drisAloma** [comment]
Hello, this particular transaction got reverted but the user made another series of transactions, all of which got acknowledged on IBC but one is yet to reflect on the target chain (APTOS)
Tx : https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/248

**Comment by sebastianscatularo** [comment]
I have been asking around, and from my understanding, the issue involves multiple components, I didn't save time to dig deeper into this.
