### ISSUE TITLE
[feat] improve error reporting for evm contract allowance

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#461]
### Scenario

```markdown
As a user who has selected a low allowance amount, I want to see a warning regarding my selection and the size of the transfer that I'm trying to execute.
```

### Acceptance Criteria

- [ ] A can see a warning and take action to adjust allowance if it is needed

### Anything else?

Current error:

![image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/4f16f627-d331-4f44-b18a-08fc9610ca1d)

**Comment by mliu-xlabs** [comment]
deprecating
