### ISSUE TITLE
CLAIMED 9522 - "no Balance detected" OSMO

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Can't load balance token from APT to OSMO via https://www.portalbridge.com/cosmos/
```

### Current Behavior

user (was) not able to see his balance

UPDATE NOW : user don't see the balance he has but can transfer.

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/1b276306-6b06-42a6-b516-3cee15e71ccf)

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/093734e5-efe6-4232-8157-a0d874798a73)

### Steps To Reproduce

via https://www.portalbridge.com/cosmos/

not able to bridge from APT to OSMO (no balance detected) and also OSMO APT.

tried : 

tried connecting both wallets and toggling between the two networks
created a new wallet, but the balance still doesn't show (on APTOS)

**Comment by sebastianscatularo** [comment]
ack, checking

**Comment by sebastianscatularo** [comment]
this issue should be fixed now

<img width="1090" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/b35695b0-3201-4a2f-9b92-98603c505fca">
