### ISSUE TITLE
can't redeem - ticket 9591

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source chain : SOLANA
Wallet Source chain : C1uUtRttwDFpiQ8QH1Kq8gbwvqbc9Nb1BTnCviKKRRZK
Target chain : ETHEREUM
Wallet target chain : 
option 1) 0xEEd5d7e275a432b11E418f24AD1B8c2798c28853
option 2) 0x12d48A599E2B5d8ebE33d356A31814Ed159Fa7c2
Tx: 97LAucaULSm9iGRhU1A29hrfAnxk8Mg31uxASjFyKB8DPR4MfXQdDvKMm27HA6bDUSpvQCtDfKHGVsULZiJ2GRV 

ITS A 2 YEARS OLD TX, so on the portal redeem interface its said : "There are not enough valid signatures to repair."
```

### Current Behavior

can't redeem

### Expected Behavior

trying to redeem on ethereum mainnet

**Comment by drisAloma** [comment]
Hello!
Is there any update on this?

**Comment by sleepycorgi1** [comment]
Please close this issue
