### ISSUE TITLE
[support] wweth_v1 asset not transferable (Ticket #9622）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#466]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:SOL
- Source Chain Wallet:HXXGdxvKcvxkfk9WBv9HSsG2PKm9xPBpC21fyqxuqi49
- Target Chain:ETH
- Target Chain Wallet:0xb1f3C577b81bed198c144b05B63ae185b313254F
- Asset Type:wweth_v1
- Tx: https://solscan.io/tx/3uFxN1WbHUiGs9iPt9N5vPqzyHgp2DKteMDr1uXBjcWZxXZHNPVUsRBoZKLPvnVvJ9tFoAYPgaucwrVWr2yCyWpc


### Current Behavior

Error message : Wormhole v1 and Sollet assets should not be transferred with this bridge


### Expected Behavior

Back to the ETH chain.

### Steps To Reproduce

Paste wweth_v1 address on bridge

### Anything else?

_No response_

**Comment by willis20188** [comment]
![2](https://github.com/XLabs/portal-bridge-ui/assets/83527164/3bf23f14-d3e6-459c-ab09-7a0c3edb6274)

**Comment by yuli-ferna** [comment]
@willis20188 please, could you open open a support ticket in the get-support channel of the discord. We will be able to help you with this case
