### ISSUE TITLE
Add permanent link to whscan in portal main page nav links

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#469]
**Task**
Add permanent link to whscan in portal main page 

- Add permanent link to whscan in portal main page
- 'Wormholescan' links to whscan

![Image](https://github.com/XLabs/portal-bridge-ui/assets/130170527/f7aba990-cc52-4d36-8aae-89a9da3d7c5b)

**Comment by Gpluv** [comment]
Design Here: https://www.figma.com/file/xDrOZdEBxBKBMXT6fI2LVR/Portal-Bridge?type=design&node-id=1444-470&mode=design&t=uB3PwtbyPUPAmzeh-4
@sebastianscatularo
