### ISSUE TITLE
[enhance] Update banner text at the top to include "Base" [October 26 tentative]

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#470]
Task
Update banner at the top of portalbridge.com to include "Base" in the text

**Acceptance Criteria**
The existing text should be updated to "Experience frictionless USDC transfers between Ethereum, Avalanche, Base, Optimism, and Arbitrum with Circle's CCTP."

**Comment by SamantaCasal** [comment]
OK Banner is updated 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/2ef3bd4a-d14d-4307-992d-a3d1da11055f
