### ISSUE TITLE
[enhance] update USDC tooltip text [October 26 tentative]

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#471]
**Task**
Update USDC Bridge tooltip text to:

"Convert some USDC to ETH, AVAX, BASE, OP or ARB and use it as gas to pay for transaction fees on the destination network."

![image](https://github.com/XLabs/portal-bridge-ui/assets/130170527/1d329e17-9dc1-4cee-a0a3-539bcddb6eb9)

**Comment by SamantaCasal** [comment]
@mliu-xlabs: 
It's ok this text? " Experience frictionless USDC transfers between Ethereum, Avalanche, Optimism, Base and Arbitrum with Circle's CCTP" 
![Screenshot 2023-10-26 at 4 12 04 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/408b9be1-f521-4222-b395-0b773fdc89b7)

**Comment by sebastianscatularo** [comment]
yes @SamantaCasal here is the ticket https://github.com/XLabs/portal-bridge-ui/issues/470

**Comment by SamantaCasal** [comment]
Is not ready to test yet. 
![Screenshot 2023-10-26 at 4 45 12 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/be158180-129c-4659-88e2-398da770d490)
