### ISSUE TITLE
[bug] incorrect notional max value

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When someone tries to send a large TX, larger than the big tx limit, the warning message the user receives says, for instance:

`This transfer's estimated notional value may exceed the remaining notional value available for transfers on Acala
($9,327) and may be subject to a delay.`

that is not accurate, since for big TX, must be held for 24hs

### Expected Behavior

a more descriptive message covering better the cases for big tx, and a link to the white paper explaining the governor system and the notional limits.  [paper](https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0007_governor.md)
 
check if the limit is hardcoded and in that case try to replace for a live version of it or at least update it.

### Environment

```markdown
- OS: N/A
- Wallet: N/A
- Browser: N/A
```

### Anything else?

https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0007_governor.md

![image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/65aaa7fd-1492-458b-9ed0-10adf8f58e8f)

**Comment by mliu-xlabs** [comment]
deprecating
