### ISSUE TITLE
[support] <Ticket 9689, cannot estimate gas>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source Chain: SUI
Source Chain Wallet: 0xd8d1e8d8c5eb0fda33c0ef771bfdd2d23266d808c17ab0d00d9de936213d4b73
Target Chain: BNB
Target Chain Wallet: 0xab31af4109ffbca760366c801c94daaa88888888
Asset Type: 2,949.54 USDC
Tx: BBFhnMjTMRmw4GaDXSB9G18ZwjBDSC7Bf1yTnSuzf5uL
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/9a933027-5f55-46fe-ad88-d3682107591f)

cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: invalid sender", method="estimateGas", transaction={"from":"0xab31aF4109fFbCa760366c801C94DaAA88888888","to":"0xB6F6D86a8f9879A9c87f643768d9efc38c1Da6E7","data":"0xc68785190000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000047901000000030d003d724eb11ae9e7b4335717fcf29e96cdc5052b9f4062a7c61de63696095f56247b00b781211cdcb5cf337d35b562d097110e09997404993d6fdbca9eab206e3d0102ed8500b1507dfdf9a9742145ec7a0eaa34c048ed740ee0889f87d0a0027642814d20ce1c215c0ade8b21ade6db096e13dc761725b25bec6c30e57bdad45df3e90103f677a36f493ba0525c6fc7a8015486ec8cad2ff003c13d50c3e7a7ddf208bb2271126e7318d9ab247b4661cb00f506e90d40ac9488e6f04d2e2a16ce24d424660104e6e3973ff437ff34fa72a0175e07474d8f0f2fccd97134d24ab4dce1bd3817d93ee6d499baeaa32c91872d81660aa41f5ab00fc3c2c5543eab0de745b30746170006a336b698c02275ae0f73426c3bfa9ce064b5588037076e9b7215f15cf2f2ebba271053bf964a7db58748d8939ddef87bb2c72adb68d223df44b7d5cc059d37000008e19db557eb12a57cf563e6655f45d2e76d98bc6fc346492769bcdbdd39bc18487ebae03c5d55113789e81441ab8a629546cda7a907dfcd83037909f536ab3dc10109ad661b8ed4f0b828a300ecebc9ebe295c63c93239d024eb4ff993edff22115c768b6fc21f48b5696cf6b52c26ec916579a431c106d2ba25f49007c51cba52f67010bb195d1d88edbb240edb8c26a94862b60c874f6ae4e89ab6199734ae80632bbb610c6423511d64e9d4e602344dd54b83ec74add7ee779a80b1abe736ef5e0e1ce000c0b7fcc82078f3c6901c8cd712696a1b6ad570a845c122c0db7be55bb3ad1787d644f930c606e620850e0bc2f5d845e986c6cc2cdf1f1f85ae974dc02b7a4b43c000d2a8254f7ed260470b3af7539294a8456f885b85a8f343614c4c163ea95e91434042305f7d7533964cbb2ed536162b7980edc6ac39639d88ea4ea9f87f929ad0c0010fa8b9f635391e416a974b5d2a3685f15ebc6633d562c513d75d259dc4729346154e9643d69ad59a97bda93f331feea87c0bb137dc7ba5f20122b4aab60945ec8011110fe5d76f5a08190908a198c1447acb0820d7e7c00686c03f050c2c3c06aa1611b1fd75496ad2f78f00c212109d54d17cd7b8875fea7f82a034fe1d1ce0d7f410012145fb19a260d111244c24a3e790e48ec7fdb1fda3fd76cc71b01cf2a6eeb235c4b0fb1d56deedfb7420bab95183b1d20b4cd0c5609ef892070d3f0eb5d60bc8f00653a0eb4000000750015ccceeb29348f71bdd22ffef43a2a19c1f5b5e17c5cca5411529120182672ade50000000000003f40000300000000000000000000000000000000000000000000000000000000afce5f24000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480002000000000000000000000000cafd2f0a35a4459fa40c0517e17e6fa2939441ca0004c4c610707eab9b222996b075f7d07c7d9b07766ab7bcafef621fd53bbf089f4e01000000000000000000000000000000000000000000000000000000000016e3600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ab31af4109ffbca760366c801c94daaa8888888800000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: invalid sender","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e696e76616c69642073656e646572000000000000000000000000000000000000"},"stack":"{\n \"code\": -32603,\n \"message\": \"Internal JSON-RPC error.\",\n \"data\": {\n \"code\": 3,\n \"message\": \"execution reverted: invalid sender\",\n \"data\": \"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e696e76616c69642073656e646572000000000000000000000000000000000000\"\n },\n \"stack\": \"Error: Internal JSON-RPC error.\\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)

### Expected Behavior

User should be able to redeem using the redeem workflow but encounter error

### Steps To Reproduce

1. https://www.portalbridge.com/#/redeem
2. Source Chain: SUI
3. Source TXID: BBFhnMjTMRmw4GaDXSB9G18ZwjBDSC7Bf1yTnSuzf5uL
4. Recover and encounters error

### Anything else?

User used
https://bridge.cetus.zone/sui
Gas Payment selected
SUI and USDC

**Comment by dry2022** [comment]
hello another user is having the same issue : 

Source Chain: SUI
Source Chain Wallet: 0x75dbc676ab6f2eff3bf484932ac476b79fe374aa2ad1b68d7e09b30bea8af982
Target Chain: BNB
Target Chain Wallet: 0xe322790A8A8caFcb4E364f672758F8C37053cFFB
Asset Type: USDC
Tx: 9x1RfHTt6p54DrEwxcMxrFWP3hGtB8KvapJf78Qf3cbk

**Comment by sebastianscatularo** [comment]
Hi @dry2022, both ops are ops with payload, and as far I can see at the Bridge code both need to be redeemed by using the proxy contract that has initiated them

https://github.com/wormhole-foundation/wormhole/blob/a04e8a386ccf16c2a3628bc29d3689179691d041/ethereum/contracts/bridge/Bridge.sol#L503

**Comment by dry2022** [comment]
thanks Seb! just to get this right, that's mean they need to go thru the url they bridge thru? like cetus for example?

**Comment by drisAloma** [comment]
> hello another user is having the same issue :
> 
> Source Chain: SUI Source Chain Wallet: 0x75dbc676ab6f2eff3bf484932ac476b79fe374aa2ad1b68d7e09b30bea8af982 Target Chain: BNB Target Chain Wallet: 0xe322790A8A8caFcb4E364f672758F8C37053cFFB Asset Type: USDC Tx: 9x1RfHTt6p54DrEwxcMxrFWP3hGtB8KvapJf78Qf3cbk

Hello @sebastianscatularo 
This has been resolved, 
Relayed successfully an hour ago, it was on the wormhole SUI bridge.
https://bscscan.com/tx/0xdbe4e630307041a02ca9d10a106f3a98419b3f9b4fb83cf1d227d20096cde0f2

**Comment by sebastianscatularo** [comment]
yes, that's correct

**Comment by drisAloma** [comment]
All good with the first one as well
We can close the ticket.
