### ISSUE TITLE
[bug] Navigation bar UI goes over source network list

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Navigation bar UI overlaps with Network list

### Expected Behavior

When source Network list is opened navigation bar stays at the back 

### Steps To Reproduce

Click on Source to open the Network list
Observe navigation bar UI positioning 

### Environment

```markdown
Preconditions: None

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://www.portalbridge.com/#/register
```

### Anything else?

![Screenshot 2023-10-26 at 17 33 31](https://github.com/XLabs/portal-bridge-ui/assets/91047061/491a6c37-911f-4d93-a81e-8c5eda7fa23f)

**Comment by mliu-xlabs** [comment]
verified still happening

**Comment by danielisaacgeslin** [comment]
![Image](https://github.com/user-attachments/assets/dce49fb5-2443-4d41-bf2d-16db260b1bcc)
