### ISSUE TITLE
[enhance] Hide FAQ nav link on Portal Bridge for the connect version on portal bridge main page

### ISSUE THREAD

**Issue by hernandiegosavio** [XLabs/portal-bridge-ui#479]
**Task**
Hide FAQ nav link in header for the connect replacement of portal bridge.

**Acceptance Criteria**
- for the Portal Bridge version that will have Connect in the main page, do not show the FAQ in nav
- for the old Portal Bridge version, continue to have the FAQ in the nav link

**Dependency:**
https://github.com/orgs/wormhole-foundation/projects/5/views/1?pane=issue&itemId=42683986

**Comment by sebastianscatularo** [comment]
addressed [here](https://github.com/XLabs/portal-bridge-ui/commit/419f40a24e4de745574b71cfda0c9f25151fbe13)
