### ISSUE TITLE
[enhance] Remove subpages from connect version of portal main page

### ISSUE THREAD

**Issue by hernandiegosavio** [XLabs/portal-bridge-ui#480]
**Task**
Remove subpages from connect version of portal main page

**Acceptance Criteria**
- Connect to Portal Bridge main page version will not have any subpages linked (remove CCTP, Sui, Cosmos)

**Comment by mliu-xlabs** [comment]
- lets make sure to preserve the deep links for SEO purposes for Sui and USDC bridge

**Comment by sebastianscatularo** [comment]
addressed [here](https://github.com/XLabs/portal-bridge-ui/commit/419f40a24e4de745574b71cfda0c9f25151fbe13)

**Comment by sebastianscatularo** [comment]
completed

https://preview.portalbridge.com/df5df83982/sui/ -redirects to-> https://preview.portalbridge.com/df5df83982/?sourceChain=sui
https://preview.portalbridge.com/df5df83982/cosmos/ -redirects to-> https://preview.portalbridge.com/df5df83982/?sourceChain=cosmos

sub pages removed

![Image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/fd23e886-fdc6-438a-b2fb-bfb144fb3d22)
