### ISSUE TITLE
[support] unable to redeem Moonbeam -> Ethereum (Ticket #9697）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:Moonbeam
- Source Chain Wallet:0x68eC7cd34DD6CB4Dfb01D98e84DDF4bEf0325230
- Target Chain:Ethereum 
- Target Chain Wallet:0x68eC7cd34DD6CB4Dfb01D98e84DDF4bEf0325230
- Asset Type:token
- Tx:https://moonscan.io/tx/0xb2191f6947f3c9a3c955bef0d5c2fef09de4144b8fe3191383d1083669d923aa
```

### Current Behavior

redeem workflow
Error message: cannot estimate gas
![2](https://github.com/XLabs/portal-bridge-ui/assets/83527164/1ff24855-87f7-4f73-80b6-71bf8218f62a)

**Comment by sebastianscatularo** [comment]
@willis20188 This TX has the same issue as https://github.com/XLabs/portal-bridge-ui/issues/477, 
`Invalid Sender` -> https://github.com/XLabs/portal-bridge-ui/issues/477#issuecomment-1781147267

**Comment by Dahtank** [comment]
Thanks @sebastianscatularo 

When trying to resume TX from https://app.beamswap.io/bridge(using wormhole connect), the TX seems to be stuck with loading the redeem TX as shown in the Screenshot, does the user need to contact Beamswap in this case?

![Screenshot 2023-10-28 at 06 06 11](https://github.com/XLabs/portal-bridge-ui/assets/141799468/bd8c18a4-2daf-4905-9879-cc255a631e08)

**Comment by sebastianscatularo** [comment]
in this case, could be an issue with the relayers, I'll check and keep you posted

**Comment by Dahtank** [comment]
Hey @sebastianscatularo, is there an issue with USDC relayer fees on SUI bridge? Another user experience similar issue

**Comment by Dahtank** [comment]
Redeemed by Sebastián Nale(Xlabs on Slack)

**Comment by Dahtank** [comment]
Redeemed by Sebastián Nale(Xlabs on Slack)
