### ISSUE TITLE
[connect > portal] - remove sub pages links

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#485]

**Comment by mliu-xlabs** [comment]
Also update the "Token Bridge" text in the nav link to make it "Home"

**Comment by mliu-xlabs** [comment]
Design:
https://www.figma.com/file/lxWryHZnWh99VvGTbqgfDN/Portal-Token-Bridge---Connet?type=design&node-id=107-1812&mode=design&t=BZ93MvZMRUTYXYHg-4

**Comment by sebastianscatularo** [comment]
addressed [here](https://github.com/XLabs/portal-bridge-ui/commit/419f40a24e4de745574b71cfda0c9f25151fbe13)
