### ISSUE TITLE
Support evmos, kujira, cosmoshub to portal bridge

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#497]
**Task**
Update connect for cosmos subpage in portal to support kujira, evmos

Kujira RPC to use: https://kujira-wormhole-rpc.synergynodes.com/

**Comment by mliu-xlabs** [comment]
cosmoshub is just testnet so going to remove that from this story

**Comment by sebastianscatularo** [comment]
completed on this PR https://github.com/XLabs/portal-bridge-ui/pull/509
