### ISSUE TITLE
[support]  Not able to redeem(Error message : "There are not enough valid signatures to repair.") <Ticket #9839>

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source chain : FTM
Source Address: 0x9DB52dC928E0B4208D1C351B6d5c31F3fb098696
Target chain : Polygon 
Target Address: 0x9DB52dC928E0B4208D1C351B6d5c31F3fb098696
Asset type: LINK
TX: https://ftmscan.com/tx/0x5d0f2cfd940884381cffd10a03a8dba04d5ffae5c44fb8917fd983b61c29ede8
```

### Current Behavior

 Not able to redeem
 Error message : "There are not enough valid signatures to repair."
 ![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/909e9e4a-6641-4e74-a9e9-f69f5c206933)

### Expected Behavior

Redeem

**Comment by sebastian-xlabs** [comment]
Yesterday we signed the requested VAA. I attach this file with the response from the guardian.
[20231113-signed-vaa.csv](https://github.com/XLabs/portal-bridge-ui/files/13348672/20231113-signed-vaa.csv)

**Comment by willis20188** [comment]
Thanks!
