### ISSUE TITLE
[support] <Ticket 9840 Terra -> Terra Classic> Error: requested VAA not found in store

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source Chain: Terra
Source Chain Wallet: terra1chgajhx5c66mzl7nd55cj6h0344qm3jg0ttnz8
Target Chain: Terra Classic
Target Chain Wallet: terra1chgajhx5c66mzl7nd55cj6h0344qm3jg0ttnz8
Asset Type: LOCAL token
Tx: 4556404884F793ED8EAD63ED400A583EC673FB9E246BCC2926B93216537B3575
https://finder.terra.money/phoenix-1/tx/4556404884F793ED8EAD63ED400A583EC673FB9E246BCC2926B93216537B3575
```

### Current Behavior

Unable to redeem or resume TX
Error: requested VAA not found in store
![Screenshot 2023-11-09 at 16 22 03](https://github.com/XLabs/portal-bridge-ui/assets/141799468/b87b9596-466b-4177-bf5e-299962722a80)

### Expected Behavior

TX should complete without issues

### Steps To Reproduce

1. https://www.portalbridge.com/#/redeem
2. Select: Terra as source chain
3. Enter the TXID: 4556404884F793ED8EAD63ED400A583EC673FB9E246BCC2926B93216537B3575

### Anything else?

LOCAL token is not native to Terra Classic, so should not be affected by the Terra Classic bridge paused

**Comment by sebastianscatularo** [comment]
@Dahtank 

![Image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/55bd751f-4795-4297-96b3-e486af953f19)

there is some VAA missed, you can check the wormhole dashboard https://wormhole-foundation.github.io/wormhole-dashboard/#/ I've asked to see if we can follow our regular process to recover this. I'll let you know once it is fixed. 

thanks :)

**Comment by Dahtank** [comment]
Closed as user able to redeem tokens
