### ISSUE TITLE
[support] Connect Klaytn network to Osmosis network on Cosmos section

### ISSUE THREAD

**Issue by steve-jeon-KF** [XLabs/portal-bridge-ui#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Klaytn
- Source Chain Wallet: Metamask
- Target Chain: Osmosis 
- Target Chain Wallet: Keplr/Metamask 
- Asset Type: Token
```

### Current Behavior

I have a conversation with Robinson and he said that Klaytn network is already connected to Cosmos network (But, not sure whether it's connected to Osmosis network), and needs to display this on UI in Cosmos section. 

### Expected Behavior

Display Klaytn network on Cosmos section and be able to connect with Osmosis network.

**Comment by sebastianscatularo** [comment]
@yuli-ferna could we check if Klaytn is configured on our Cosmos section?

**Comment by steve-jeon-KF** [comment]
@sebastianscatularo @yuli-ferna Any updates?

**Comment by mliu-xlabs** [comment]
moving issue to here:
https://github.com/wormhole-foundation/wormhole-connect/issues/1296

**Comment by steve-jeon-KF** [comment]
Okay, do you know about the expected due date?
