### ISSUE TITLE
OSMOSIS -> SOLANA : can't redeem "Bridge transaction not found" CLAIMED 9893

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source chain : Osmosis
Wallet Source chain :  osmo1lttjtqh26d9dhy2v2kc74zdpd7yl2xtardr55m
Target chain :  Solana
Wallet target chain :  AvSJMKHoVnW4qPM4362gw58zSB4krwvQeiQsuCqxA1Pf
Tx: d696306ae2f72719fe7a1d791b64d4382c1af37644302217965e6c6fc723b02c

https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/248?view=rawdata
```

### Current Behavior

can't redeem on SOLANA. while going thru this  https://www.portalbridge.com/cosmos/ then resume transaction it said : Bridge transaction not found, check that you have the correct chain and transaction ID

https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/248?view=rawdata

**Comment by willis20188** [comment]
Any update on this please?

**Comment by dry2022** [comment]
hello! @M-Picco do you take care of all OSMOSIS related issue ?

**Comment by dry2022** [comment]
the user is still having the same issue 
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/6e8f1613-212e-4758-8ae7-00edfd0f20b9)

**Comment by sebastianscatularo** [comment]
@dry2022 seems this TX has been redeemed correctly, closing it, seems it is not longer an issue

https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/248?view=overview:~:text=0X8964EDC4A5A2687B5740759D1B3A0DEC64BDBE49DF9421FA389CF97F8D58F20F

https://explorer.aptoslabs.com/txn/0x8964edc4a5a2687b5740759d1b3a0dec64bdbe49df9421fa389cf97f8d58f20f?network=mainnet
