### ISSUE TITLE
[support] <Ticket 9940 OPT -> APT Cannot read properties of undefined (reading 'name')>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: OPT
- Source Chain Wallet: 0xcc3cd86ddcaa0bf51c5e00e0f58e8b2e7ded91bc
- Target Chain: APT
- Target Chain Wallet: 0x43626957168e78b87a5a59a26ab2870f0035ffcfb523d5e484eccb6a71333785
- Asset Type: USDC
- Tx: 0xf595ea0c7e64dd43856027ffe03682f9d69a91d6007f59bbe83400d455a88ee8
https://wormholescan.io/#/tx/f595ea0c7e64dd43856027ffe03682f9d69a91d6007f59bbe83400d455a88ee8
```

### Current Behavior

Transaction error
Cannot read properties of undefined (reading 'name')

Payload
Function: 0x576410486a2da45eee6c949c995670112ddf2fbeedab20350d506328eefc9d4f::complete_transfer::submit_vaa_and_register_entry

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/39db179d-5c1e-4583-968e-b6750d5b5734)

### Expected Behavior

able to redeem without error

### Steps To Reproduce

1. https://www.portalbridge.com/#/redeem
2. Select OPT as source chain
3. Enter 0xf595ea0c7e64dd43856027ffe03682f9d69a91d6007f59bbe83400d455a88ee8 as Source TXID
4. Click Recover
5. Connect Petra wallet and Redeem

### Anything else?

Tested redeeming workflow for user, but got another error "Simulation failed with following error:
Simulation error"

Please note that i do not have Aptos tokens in wallet

![Screenshot 2023-11-14 at 14 46 10](https://github.com/XLabs/portal-bridge-ui/assets/141799468/15a11a02-4459-4ebd-9740-c5c6e51e2045)

**Comment by Dahtank** [comment]
Hey, anyone had a chance to look into this yet? :)

**Comment by dry2022** [comment]
@sebastianscatularo hey, any update for this case? :)

**Comment by Dahtank** [comment]
Seem like Pontem wallet is the problem, works with Martian Wallet
