### ISSUE TITLE
[enhance] update the 'token bridge' nav link

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#520]
**Task**
Update the nav link 'Token Bridge' to say 'Home' instead

**Comment by Gpluv** [comment]
Design: 
https://www.figma.com/file/lxWryHZnWh99VvGTbqgfDN/Portal-Token-Bridge---Connet?type=design&node-id=107-1812&mode=design&t=BZ93MvZMRUTYXYHg-4

**Comment by mliu-xlabs** [comment]
This is a duplicate

**Comment by sebastianscatularo** [comment]
completed



![Image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/b969d2c1-0b3f-4581-b5d7-46cd158bcc30)
