### ISSUE TITLE
[connect > portal] - define configs to preset source for chains not supported by Connect (Acala, Algorand, Sei)

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#523]
When a user selects Acala, Algorand, or Sei in the source chain selector, direct the user to the former portal bridge UI with the source chain preset based on the user's previous selection.

define configs to preset source for chains not supported by Connect (Acala, Algorand, Sei)

**Comment by sebastianscatularo** [comment]
completed 



![Image](https://github.com/XLabs/portal-bridge-ui/assets/1277510/e92a4343-4a86-40a3-ae9f-55cf2ca5f0a9)
