### ISSUE TITLE
[support] Can't Resume（Ticket #9997）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:Osmosis
- Source Chain Wallet:osmo16l59nmv04vmud6myh6332a28r9gxl4xusdqegz
- Target Chain:ETH
- Target Chain Wallet:0x5c76566954bd0e68822ee3f2ac71caa528c5a2d4
- Asset Type:WETH
- Tx:https://dev.mintscan.io/osmosis/txs/5C8CBEF6EA5F17ADFBEF59F1A2665D790DDA53500C168F846E0622D6976C01B4?height=12378531
```

### Current Behavior

Can't Resume
Error message：Bridge transaction not found, check that you have the correct chain and transaction ID

![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/e636e0bc-f225-4b1c-b128-c0a89d7e5092)
https://www.portalbridge.com/cosmos/

### Expected Behavior

Resume

### Steps To Reproduce

https://www.portalbridge.com/cosmos/
Open Menu, Resume TX
Select OSMO and Paste the TX 
5C8CBEF6EA5F17ADFBEF59F1A2665D790DDA53500C168F846E0622D6976C01B4
Bridge transaction not found, check that you have the correct chain and transaction ID

**Comment by dry2022** [comment]
@M-Piccowe have also this user on OSMO
