### ISSUE TITLE
[bug] Completed transaction is shown as not completed

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Completed transaction is shown as not completed. "Claim" button is shown in "Send to" section.

### Expected Behavior

Transaction is shown as completed.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/df5df83982/
2. Click "Resume transaction" link
3. Search for transaction hash 0x429c3bb17996d84f6a16a7d81d66670e10050cec533b433745c90a0a6cf60e0f in Optimism network
4. Observe if transaction is completed

### Environment

```markdown
- OS: macOS 12.7
- Wallets: Metamask, Phantom
- Browser: Google Chrome Version 119.0.6045.159 (Official Build) (x86_64)
```

### Anything else?

Screenshots show how the same transaction looks on https://wormhole-connect-mainnet.netlify.app/ and on https://preview.portalbridge.com/df5df83982/. 

![Screenshot 2023-11-22 at 19 43 26](https://github.com/XLabs/portal-bridge-ui/assets/10746654/9df24644-4c08-4083-943a-6cce9a2e4fed)

Send to tx: [Solana explorer](https://explorer.solana.com/tx/61rpBLJQAT73nncf8aAbgh8FrUCdKQXL3DhPtADtwhvPLFemrAHQL85p515GUoCdUwDdHhDUhLaCychAW43GHM2F)
Link to Wormhole explorer: [Wormholescan](https://wormholescan.io/#/tx/0x429c3bb17996d84f6a16a7d81d66670e10050cec533b433745c90a0a6cf60e0f)

**Comment by mliu-xlabs** [comment]
Think this might be a connect issue, not portal specific

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ [Mainnet]. 

* Transaction mentioned in the description is shown as completed on https://portalbridge.com/ [Mainnet]. Tx hash `0x429c3bb17996d84f6a16a7d81d66670e10050cec533b433745c90a0a6cf60e0f` (Optimism)
* Initiated a new transfer, sent 0.000001 tBTC from Optimism (MetaMask) to Solana (Phantom). Transaction completed successfully.
  * Send from tx:  [Optimistic Etherscan](https://optimistic.etherscan.io/tx/0x9e7110b98dd45598d0cb38cd38ad04506e15a0182568d95638f80f15251a1957)
  * Send to tx: [Solana Explorer](https://explorer.solana.com/tx/5vyKpmQq6mhJLhr8ecPFkZnnw3YmVey2cwNqVgQX4UH4XLk3NhN2Hz7o7GdkJNkHKUAiVFqYCAKfCJsEFmRzVhxA)
  * Link to [Wormholescan](https://wormholescan.io/#/tx/0x9e7110b98dd45598d0cb38cd38ad04506e15a0182568d95638f80f15251a1957)

Ticket is closed.
