### ISSUE TITLE
[bug] [connect/ portal] Space is missing between paragraph and search input

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Space is missing between paragraph and search input.

### Expected Behavior

There is space between paragraph and search input.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/df5df83982/
2. Click "Resume Transaction" link

### Environment

```markdown
- OS: macOS 12.7
- Wallet: - 
- Browser: Google Chrome Version 119.0.6045.159 (Official Build) (x86_64)
```

### Anything else?

![Screenshot 2023-11-22 at 19 55 42](https://github.com/XLabs/portal-bridge-ui/assets/10746654/01e93dcf-bf16-474b-b2b3-6a91240afb7a)

**Comment by sebastianscatularo** [comment]
@tsadovska this should be fixed now :)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
* https://preview.portalbridge.com/df5df83982/ [Mainnet] v0.2.0-P9316d62b51
* https://testnet.portalbridge.com/df5df83982/ [Testnet] v0.2.0-T9316d62b51

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/2369ab7c-4d1a-40ba-a0a1-41759db4d22c)

Ticket is closed.
