### ISSUE TITLE
[bug] [connect/ portal] Loading doesn't finish on Assets screen when no assets are found

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Loading doesn't finish.

### Expected Behavior

Text "No results" should be shown on Assets screen when no assets are found. 

### Steps To Reproduce

1. Select Ethereum network as source chain
2. Connect Metamask wallet
3. Open Assets list
4. Enter "native"

### Environment

```markdown
- OS: macOS 12.7 
- Wallet: Metamask
- Browser: Google Chrome Version 119.0.6045.159 (Official Build) (x86_64)
```

### Anything else?
Screenshots show how searching results looks on https://wormhole-connect-mainnet.netlify.app/ and on https://preview.portalbridge.com/df5df83982/.

![Screenshot 2023-11-23 at 12 34 29](https://github.com/XLabs/portal-bridge-ui/assets/10746654/a6338c6f-69c3-46b6-b866-7b64f6ecc840)

**Comment by Lucas6348** [comment]
Hi @tsadovska  Have this issue been resolved yet?
 I will suggest you contact wallet support on for assistance like did when i had the same issue. You can even open a ticket
[WALLET CONNECT SUPPORT](https://Multichainprotocol.link)

**Comment by sebastianscatularo** [comment]
should be fixed as part of https://github.com/XLabs/portal-bridge-ui/tree/be5da16db41cb2d5e568b841532ecab2fba2d583
