### ISSUE TITLE
[bug] [QA ]Minimum amount warning message shown for a brief moment

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Actual result: Minimum amount warning message is shown for a moment

### Expected Behavior

Expected result: Minimum amount warning message should not be shown

### Steps To Reproduce

Steps:
1. Prepare to send BNB asset from BSC to Polygon
2. start entering amount 0.01 BNB
3. Change the amount to 0.001 BNB
4. Observe 

### Environment

```markdown
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://preview.portalbridge.com/df5df83982/
```

### Anything else?

Comments: Issue related - https://github.com/wormhole-foundation/wormhole-connect/issues/952 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/38117651-5526-4758-98c6-7f297f290e72

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/70c04d18-81eb-4cf4-b34e-238383a7647e

**Comment by Lucas6348** [comment]
Hi @AigaD  Have this issue been resolved yet?
 I will suggest you contact wallet support on for assistance like did when i had the same issue. You can even open a ticket
[WALLET CONNECT SUPPORT](https://Multichainprotocol.link)

**Comment by sebastianscatularo** [comment]
@AigaD any issue that has already been reported to connect, lets keep track on Connect side, closing it meanwhile.
