### ISSUE TITLE
[bug] ETH (Base) double naming in Asset field

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the moment asset ETH (Base) shows as "ETH (Base) (Base)" in the asset field when selected

### Expected Behavior

Perhaps only main ETH (Base) could be displayed to user when asset is selected

### Steps To Reproduce

1. Connect Metamask wallet
2. Select Base Network
3. Select ETH (Base) asset
4. Observe

### Environment

```markdown
Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://preview.portalbridge.com/df5df83982/
```

### Anything else?

![Screenshot 2023-11-23 at 15 17 36](https://github.com/XLabs/portal-bridge-ui/assets/91047061/3f51e363-c20f-4a51-8506-397b4bd96158)

**Comment by sebastianscatularo** [comment]
@AigaD  this is https://github.com/wormhole-foundation/wormhole-connect issue, does not apply to portal, could we move it there? closing it meanwhile
