### ISSUE TITLE
[bug] [connect/ portal] Cannot change slider position 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot change slider position.

### Expected Behavior

User can change slider position in "Native gas" section.

### Steps To Reproduce

1. Prepare to send 10 GLMR from Moonbeam (Metamask) to Solana (Phantom)
2. Enable "Native gas" section
3. Change slider position

### Environment

```markdown
- OS: macOS 12.7
- Wallets: Metamask, Phantom
- Browser: Google Chrome Version 119.0.6045.159 (Official Build) (x86_64)
```

### Anything else?

* Issue is also reproducible on https://preview.portalbridge.com/df5df83982/ [Mainnet] when sending 0.007 ETH from Ethereum (Metamask) to Solana (Phantom)
* Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

1) https://preview.portalbridge.com/df5df83982/ [Mainnet]

https://github.com/XLabs/portal-bridge-ui/assets/10746654/b37283a1-9690-4ec8-a276-ae20925e25cd

2) https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

https://github.com/XLabs/portal-bridge-ui/assets/10746654/87174113-d342-44ab-9ba1-af8e93f73642

**Comment by sebastianscatularo** [comment]
this should be fixed as part of https://github.com/XLabs/portal-bridge-ui/tree/be5da16db41cb2d5e568b841532ecab2fba2d583
