### ISSUE TITLE
TICKET 10178 : Terra Classic - can't redeem - Request failed with status code 404

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Source chain (name) : Terra Classic

Wallet Source chain (adress) : ??? To be confirmed by the user 

Target chain (name) : Avax

Wallet target chain (adress) : 0x381DCd13738D9347b84BC5fd67aCAb6eDFdE341F

tx1 = C446B03AE7A3E68A1A95C6518E9AEAF2676353AC62694EABD7BEB628C5F1207F

tx2 = C8B61BDCA05C0B7DC21616F76209ADA53CC6F3EDFBF8AD39E2DADE04FED7594A

tx3 = 144CC56222702F4D48099B6CC5C97C5314DA9979CECA3F4F95E32F0F702DEF8A

tx4 = 342CDF7D55070D1B572748BC0AFAF46A049EB54AA0404020D1542A852FE6C8A0
```

### Current Behavior

a user bridge, back in May 22' lunc & ustc from TC to Avax. 

when i put in redeem his tx i have : Request failed with status code 404

### Expected Behavior

redeem on Avax chain

**Comment by dry2022** [comment]
Wallet Source chain (adress) : terra1u2ga74868w5rxdpyu6zk4zm6gvsu5czlgxgzjk

**Comment by dry2022** [comment]
UPDATE : 

3 out of 4 have been redeemed -> only this one left : 

144CC56222702F4D48099B6CC5C97C5314DA9979CECA3F4F95E32F0F702DEF8A

that's the issue we are seeing :  

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/b472aaa7-f962-4b8d-bee7-5761aeaad61f)

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you try to redeem using the following VAA, @dry2022 could you check if the user can redeem it with the following VAA

```01000000030d002d0302a9066d533daa2caec5133389e4153414f32d91edbb6972a4874e8974426dfbcf12c3e159abb405db1617f42cef7ff792971f76750021002d301189bff20002bd37986c453dd4cae9ac84292a1db786ca41cdaf6657eeff93983ad8f0cc3c9d56867bd0bddba3830699f7b4d270b55733aa9e2bbfb8995c2f7078e15242bef40103be52a64ece05ed5b55192e8640431dfa958fcf0c73875c4c1bdaea281e7d77815ade23636d6e27189ea3834f46344ac2ae6aa5171382cddcf483b039081cff41000475e806a23a7817bdad3fffee1460b529dc282f19664ac6a9ac5d49b754e27c8867effee82ade0a9775707f09977392db15c753146875da5cfd71f470190339740106216194896eae800fd433f22deb1931b8b25229cbead95e691e1624dcdbd86333644ba8c78bdb11b9ce0e62a879d0aabb402abd5b33b750f9b9533fd866fc3e1e010964380c03a630a56037ae845ae366368230ecc833aecd1f651eed6210f74731ca0a1c156801242600f8936afc9cd7f0bfe16faf436eb13e519989e38b1067955a000a2f096483378300fc80acc4cf9add1fc35194a5d7d60de41255500d3a655b5df3117bf367e4a6ae85d49160db9dd13b3d56dfa5286127e3609894d12ada55bd54010bab8f2b648eb1bfe0c2e7b30fd7b11b832d3334227fe18f1b96d77ee3533c0e2217b2d4137146e7d1e2fb05add05ea79a271a70603dbea9810a6dff08e440d50b010cf045833e1a2ba704e85a581b5ab5a9d343eb9f48cd0c7f117588cf6e36d095a9380a5a8cad7c9e5aad8304315737b537b6dcb71380521b6e9993f5acbbe04147010d1b58dae8932c57ac17bda74651209f4c948a111de89ae2cf6b8d5f0b48c293e61a6396c727ea656ee274ab194a48d00fb433ea09241643f79f6409577c1d330c010e32547212512c0988be5be9967d2311f31121f0260cddf5d5e82465873011571b124a93654d4b4266c39d9621f4188529fce1be10938de7311501e2766188e97c0010a20ddf416cd282fb0af6085d82e8486f9226004e5844f46d8106ad2e0d53f3c411b908fea7569009ad93c8f2bf565d0ffe81c0c972e5a3cb956f09a3767461230012afa2f8fb4fec9c4e55c8caa64583f4c12ea4a3ae39dc6e1685fc81c58fda186d248b3d8284e4825f831c8eaf9a4cef2ebf3c80dddb33796043719aef973c0b07016297bd320000e0c700030000000000000000000000007cf7b764e38a0a5e967972c1df77d432510564e20000000000037570000100000000000000000000000000000000000000000000000000000001299b224001000000000000000000000000000000000000000000000000000000757573640003000000000000000000000000381dcd13738d9347b84bc5fd67acab6edfde341f00060000000000000000000000000000000000000000000000000000000000000000```

**Comment by sebastianscatularo** [comment]
if that doesn't work, we should need to re sign the tx, please, let me know

**Comment by SamantaCasal** [comment]
The TxRedeem: https://snowtrace.io/tx/0x941999a8447459e6349fe2386b5e00c5b5c241ad43898eebfe1a4c8f316ee9bd
https://github.com/XLabs/portal-bridge-ui/assets/69044575/1b42cfc0-8182-4736-b803-f39199e09b5d
