### ISSUE TITLE
[bug] [connect/ portal] Link to Wormholescan is not fully visible on small screen

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Link to Wormholescan is not fully visible on small screen. 

### Expected Behavior

Link to Wormholescan is well displayed.

### Steps To Reproduce

1. Open https://testnet.portalbridge.com/df5df83982/ on mobile 
2. Observe if link to Wormholescan is well displayed

### Environment

```markdown
- OS: iPhone 11 Pro iOS 16.5.1
- Wallet: - 
- Browser: Google Chrome Version 114.0.5735.124
```

### Anything else?

![Screenshot 2023-11-27 at 17 46 03](https://github.com/XLabs/portal-bridge-ui/assets/10746654/079de41a-599e-4578-96a2-48c68301e2f7)

**Comment by sebastianscatularo** [comment]
should be fixed as part of https://github.com/XLabs/portal-bridge-ui/pull/540
