### ISSUE TITLE
[bug] [connect/ portal] Text in the Footer is overlapped on small screen

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Text in the Footer is overlapped on small screen.

### Expected Behavior

 Text in the Footer is shown correctly. 

### Steps To Reproduce

1. Open https://testnet.portalbridge.com/df5df83982/ on mobile
2. Observe if version number overlaps text "Powered by Wormhole"

### Environment

```markdown
- OS: iPhone 11 Pro iOS 16.5.1
- Wallet: - 
- Browser: Google Chrome Version 114.0.5735.124
```

### Anything else?

![Screenshot 2023-11-27 at 18 15 16](https://github.com/XLabs/portal-bridge-ui/assets/10746654/8d972442-c0a0-49b3-ba40-de20692ef9f9)

**Comment by sebastianscatularo** [comment]
should be fixed as part of https://github.com/XLabs/portal-bridge-ui/pull/545

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
- https://preview.portalbridge.com/df5df83982/ [Mainnet]
- https://testnet.portalbridge.com/df5df83982/ [Testnet]

Checked on:
- iPhone 11 Pro iOS 16.5.1 with Google Chrome Version 114.0.5735.124
- Samsung S20 Android 12 with Brave 1.60.118, Chromium 119.0.6045.163

Ticket is closed.
