### ISSUE TITLE
[bug] [connect/ portal] Two same tabs are opened when user clicks on Algorand/ Acala/ Sei

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Two same tabs are opened when user clicks on Algorand/ Acala/ Sei.

### Expected Behavior

Only one tab is opened. 

### Steps To Reproduce

1. Allow pop-ups and redirects permissions to https://testnet.portalbridge.com/df5df83982/ 
2. Select Algorand/ Acala/ Sei network

### Environment

```markdown
- OS: macOS 12.7.1 
- Wallet:
- Browser: Google Chrome Version 119.0.6045.159 (Official Build) (x86_64)
```

### Anything else?

![Screenshot 2023-11-27 at 20 37 02](https://github.com/XLabs/portal-bridge-ui/assets/10746654/ff5673f2-a01d-4835-9bab-6ec696e4b23b)

https://github.com/XLabs/portal-bridge-ui/assets/10746654/86dbcc7f-e1d5-48f0-9060-a4e90d028f85

**Comment by sebastianscatularo** [comment]
should be fixed on https://preview.portalbridge.com/df5df83982/

**Comment by AigaD** [comment]
Tested OK, closing the ticket.
Tested from: https://testnet.portalbridge.com/df5df83982/ and https://preview.portalbridge.com/df5df83982/
One tab is opened when user clicks on Algorand/ Acala/ Sei.
Attachment:

https://github.com/XLabs/portal-bridge-ui/assets/91047061/1aedee31-9ef5-49b5-9488-4ca436bc716d
