### ISSUE TITLE
[support] Cannot Redeem Transaction : "Request failed with status code 404"<ticket 10178>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:Terrac Classic
- Source Chain Wallet:
- Target Chain: Avalanche 
- Target Chain Wallet: Metamask 
- Asset Type: Token 
- Tx: https://wormholescan.io/#/tx/342CDF7D55070D1B572748BC0AFAF46A049EB54AA0404020D1542A852FE6C8A0

https://wormholescan.io/#/tx/C8B61BDCA05C0B7DC21616F76209ADA53CC6F3EDFBF8AD39E2DADE04FED7594A

https://wormholescan.io/#/tx/144CC56222702F4D48099B6CC5C97C5314DA9979CECA3F4F95E32F0F702DEF8A

https://wormholescan.io/#/tx/C446B03AE7A3E68A1A95C6518E9AEAF2676353AC62694EABD7BEB628C5F1207F
```

### Current Behavior

Redeem  workflow returned "Request failed with status code 404"

### Expected Behavior

Show Recover Button 

### Steps To Reproduce

1. Go to https://www.portalbridge.com/#/redeem
2. Choose Terra Classic as source chain.
3. Paste in transaction hash 

### Anything else?

The transactions are over 18 months old

**Comment by dry2022** [comment]
hey @drisAloma I opened this ticket already yesturday :) https://github.com/XLabs/portal-bridge-ui/issues/542

you can close this one if you are okay

**Comment by drisAloma** [comment]
Oh, okay cool
