### ISSUE TITLE
[bug] [connect/ portal] Clicking on Help icon opens an error page

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on Help icon opens an error page "This preview.portalbridge.com page can't be found".

### Expected Behavior

Page is opened. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/df5df83982/ on mobile
2. Scroll down
3. Click on "Advanced Tools" link
4. Click on Help icon
5. Observe

### Environment

```markdown
Checked on:
* Samsung S20 Android 12 with Brave 1.60.118, Chromium 119.0.6045.163
* iPhone 11 Pro iOS 16.5.1 with Google Chrome 114.0.5735.124
```

### Anything else?

![Screenshot 2023-11-28 at 11 25 12](https://github.com/XLabs/portal-bridge-ui/assets/10746654/a58d581f-88d8-4936-92c8-a31417cfeb1c)

https://github.com/XLabs/portal-bridge-ui/assets/10746654/d62066b7-b2fa-4394-a1fe-2ee04f471fac

**Comment by sebastianscatularo** [comment]
this should be fixed 


https://github.com/XLabs/portal-bridge-ui/assets/1277510/63abc00d-5128-467c-b4f7-42730fd85ba5

as part of https://github.com/XLabs/portal-bridge-ui/tree/bb0ddb362a7c81c43a3f385ed7d42edc497b1301

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
- https://preview.portalbridge.com/df5df83982/ [Mainnet]
- https://testnet.portalbridge.com/df5df83982/ [Testnet]

Checked on:
* Samsung S20 Android 12 with Brave 1.60.118, Chromium 119.0.6045.163
* iPhone 11 Pro iOS 16.5.1 with Google Chrome 114.0.5735.124

Ticket is closed.
