### ISSUE TITLE
[bug] [connect/ portal] Menu is not visible in Portrait mode

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Menu is not visible in Portrait mode.

### Expected Behavior

Menu is visible.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/df5df83982/ in Portait mode
2. Scroll down
3. Click on "Advanced tools" link
4. Observe if Menu is displayed

### Environment

```markdown
- OS: Samsung S20 Android 12
- Wallet: -
- Browser:  Brave 1.60.118, Chromium 119.0.6045.163
```

### Anything else?

![device-2023-11-28-114249](https://github.com/XLabs/portal-bridge-ui/assets/10746654/b12eba57-376e-41a0-95c9-d5038cbec581)
![Screenshot 2023-11-28 at 11 41 19](https://github.com/XLabs/portal-bridge-ui/assets/10746654/1eeea3fa-aa57-43a0-9e7f-68e2500f9a4d)

**Comment by sebastianscatularo** [comment]
this is working as design
