### ISSUE TITLE
[bug] [connect/ portal] Balance is not loading for Cosmoshub

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Balance is not loading for Cosmoshub.

### Expected Behavior

Balance is loaded.

### Steps To Reproduce

1. Select Cosmoshub network as source chain
2. Connect Leap/ Keplr wallet

### Environment

```markdown
- OS: macOS 12.7.1 
- Wallet: Leap/ Keplr
- Browser: Google Chrome Version 119.0.6045.159 (Official Build) (x86_64)
```

### Anything else?

* Issue is not reproducible on https://wormhole-connect.netlify.app/ [Testnet].
* Screenshot (https://testnet.portalbridge.com/df5df83982/)

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/148777eb-84d0-4bee-b68e-bb6f7c37cc7c)

**Comment by AigaD** [comment]
Reproduced from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/#
Balance is not loading for Cosmoshub Network
Attachment:

https://github.com/XLabs/portal-bridge-ui/assets/91047061/c74ac39b-1c07-4547-810d-bf7f611da532

**Comment by tsadovska** [comment]
Closing the ticket, because currently Cosmos networks are not displayed in the Networks list.
