### ISSUE TITLE
[bug] walletconnect times out

### ISSUE THREAD

**Issue by opsecx** [XLabs/portal-bridge-ui#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Walletconnect connections do not conclude, but time out. 

When using walletconnect, the connection times out. This is across different wallets and devices.

Advise upgrading the walletconnect modal to latest, as know from other contexts this tends to fix the issue.

### Expected Behavior

Walletconnect connection is established.

### Steps To Reproduce

1. Open portalbridge.com in any browser
2. Press connect
3. Select Walletconnect
4. Use QR-code
5. Scan QR-code with wallet (trust or metamask)
6. Wait for connection
7. Observe no connection happens

### Environment

```markdown
- OS: Windows 10 (browser), ios 15.8 (mobile wallets)
- Wallet: Metamask mobile and Trust wallet
- Browser: Edge/Chrome/Firefox
```

**Comment by sebastianscatularo** [comment]
@opsecx we deployed a couple of fixes that should affect this, could you try again, I'm closing the issue meanwhile, feel free to re open it if you still face issues with wallet connect

**Comment by opsecx** [comment]
> @opsecx we deployed a couple of fixes that should affect this, could you try again, I'm closing the issue meanwhile, feel free to re open it if you still face issues with wallet connect

Behavior still persists. Not sure I have permissions to reopen. Recommend upgrading the wc-modal.

**Comment by sebastianscatularo** [comment]
yes, that is at the connect side https://github.com/wormhole-foundation/wormhole-connect/pull/1285, we are waiting on a new connect release to upgrade it, I'll let you know once it is done, meanwhile, [advanced-tools](https://portalbridge.com/advanced-tools/#/transfer) use wc v2
