### ISSUE TITLE
[support] <Ticket 11221 Kujira unable to Bridge tokens on PortalBridge>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:Kujira
- Source Chain Wallet: kujira1973qhhswmsf0y99h88t40v7ecgzqhs6rwafk58
- Target Chain:Solana
- Target Chain Wallet: 75HiK486fcj6gDH2KkW2RrhogUKj6iYsKgCsBbXwtXFK
- Asset Type:whSOL
- Tx:
```

### Current Behavior

Trying to send whSOL from KUJI to SOL. Portalbridge doesnt show the balance of my whSOL in my Kuji wallet, and then when I try to transfer it says error please try again.
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/5d125fdc-0f1c-489e-96d9-7c8005774028)

**Comment by sebastianscatularo** [comment]
seems to be the same issue as https://github.com/XLabs/portal-bridge-ui/issues/580

**Comment by SamantaCasal** [comment]
Tested from: 
https://portalbridge.com/
OK! Sending wSol from Kujira -> Solana 
[wormholesacn](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/2625)
[explorerSoana](https://explorer.solana.com/tx/2sdHfFmBGfjQ236zVX5rVnNfiDdU518ua5RQfwsfhSMceMSBfqRAQxpsmJcQARiG1vEu3GqnPEd9eppGsQcBDWbV)
[kujiraFinder](https://finder.kujira.network/kaiyo-1/tx/0EC3E1F9D4545A1646DA590F7317992C2A1D78CD69972E27BA57702C57EF38A5)

Evidence

https://github.com/XLabs/portal-bridge-ui/assets/69044575/c7a1d63c-2994-411c-94d8-f8d9255a73e2

**Comment by sebastianscatularo** [comment]
since it was verified successfully, we are going to close this, @Dahtank please open a new ticket if you get the error again, but, this could due relayer or network congestion, I hope in the short time we will have a better visibility of this kind of issues.
