### ISSUE TITLE
[support] <Ticket 11219 BNB -> INJ transaction failed>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:BSC
- Source Chain Wallet:0xf18ca3753c5bba51b97fd410542ca739b4de5e71
- Target Chain:INJ
- Target Chain Wallet:inj193w3jtcvlntlyxgqnt9nd7gc22vjsqfx7z4anr
- Asset Type:
- Tx: 0xae6e01ae9b2a5aecf06e4eb6debac8693c6066b05ce46212dbc36242d4a4332e
https://wormholescan.io/#/tx/0xae6e01ae9b2a5aecf06e4eb6debac8693c6066b05ce46212dbc36242d4a4332e
```

### Current Behavior

I'm bridging some INJ and I keep having an error "The transaction failed to be included within a block on time."

**Comment by sleepycorgi1** [comment]
User resolved his issue by changing the RPC endpoint in my keplr wallet and then it worked . Please close this issue, thanks.
