### ISSUE TITLE
[support] <Ticket 11212 Evmos token balance not showing>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain:
- Source Chain Wallet:
- Target Chain:
- Target Chain Wallet:
- Asset Type:
- Tx:
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/a1c49f37-b22f-45db-be46-20f0cf55f279)

**Comment by sleepycorgi1** [comment]
Resolved - please close this ticket .
