### ISSUE TITLE
INJECTIVE ISSUE 11213

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
https://wormholescan.io/#/tx/0x2ded536da385c80a1467c5d94710b018593d5b94b8384c80c26e37135f292be1

can't redeem
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/6dbfae87-eb69-4898-8031-0b86180af79c)
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/970adf1c-878e-4b1f-824a-fb2b9fdb55ab)

**Comment by sebastianscatularo** [comment]
we are working on this, it should be fixed after this [PR](https://github.com/XLabs/portal-bridge-ui/pull/592) got merged and deployed.
