### ISSUE TITLE
[support] <Ticket 0029, SUI -> AVAX cannot redeem/resume, cannot estimate gas;>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Operation Details

```markdown
- Source Chain: SUI
- Source Chain Wallet: 0xd0173bb7862e52b9a45f53b6e7bd5645d493ea1009c6fd131247929b62e97d62
- Target Chain: AVAX
- Target Chain Wallet: 0x2701acdcdd03212bf95e332b8fb0e33682e4f47f
- Asset Type: wAVAX
- Tx: 8Smwb3k7cBGwPhBfPif9AjSwgg6RPuk8no2x4VuW3R1u
https://wormholescan.io/#/tx/8Smwb3k7cBGwPhBfPif9AjSwgg6RPuk8no2x4VuW3R1u
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/92444a43-60ef-4e0d-a4a3-49448298ac5f)
User has enough AVAX to redeem
Tested the redeem workflow on my machine and i got the same error

### Expected Behavior

Able to redeem normally

### Steps To Reproduce

1. https://portalbridge.com/advanced-tools/
2. Select SUI as source chain
3. TXID 8Smwb3k7cBGwPhBfPif9AjSwgg6RPuk8no2x4VuW3R1u

**Comment by sebastianscatularo** [comment]
this Tx has been completed by a relayer https://wormholescan.io/#/tx/8Smwb3k7cBGwPhBfPif9AjSwgg6RPuk8no2x4VuW3R1u, closing the issue
