### ISSUE TITLE
[support] <Ticket 0038 SOL -> ETH, unable to redeem/resume, cannot estimate gas;>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain: SOL
- Source Chain Wallet: CisYKYSi58ZmQTtVnfpsddYrboLuVnbES8bBdPr2mQxu
- Target Chain: ETH
- Target Chain Wallet: 0x1bbDa612525d0361a0C46fc001830a6E0dDb7eAa
- Asset Type: wETH
- Tx: ZKeq7ULN8MB9sgX4jhCkHLsvfZGAQXF5a6GoGDauKKfMSHgqnxb5pbzQYTPnvvnZLU1udU9wJwxaxES1ip5u5Zy
https://wormholescan.io/#/tx/ZKeq7ULN8MB9sgX4jhCkHLsvfZGAQXF5a6GoGDauKKfMSHgqnxb5pbzQYTPnvvnZLU1udU9wJwxaxES1ip5u5Zy
```

### Current Behavior

unable to resume/redeem

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/dd15383b-ab93-446f-a1c6-9e44d43882e5)
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/07782ba2-466d-49f2-9bef-f5a257f88f37)

### Expected Behavior

Able to resume/redeem

### Steps To Reproduce

1. https://portalbridge.com/advanced-tools/
2. Select SOL as source
3. TXID: ZKeq7ULN8MB9sgX4jhCkHLsvfZGAQXF5a6GoGDauKKfMSHgqnxb5pbzQYTPnvvnZLU1udU9wJwxaxES1ip5u5Zy

**Comment by willis20188** [comment]
Another user faced the same issue  Ticket #0150
https://wormholescan.io/#/tx/5Cy6EdgkjvCtMHKbChNEqa7sSJhByP9pYiNAXUpPJ9CrPBkBxm6v3hn2oEmcH9CygiWX29xNiBDb3Sg29YEVFcFg

**Comment by sebastianscatularo** [comment]
both tx were an operations with a relay, that seems to have been addressed by a relayer 

<img width="819" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/336fe6c8-b274-445b-a568-1e38c0f8b4bf">

<img width="791" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/cd6de266-6cd6-4ea9-ac5b-4e433d804f07">
