### ISSUE TITLE
[support] cannot redeem nft on Polygon<Ticket 0140>

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Operation Details

```markdown
- Source Chain:base
- Source Chain Wallet:0xDb0BF5ed27346BBB235A2BB8763BF9425b6348CB
- Target Chain:polygon
- Target Chain Wallet:0xDb0BF5ed27346BBB235A2BB8763BF9425b6348CB
- Asset Type:nft
- Tx:
https://basescan.org/tx/0xfdf37a0591f0249386ee3946ba4fabebc61f24544105e3ba26ad540bdd693256
```

### Current Behavior

Error message : cannot estimate gas
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/0088b253-1f01-4644-85ee-b133fae3095b)

**Comment by sebastianscatularo** [comment]
@willis20188 this NFT has been transferred correctly, we've detected an issue at the UI that shows the NFT is still available to be redeemed when that is not the case.

this is the NFT at the target wallet https://polygonscan.com/token/0x0fae5477a3ae1d07f542a588ebc185c73a74fd34?a=105132673274799523554415412200893093322059529230079200670483040371509685942422

we are going to open another ticket to track the UI/UX issue
