### ISSUE TITLE
[support] unable to redeem Ethereum ->Inj <Ticket 0350>

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Operation Details

```markdown
- Source Chain:ETH
- Source Chain Wallet:0xf338ae28794bc7a79c94daaa8657aac3ca65768b
- Target Chain:INJ
- Target Chain Wallet:inj12g8922js8gdhherqers9ec0ega6nl2tq5q3p3g
- Asset Type:WETH
- Tx:https://etherscan.io/tx/0x550c97fd3e457460e5789f0413d315a4d486e938c44ee92b48033a3f9986f92f
```

### Current Behavior

Error message : The sequence number provided in the transaction is incorrect
![1](https://github.com/XLabs/portal-bridge-ui/assets/83527164/ef7d4742-01ec-41ab-ba0b-c29cfea3a45a)
![2](https://github.com/XLabs/portal-bridge-ui/assets/83527164/f122b64a-4a16-456e-9c2c-2ff9ab58c418)

**Comment by sebastianscatularo** [comment]
@willis20188 checking this issue, seems to be, the user has been able to redeem the tx

<img width="810" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/c9846563-14f7-4b47-9128-0c27d1a0654e">
