### ISSUE TITLE
[support] Ticket 0913 - Osmosis > Sol not yet received tokens 

### ISSUE THREAD

**Issue by sleepycorgi1** [XLabs/portal-bridge-ui#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Bridge Experience URL

-

### Operation Details

```markdown
Source chain : Osmosis 
Source Address: osmo1t8yjrr0egrdffad42yz6ka5vvne3lkt5gskjsy
Target chain : Solana
Target Address: B8tSuQUg3vq4D4wfFRjiRrvu5hQAykN1oarCNVr9K7NL
Source service: Portal Bridge 
Asset type: Token (0.57 SOL) 
Source Tx: 3C08A21F7AB38035987DB20E183226445F8BACB2903C98B85D7D5B38D6F85FEE

https://wormholescan.io/#/tx/3C08A21F7AB38035987DB20E183226445F8BACB2903C98B85D7D5B38D6F85FEE?view=overview
```

### Current Behavior

User did not receive funds on target chain + unable to redeem with advanced tools + resume workflow .

Upon four wallet approvals on Solana side, user has "unexpected error" 

### Expected Behavior

User should be able to redeem tokens after four wallet approvals on Solana side 

### Steps To Reproduce

1. Using resume transaction > Transaction cannot be found
2. Using advanced tools > paste in VAA > connect solana wallet > user approves four wallet approvals > "unexpected error" pop up occurs 

3.Force creating wallet also not working 

### Anything else?

<img width="438" alt="Screen Shot 2024-01-04 at 8 12 00 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/26aab864-583b-46dc-911e-8b417212efe0">
<img width="171" alt="Screen Shot 2024-01-04 at 8 12 32 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/93da2782-f31e-4aa9-871c-acebe1f934a6">
<img width="426" alt="Screen Shot 2024-01-04 at 8 13 48 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/ad2c584b-6834-4973-8732-36eb76a03221">

**Comment by sebastianscatularo** [comment]
currently, the RPC is not responding with the tx details, we need to dig deeper to understand what is going on, since this is a Gateway transfer though wormchain and IBC, this tx could not be redeemed using advanced-tools

**Comment by drisAloma** [comment]
Hello!
Please is there any update on this?
