### ISSUE TITLE
[support] Ticket 1100 - Op to injective unable to redeem 

### ISSUE THREAD

**Issue by sleepycorgi1** [XLabs/portal-bridge-ui#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Bridge Experience URL

-

### Operation Details

```markdown
Source Chain: OP
Source Chain Wallet: Metamask : 0x698A00C4546432b2ad17629Ee68b95783800321D
Target Chain: Injective
Target Chain Wallet: I tried both Keplr and Leap : inj1psey2xfrk33xt7umg6m9pafkd2e20uwqefg5ye
Asset Type: Weth token 
Tx: 0x174698626112a598df6e412c79e824cc2286e0783b78d30a378087815773a3e5
```

### Current Behavior

Unable to redeem when redeeming transaction . Error popup - "contract execution failed" 

### Expected Behavior

User should be able to redeem tokens 

### Steps To Reproduce

1. User does redeem workflow (select OP and paste in the transaction)
2. Click redeem
3. approve wallet approval
4. "Contract execution failed" popup 

### Anything else?

![Uploading Screen Shot 2024-01-04 at 8.21.05 pm.png…]()

**Comment by tonyjin** [comment]
@sleepycorgi1 screenshot doesn't load - can we please see the console errors? Thanks!

**Comment by yuli-ferna** [comment]
Trying to redeem I have this error:

![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/189c9c5e-0cf2-4bd6-90a5-e9d3f35a4937)
`rpc error: code = NotFound desc = account inj1xur6zq75t2jhq8449am93rxu4elytldjf75jnh not found: key not found`

@SamantaCasal could you try please?

**Comment by SamantaCasal** [comment]
Hi! I get this error trying to redeem the `tx: 0x174698626112a598df6e412c79e824cc2286e0783b78d30a378087815773a3e5`


https://github.com/XLabs/portal-bridge-ui/assets/69044575/e49bf526-0a1f-4fa2-9e72-0d9933b3a58c

**Comment by sleepycorgi1** [comment]
Closing this ticket as it is a duplicate of https://github.com/XLabs/portal-bridge-ui/issues/631
