### ISSUE TITLE
[support] Ticket 1500 - Osmosis > Solana not yet received funds 

### ISSUE THREAD

**Issue by sleepycorgi1** [XLabs/portal-bridge-ui#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain:Osmosis 
- Source Chain Wallet:
- Target Chain: Solana 
- Target Chain Wallet:
- Asset Type: Token 
- Tx:7C123789920C6E6BBF68C2646553CCF50F008A51F027605917F35ED9DBD81010
```

### Current Behavior

User is trying to resume transaction however it is not found . Also does not populate in wormholescan 

### Expected Behavior

User should be able to receive funds in Solana side 

### Steps To Reproduce

1. Resume transaction + paste in 7C123789920C6E6BBF68C2646553CCF50F008A51F027605917F35ED9DBD81010 , select osmosis

**Comment by yuli-ferna** [comment]
@sleepycorgi1  Could the user say other detail? Because I can't find this transaction id in the osmosis chain

**Comment by sleepycorgi1** [comment]
https://www.mintscan.io/osmosis/tx/7C123789920C6E6BBF68C2646553CCF50F008A51F027605917F35ED9DBD81010 (is this transaction correct?) thank you

**Comment by yuli-ferna** [comment]
Oh sorry about that, I see in another browser an error.We will work to see what the problem is

**Comment by sleepycorgi1** [comment]
hi @yuli-ferna was there any update?

**Comment by sebastianscatularo** [comment]
it is odd @sleepycorgi1, but, seems to be the tx is only available at mintscan, at other scanners/rpcs we are not seeing the TX, and that's why the user can not continue, also, seems to be, the guardians didn't see it, since we can not find a vaa emitted for this specific tx, we are still investigating this case
