### ISSUE TITLE
[bug] Terra Classic bridge be reopened, when? 

### ISSUE THREAD

**Issue by eliiik** [XLabs/portal-bridge-ui#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It has already been suspended for half a year. How is the repair going?

### Environment

```markdown
- OS:
- Wallet:
- Browser:
```

**Comment by sebastianscatularo** [comment]
we are re-opening it in this PR https://github.com/XLabs/portal-bridge-ui/pull/706
