### ISSUE TITLE
[support] unable to redeem Osmosis ->Moonbeam <Ticket 3338>

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain:Osmosis
- Source Chain Wallet:osmo13mfvtszt4ustt7ykf02r36nwezl8l66ruq0euv
- Target Chain:Moonbeam
- Target Chain Wallet:0x004731D68192f5154EAF4652C5fC69A7DDb5Ac24
- Asset Type:USDC
- Tx:https://www.mintscan.io/osmosis/tx/D82CFBEED0A1AFF2FA4BA4346EB927D795EE0497954BAC08F3D46E8A57DDDDAE
```

### Current Behavior

TX done about 2days ago
unable to redeem
Error message : Bridge transaction not found, check that you have the correct chain and transaction ID
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/efd332e3-0c1a-46d7-91c3-4e4d7e4221f0)
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/31d4a422-fb8b-46db-8c3a-41dcc47d4035)
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/2041a959-41a7-4bb3-b96a-35f294e6192e)

**Comment by willis20188** [comment]
Hello,
Any update on this？

**Comment by sleepycorgi1** [comment]
I think this has been resolved. please close this ticket.
