### ISSUE TITLE
[support] Cannot redeem transfer on Optimism<ticket 3322 & 3087>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain: Injective 
- Source Chain Wallet: Kepler 
- Target Chain: Optimism 
- Target Chain Wallet: Metamask 
- Asset Type: Token 
- Tx-1:https://explorer.injective.network/transaction/690df5727cdce1cd7ced215fb9351d011a44110dbe28a1ea3a939773de8049d8/
- Tx-2: https://explorer.injective.network/transaction/6fbcb2aeaa7800637bdae0b15929cc651b678ef3a26ac61a421d31a2a0ae570c/
```

### Current Behavior

It returns the error in the image immediately after clicking on the redeem button 
![screenshot_2024-01-09_224736-1](https://github.com/XLabs/portal-bridge-ui/assets/64994788/45be384d-10d6-4a77-8e7b-aeeb86a2f31e)

<img width="1512" alt="Screenshot_2024-01-07_at_14 49 15" src="https://github.com/XLabs/portal-bridge-ui/assets/64994788/f6cd06c6-7a1e-4e46-9a2e-4b88eb3dd872">

### Expected Behavior

A wallet notification pops up to approve the redeem transaction and complete the transfer.

### Steps To Reproduce

1. Go to https://portalbridge.com/advanced-tools/#/redeem
2. Choose Injective as source chain
3. Paste the transaction hash and click on recover
4. Connect optimism wallet on the next interface
5. Click on redeem.

### Anything else?

Trying to redeem the second transaction returns the error in the image after pasting in the transaction hash but with you pasting the VAA in the advanced section help to bypass the error and proceeds to the next interface.
<img width="596" alt="Screenshot_2024-01-10_at_03 16 48" src="https://github.com/XLabs/portal-bridge-ui/assets/64994788/7b77dbc3-e86f-47b8-9fed-8bb54261f86d">
<img width="756" alt="Screenshot_2024-01-10_at_03 17 23" src="https://github.com/XLabs/portal-bridge-ui/assets/64994788/a27eb27f-74e8-45f1-921e-37c9130e5cbf">

**Comment by Dahtank** [comment]
Ticket 3523
Similar issue
- Source Chain: INJ
- Source Wallet Address: inj1ghd753shjuwexxywmgs4xz7x2q732vcnxxynfn
- Target Chain: OP
- Target Wallet Address: 0xf296a916e1ba803ecb69db8b0ed15f7ce3ca8bd2
- Asset Type: USDbC
- Tx: 15c4d9a3fce04f6637f42671004dbb60358fb3606ab60bed3d352731c92ae85e
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/3a42579d-d217-454b-bdfa-363d40f82635)

**Comment by sebastianscatularo** [comment]
All the TX reported in this issue are completed from what Wormhole Scan reports:
- https://wormholescan.io/#/tx/690df5727cdce1cd7ced215fb9351d011a44110dbe28a1ea3a939773de8049d8
- https://wormholescan.io/#/tx/6fbcb2aeaa7800637bdae0b15929cc651b678ef3a26ac61a421d31a2a0ae570c
- https://wormholescan.io/#/tx/15c4d9a3fce04f6637f42671004dbb60358fb3606ab60bed3d352731c92ae85e
- https://wormholescan.io/#/tx/8b78d3d7da16bed0f78cf150699a7effe8e1dc700003a688aa41bd13d5fa7cd5
