### ISSUE TITLE
[support] <Ticket 4606 Osmo -> Aptos>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain: Osmosis
- Source Wallet Address: osmo12valq7maa8wjc9g576rwlu996tqsn9n9dlyqmr
- Target Chain: Aptos
- Target Wallet Address: 0x007da1bf43a3864a81bc488082432811992a6f0dffd3cd871635646beef5159a
- Asset Type: USDC
- Tx: B30A47CD2AB549556369CDD98E66EBD9E7EE92F5F3454EF36D6D9DF561E36369
```

### Current Behavior

Users wallet is 0x007da1bf43a3864a81bc488082432811992a6f0dffd3cd871635646beef5159a
but PortalBridge wants user to connect with wallet 0x7da1bf43a3864a81bc488082432811992a6f0dffd3cd871635646beef5159a

### Expected Behavior

User should be able to claim/redeem normally

### Steps To Reproduce

1. https://www.portalbridge.com
2. Resume TX
3. OSMO source chain
4. TXID B30A47CD2AB549556369CDD98E66EBD9E7EE92F5F3454EF36D6D9DF561E36369

### Anything else?

This issue has appeared before on Aptos chain before, the workaround is the use 
https://portalbridge.com/advanced-tools/#/redeem
but in this situation it doesn't work because Osmosis chain not supported there

**Comment by sebastianscatularo** [comment]
checking with the ops team, this is an issue at the chain level, that is out of our scope to be handled, it seems to be an IAVL issue, I go any new info, I'll share with you

**Comment by sebastianscatularo** [comment]
for the record, this seems to be the issue a node level:

```
InvalidArgument desc = failed to load state at height 6630456; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height
```

**Comment by drisAloma** [comment]
This was resolved by using the VAA to redeem the transfer directly on the advanced bridge page. 
We can close the ticket.
