### ISSUE TITLE
[feat] Re-enable ability to bridge native assets back into Terra Classic

### ISSUE THREAD

**Issue by tonyjin** [XLabs/portal-bridge-ui#689]
### Scenario

The Wormhole Foundation expects that the smart contracts for the Terra Classic token bridge will be upgraded on or before Jan 26th, 2024 to re-enable bridging of native assets back into Terra Classic.

Portal's Advanced Tools UI should remove the check that currently prevents a user from bridging $USTC and $LUNC back into Terra Classic and all associated messaging.

<img width="724" alt="Screenshot 2024-01-30 at 9 43 08 AM" src="https://github.com/XLabs/portal-bridge-ui/assets/689351/9215d97f-e9c1-4681-886b-86ec097ab30f">

Remove the "Transfers of native tokens to Terra Classic have been temporarily paused." warning and allow these transfers.

Contract address of Wormhole-wrapped LUNC on Eth: https://etherscan.io/token/0xbd31EA8212119f94A611FA969881CBa3EA06Fa3d

### Acceptance Criteria

- [] User with Wormhole-wrapped $USTC and $LUNC should be able to use Portal's Advanced Tools UI to bridge those assets back into Terra Classic

**Comment by tonyjin** [comment]
I see this warning in an older Portal commit (https://github.com/XLabs/portal-bridge-ui/blob/01dd6d01652e0895adace40fa7a084466234a812/src/config/transferRules.ts#L31), but can't find it on main

**Comment by sebastianscatularo** [comment]
advanced-tool is getting built from advanced-tools branch, there is a pending ticket to integrate as part of the main branch, was it this way to keep the work mean while we where doing the connect migration.

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you test it?

Steps to test it
- 1. go to advanced-tools
- 2. bridge from terra to some chain, like BSC or AVAX UST or LUNC
- 3. bridge the assets back

Expected result: 
- outgoing and incoming transfers should work.

**Comment by tonyjin** [comment]
I was able to reproduce Samanta's issue by trying:
1. Bridging LUNC from Terra Classic -> Avalanche and then trying to bridge that LUNC back to Avalanche (this didn't work - the "Next" button was disabled as shown above)
2. Select Ethereum and enter the wLUNC address `0xbd31EA8212119f94A611FA969881CBa3EA06Fa3d` in the token select menu. Note that you still see the "Transfers of native tokens to Terra Classic have been temporarily paused" warning

**Comment by sebastianscatularo** [comment]
yes, there is an issue with the environments that are not rendering the right build, we are working on it

**Comment by sebastianscatularo** [comment]
I was able to transfer back to terra classic LUNC from BNB, evidence below

redeem tx -> https://finder.terra.money/columbus-5/tx/CA7A2848BE3599801B59714E41389112259FA67ECAE2FFD7FF5BCA6631B549C0

https://github.com/XLabs/portal-bridge-ui/assets/1277510/f5666cc7-b909-4cb4-a2fd-0fdf4b853c36

**Comment by sebastianscatularo** [comment]
merged https://github.com/XLabs/portal-bridge-ui/pull/706
