### ISSUE TITLE
Connection support for Rabby Wallet 

### ISSUE THREAD

**Issue by PhuocHofu** [XLabs/portal-bridge-ui#696]
Please support EVM users connecting to PortalBridge using Rabby wallet https://rabby.io/ 
Rabby wallet currently has 300k users on Chrome store
a lot of people are using rabby and can't connect to PortalBridge/Wormhole

Thanks

**Comment by sebastianscatularo** [comment]
we are adding support as part of our next release, you will be able to use Rabby wallet soon :)
