### ISSUE TITLE
[bug] [Mainnet] Cannot connect using Wallet Connect

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Message `Uncaught (in promise) Error: To use QR modal, please install @walletconnect/modal package` is shown when user clicks on WalletConnect option

### Expected Behavior

WalletConnect QR code is opened

### Steps To Reproduce

1. Click on Connect Wallet
2. Search WalletConnect (Ethereum)
3. Click on it
4. Observe

### Environment

```markdown
- OS: macOS Ventura 13.0.1, 
- Wallet: None
- Browser: Chrome Version 120.0.6099.234
Tested from: 
- https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ - Tested NOK
- https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/# - Tested NOK
- https://wormhole-connect-mainnet.netlify.app/# - Tested OK
```

### Anything else?

Attachment:

https://github.com/XLabs/portal-bridge-ui/assets/91047061/db19ecd8-47da-483c-83b1-c0e23e3cb177

**Comment by AigaD** [comment]
Reproduced from: https://portalbridge.com/#
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/747
Attachment:

https://github.com/XLabs/portal-bridge-ui/assets/91047061/169d71d7-5e18-4197-b2d4-03200bc18a49

**Comment by tsadovska** [comment]
Issue is no longer reproducible on:
* https://portalbridge.com/ [Mainnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]
* https://wormhole-connect.netlify.app/ [Testnet].

Preview pages can’t be found:
* https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet]
* https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/ [Testnet]

Ticket can be closed.

**Comment by sebastianscatularo** [comment]
thanks, closing it
