### ISSUE TITLE
[support] Cannot Resume/Redeem transfer from Base (CCTP transfer) <ticket-5910>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain:Base
- Source Chain Wallet: Metamask 
- Target Chain: Optimism 
- Target Chain Wallet: Metamask 
- Asset Type: Token 
- Tx: https://basescan.org/tx/0x343b6e98f337405218789ef0101ad95f161709f3ec1b1c18fd3b955a4b869e92
```

### Current Behavior

![Screenshot_2024-01-28-17-32-09-98_4d38fce200f96aeac5e860e739312e76](https://github.com/XLabs/portal-bridge-ui/assets/64994788/581a1113-f00e-4db1-907e-0e8288bce6c3)
![Screenshot_2024-01-28-17-35-39-87_08800057d42e3b72e31ae4fd4c41ba57](https://github.com/XLabs/portal-bridge-ui/assets/64994788/b2963a4f-358b-4c96-ac95-9ae86569fb1c)

### Expected Behavior

Returns transaction and claim/recover button 

### Steps To Reproduce

1. Go to https://portalbridge.com 
2. click on the "resume transaction" option on the lower left corner of the page.
3. Choose Base as Network
4. Paste the transaction hash 

### Anything else?

Here is the link to slack discussion/troubleshooting on the issue 
https://wormholefoundation.slack.com/archives/C05KPN51PBK/p1706462248683889?thread_ts=1706462248.683889&cid=C05KPN51PBK

**Comment by drisAloma** [comment]
These users are also facing the same issue.

Ticket-5909
https://basescan.org/tx/0x9d6e83c3ee345e27d5efe1a1436c8f2dd6f5e370c4c14dee0a2e1893b0f2a39d

Ticket-5900: 
https://basescan.org/tx/0xe3f2d0d88379a8247e9ab92d71dc2db68cb1d6b95806d420671b032b448144f6

Ticket-5921:
https://basescan.org/tx/0x8c988fab4efb1202adbf4924985f1fd4aa1caa845ca5c7e90203597cb7393826

**Comment by willis20188** [comment]
Tikcet 5987
https://basescan.org/tx/0xe9dceab4a93c4a71fbfc2b21e59a23205368a00af6f04a05ca538c3296054c93
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/0a636cef-d8c3-45f9-8833-01bcd861798d)

**Comment by yuli-ferna** [comment]
@drisAloma @willis20188 I was able to resume this txs, and all of them are complete :)
![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/292bf8ac-bc2b-4c36-86de-b6c112516e37)

So for now I will close this issue.

**Comment by drisAloma** [comment]
Yeah, they are all good, thank you!
