### ISSUE TITLE
[bug] Cannot connect Torus wallet

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot connect Torus wallet. Torus window does not appear. 

Errors:

`Refused to load the stylesheet 'https://solana.tor.us/css/widget.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.`

`Refused to frame 'https://solana.tor.us/' because it violates the following Content Security Policy directive: "frame-src https://verify.walletconnect.org/ https://verify.walletconnect.com/ https://connect.solflare.com/ https://www.youtube.com".`

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://solana.tor.us') does not match the recipient window's origin ('null').`

![Screenshot 2024-01-30 at 10 57 23](https://github.com/XLabs/portal-bridge-ui/assets/10746654/6049539e-2c29-4b01-9263-37e970f2377c)

### Expected Behavior

User can connect Torus wallet. 

### Steps To Reproduce

1. Click "Connect wallet" button
2. Select "Torus" option

### Environment

```markdown
- OS: macOS Sonoma 14.2.1 
- Wallet: Torus
- Browser: Google Chrome Version 121.0.6167.85 (Official Build) (arm64)
```

### Anything else?

Torus window appears on https://wormhole-connect-mainnet.netlify.app/, but loading does not finish. Ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1192

**Comment by tsadovska** [comment]
Issue is reproducible on https://portalbridge.com/ [Mainnet] and https://preview.portalbridge.com/ [Mainnet].

![Screenshot 2024-03-08 at 15 50 38](https://github.com/XLabs/portal-bridge-ui/assets/10746654/76023d41-07a2-4774-bd88-564f35f6b178)

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/b05f4e9322/ [Mainnet].

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet].

**Comment by xavierlepretre** [comment]
Still happening.
