### ISSUE TITLE
Claimed 6192 - NFT CAN'T BE REDEEM

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
Source chain : solana
Wallet Source chain : Dg7U95gSF4jMosMX2BLGmMiu6pWEgYnBqHMmCEfcbcWV
Target chain : aptos
Wallet target chain : 0x8cef0430cefe1cd1f86a3940ee268aa92f5b1f5999ab8c0540d1b8724ed53b41
Tx:  5iExjto74ozDiHbLNT9qweGdmPi91NJUeEJhfr2kJ9ACbyd7rXdsxJDm2MzcXFS1mAeQ8xJW3fUSFhwosbategRA
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/73ddf00a-0554-4041-b3c4-41ce67f19405)
can't redeem the NFT on Aptos side

**Comment by yuli-ferna** [comment]
@dry2022 The user needs to select NFT type first, please, could you ask him/her?
![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/0b667e83-c7df-4d6d-bf7d-406718bda4fb)

**Comment by sebastianscatularo** [comment]
closing it since we do not get an answer on this
