### ISSUE TITLE
TICKET 6481 - CAN'T BRIDGE FROM BASE (only from base the user have this issue 

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
Source chain :Base
Wallet Source chain : Metamask
Target chain : Polygon
Wallet target chain : Metamask
there is no tx, because I can't create tx
```

### Current Behavior

https://cdn.discordapp.com/attachments/1202610907566571581/1202974366221205574/image.png?ex=65cf682f&is=65bcf32f&hm=631821df7e2544dbd54c89a3893609ee0b950b62dd946b93e821cc6f7ef954bf&
https://cdn.discordapp.com/attachments/1202610907566571581/1202977187737894953/image.png?ex=65cf6acf&is=65bcf5cf&hm=e16d8906390cb7b716ba5f4699118b3da3606bbe953d9d91f4bc829f0c7cefcb&
https://cdn.discordapp.com/attachments/1202610907566571581/1202977531993788486/image.png?ex=65cf6b21&is=65bcf621&hm=e7ba3d32a9bcd995dd89768c4bf7f13250bce2530f6ea2336c6eb5d7c59dc7c5&

### Expected Behavior

trying to send from BASE to POLYGON

**Comment by yuli-ferna** [comment]
@dry2022 I wasn't able to see the images in current behavior, could you post it again?

**Comment by sebastianscatularo** [comment]
@dry2022 we are going to close it due the lack of answer, seems it is not so urgent at this moment, please re open it if you disagree.
