### ISSUE TITLE
Cant redeem USDC Sol bridge to Polygon

### ISSUE THREAD

**Issue by dezinhooo** [XLabs/portal-bridge-ui#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain:Solana
- Source Chain Wallet: 9irE4kHMHRbFtV4LbEQUvWgzXPtGdPuLFrvXMq7rv7MT
- Target Chain: Polygon
- Target Chain Wallet: 0x15d6e66Ef3738a9F2A2704783789e47431D80D70
- Asset Type:Token
- Tx: https://explorer.solana.com/tx/39cLpeKoma4L3hPN6auWLKsKJqZ4ycGCyFZAKMvNY9K91zdqoyd7V5VBz8NcqUVb7jadsFjyxgK3TSwhN3WZ3gcn
```

### Current Behavior

I tried to bridge USDC Solana to Polygon, The transaction was successful on the Solana transaction, but it failed bridging. Now I canta redeem, I get an error: Error: requested VAA not found in store.

**Comment by sebastianscatularo** [comment]
we have experiencing delays on tx coming out from Solana due the recent outage, you could check [here](https://wormhole-foundation.github.io/wormhole-dashboard/#/) for the solana status at wormhole. Once we gets recovered, you should be able to resume you tx without issues.

**Comment by sebastianscatularo** [comment]
since your tx seems to be completed, we will close this ticket 

https://wormholescan.io/#/tx/39cLpeKoma4L3hPN6auWLKsKJqZ4ycGCyFZAKMvNY9K91zdqoyd7V5VBz8NcqUVb7jadsFjyxgK3TSwhN3WZ3gcn
