### ISSUE TITLE
[support] Pending transfer to EVMOS <ticket-6834>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain:BNB
- Source Chain Wallet: METAMASK 
- Target Chain: EVMOS
- Target Chain Wallet: KEPLER 
- Asset Type: Token 
- Tx:https://bscscan.com/tx/0x4ac1292707d3b9a4f86fd407346c5cc35f32040d443935b5cd3851626975c7bd
```

### Current Behavior

loads infinitely on an attempt to resume the transfer as shown in the image. 

![screenshot_2024-02-07_at_23 13 22-1](https://github.com/XLabs/portal-bridge-ui/assets/64994788/f2dc79f3-48c3-44b2-973a-356bb3ffbf22)

### Expected Behavior

Manual claim or relayed successfully 

### Steps To Reproduce

1. Go to https://portalbridge.com/#/transfer
2. Click on the resume button at the lower left corner
3. Choose BNB as network and paste in the transaction hash.

**Comment by drisAloma** [comment]
Ticket-6664 has the same issue 
Source chain: Arbitrium
Target chain: Evmos
Tx: https://arbiscan.io/tx/0x6e735b7a8175e2f5efc1593b310fc873722e684d6cd131a7086119065824de5f

**Comment by yuli-ferna** [comment]
@drisAloma I think the issue is solved, and both txs are completed :)

![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/6ce0d1d7-39b6-448c-a7dd-144ba7aa6a26)
![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/12e0e247-8ec6-4f78-b415-058e658c6e06)

**Comment by drisAloma** [comment]
Yeah, both are, thank you!
