### ISSUE TITLE
[bug] Transaction timeout shown for transaction from Solana

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some of the transactions from Solana fails with reason `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed.`

### Expected Behavior

Every transaction is started and completed

### Steps To Reproduce

Send 0.03 SOL from Solana to Moonbeam
Select automatic transaction in Route section
Add some Native gas
Click on Approve and proceed with transaction
Observe if transaction is completed

### Environment

```markdown
- OS:macOS Ventura 13.0.1
- Wallet: Solflare, Metamask
- Browser:Chrome Version 121.0.6167.85
- Tested from: https://preview.portalbridge.com/749d45da9e/#
```

### Anything else?

First transaction failed with transaction timeout, second transaction was completed
Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/732

![Screenshot 2024-02-16 at 10 05 04](https://github.com/XLabs/portal-bridge-ui/assets/91047061/4d885a97-e5c2-437e-857b-33d73b6b1d02)

https://github.com/XLabs/portal-bridge-ui/assets/91047061/c9365e90-5d40-4a2a-b7e3-810222bac251

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/749d45da9e/
Issue is still reproducible. Transaction timeout shown for transaction Solana (Coin98) to BSC (Metamask)
Attachment:

![Screenshot 2024-02-21 at 17 37 02](https://github.com/XLabs/portal-bridge-ui/assets/91047061/b2185814-34c7-49ae-a41d-db3b4ff37970)

**Comment by tsadovska** [comment]
Checked on https://portalbridge.com/ [Mainnet]. 

Scenarios - Tested OK:
* Send SOL from Solana (Phantom) to Avalanche (MetaMask) with manual route: [Solana explorer](https://explorer.solana.com/tx/4D7anDviWnB6oyQi3kmNapUYd64MTNSfjdJWp56xjYXNkPgRPfEFWSqYVUJssSf5iK9LCLj4oNuabnE2eLyWydvk), [Avascan](https://avascan.info/blockchain/c/tx/0x8dc85434326cb79d4754c7dd4954dfbfa43ee52b107d5677d90816e8e69fd9fa).
* Send SOL from Solana (Phantom) to Moonbeam (MetaMask) with manual route: [Solana explorer](https://explorer.solana.com/tx/5mBQTCqTxuAmgpV4pTra7WYUUWtx2pfVDPQsErn3hiDZAt99X7SUGP354psyFukoBdgxoArQ2Kd17w9kmuh18HfK), [Moonscan](https://moonscan.io/tx/0x378cf31438721ff4299dca91cae74d86f0ada033dbe1fbb57b7b2eab5ebdfd3a).
* Send SOL from Solana (Phantom) to Moonbeam (MetaMask) with automatic deposit route: [Solana Explorer](https://explorer.solana.com/tx/4G2U6eFu1S8P3dGm1RWzRcz2zjNhPZcnM7FMgfPrHGexT59sw33UUMdDR6969kcuNpYPXpNnstJz15tdaykaXaw9), [Moonscan](https://moonscan.io/tx/0xca7f437b65c956d34bc76f34174f66c605f80c9a19b947b84714211c295da114).

Scenario - Tested NOK:
* Send SOL from Solana (Coin98) to BSC (MetaMask). Transaction fails with with "WalletSendTransactionError" after clicking on "Approve and proceed with transaction" button. Please view this [link](https://github.com/wormhole-foundation/wormhole-connect/issues/1552) to view the issue. 

Ticket can be closed.
