### ISSUE TITLE
[support] <Ticket 7568 Polygon -> Arbitrum, cannot redeem>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
Source Chain: Polygon
Source Wallet Address: 0xd73148ae535250499d40a0167ebd48b3ddbd4f14
Target Chain: Arbitrum
Target Wallet Address: 0xd73148ae535250499d40a0167ebd48b3ddbd4f14
Asset Type: USDC
Tx:0xb32a404673a39bbe3d3705b2aadce868a004ccad0bcdadf58d3524c06d00c0fe


Source Chain: Polygon
Source Wallet Address: 0x09bb57b0fa8d6959017d5480bbcc1f84921fa043
Target Chain: Arbitrum
Target Wallet Address: 0x09bb57b0fa8d6959017d5480bbcc1f84921fa043
Asset Type: USDC
Tx:0x1bc597df3ee45a4b5d24871865913af8ae5d0c81acb66992f5ab9ffc07dd8695


Source Chain: Polygon
Source Wallet Address: 0x3098f588a3df52302e3f0da9125751c294bf2e99
Target Chain: Arbitrum
Target Wallet Address: 0x3098f588a3df52302e3f0da9125751c294bf2e99
Asset Type: USDC
Tx:0x7654df0e37a811b0115243685cf20f334329feb7992a7615652acbf68ece98a0
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/65b7989d-ccda-4c4b-88a5-20c271cf288e)
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/157b622f-41bb-44d0-b04d-0fcb6864e5c6)

Claiming tthese 3 TXs. they are stuck loading before user can connect ARB walle(tested on my own smartphone and desktop with same results

### Expected Behavior

Able to claim/redeem normally

### Steps To Reproduce

1. Go to https://www.portalbridge.com
2. Scroll down :arrow_down: and Click “**Resume Transaction**”
3. Select Source Chain: Polygom
4. Enter Source TXID: 0xb32a404673a39bbe3d3705b2aadce868a004ccad0bcdadf58d3524c06d00c0fe
or
0x1bc597df3ee45a4b5d24871865913af8ae5d0c81acb66992f5ab9ffc07dd8695
or
0x7654df0e37a811b0115243685cf20f334329feb7992a7615652acbf68ece98a0

### Anything else?

Could this be a relayer issue from ARB in Jan 2024? The TXs are about 39+ days old

**Comment by sebastianscatularo** [comment]
@Dahtank we are reviewing them, since are TX we relay, we expect them to be redeemed automatically once the issue, if exist, go resolve. Our apologies for the inconvenience.

**Comment by sebastianscatularo** [comment]
@Dahtank all tx should be good now, relayer team was able to manage it, this VAA was missed to be proceed since a Re Organization at Polygon, it is not something common, so, we do not expect it to happen again. 

thanks @solanoepalacio

**Comment by solanoepalacio** [comment]
Hey there,
This transactions seem to have been affected by re-org.
Automatically detecting when a relay is affected by a re-org is currently been tested on testnet and will likely be deployed to mainnet soon.
We have manually re-processed the mentioned transactions. These are the txs on arbitrum:
```
Source: 0xb32a404673a39bbe3d3705b2aadce868a004ccad0bcdadf58d3524c06d00c0fe
Target: 0xec36be5bf9c7d53d6c889512742effda8402556d1b552a2bdd458ac423703cce

Source: 0x1bc597df3ee45a4b5d24871865913af8ae5d0c81acb66992f5ab9ffc07dd8695
Target: 0x4fa2e96d005ddd14e1ffcee8a72009b7609cd983d93a4e4f4bd9b3580aaedaa5

Source: 0x7654df0e37a811b0115243685cf20f334329feb7992a7615652acbf68ece98a0
Target: 0x37e98efb10c9b025ba7d94da09c3be410441dcd11ce410a2e188c722d8883889
```

**Comment by Dahtank** [comment]
Great! Thank you guys! Closing this ticket
