### ISSUE TITLE
[bug] Claiming on Solana fails with "Cannot read stream: RpcTransport has not been started" error

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error appears after clicking on "Claim" button:

```
GOT ERROR Error: Cannot read stream: RpcTransport has not been started
    at ri.<anonymous> (<anonymous>:3:210988)
    at Generator.next (<anonymous>)
    at <anonymous>:1:1598
    at new Promise (<anonymous>)
    at Fe (<anonymous>:1:1418)
    at ri.send (<anonymous>:3:210941)
    at oi.<anonymous> (<anonymous>:3:214822)
    at Generator.next (<anonymous>)
    at <anonymous>:1:1598
    at new Promise (<anonymous>)
```

### Expected Behavior

Transaction proceeds without errors. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/7246284e5d/ [Mainnet]
2. Prepare to send 0.0001 AVAX from Avalanche (MetaMask) to Solana (Phantom)
3. Click "Approve and proceed with transaction" button
4. Click on "Claim" button

### Environment

```markdown
- OS: macOS Sonoma 14.2.1
- Wallet: MetaMask, Phantom
- Browser: Google Chrome
```

### Anything else?

* Send from tx: [Arbitrum Explorer](https://arbiscan.io/tx/0x40dc1864f15a668768e82197b6e08fd1aeae8ca3b7317bd4dc6d2788ec75d27a)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x40dc1864f15a668768e82197b6e08fd1aeae8ca3b7317bd4dc6d2788ec75d27a)

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/bedede3a-a3fd-4821-8c25-6431fd2c6c84)

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/
Transaction AVAX from [Avalanche](https://avascan.info/blockchain/c/tx/0x1046a3e5a0868d53a47f8405e60d78dd62b4391677d6abf7b1afb5dcdc01b075) (Metamask) to [Solana](https://explorer.solana.com/tx/2eRCg8DVbA9JFoSMEF8Q2TrWpqTuKdxtJhzbuf1o2pgSaBnUKsB7MkkS1QKgS74j4skrnP2Ycg2oDf74GQRuNWhW) (Phantom) tested OK.
Closing the ticket.
Attachment:


![Screenshot 2024-03-05 at 15 40 51](https://github.com/XLabs/portal-bridge-ui/assets/91047061/e1c8efb9-abfe-4a5e-9886-35a0a55fd276)
