### ISSUE TITLE
[support] <Ticket 7858 Polygon -> ETH(Luna tokens right after the Luna crash)>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Operation Details

```markdown
Source chain: Polygon
Source wallet: 0xdF59c590d7A328CA05f7C0A300a08f589EfE9728
Target chain: Ethereum 
Target wallet: 0xdF59c590d7A328CA05f7C0A300a08f589EfE9728
Asset type: LUNA(Wormhole)(LUNA)
Tx: 0x0d5707a9cbd1261a896431d2fed080e528ccffc7f5f97fe9d325cbc7871d0251

https://wormholescan.io/#/tx/0x0d5707a9cbd1261a896431d2fed080e528ccffc7f5f97fe9d325cbc7871d0251?view=overview

https://wormhole.com/explorer?txId=0x0d5707a9cbd1261a896431d2fed080e528ccffc7f5f97fe9d325cbc7871d0251
```

### Current Behavior

No VAA for this TX

### Expected Behavior

VAA to be generated and user able to redeem

### Steps To Reproduce

https://portalbridge.com/advanced-tools/#/redeem
Cannot redeem because there is no VAA

### Anything else?

This is right after Luna token/chain crashed, not sure if it's even worth redeeming or if the assets were frozen because it was during this period? Regardless, should the tx still be processed?

**Comment by sebastianscatularo** [comment]
@Dahtank this vaa has an outdated guardian index set, it needs to be resigned with the new guardian set, I'll ask folks to do it and I'll share the result here

current vaa


```base64
AQAAAAINAObzD/CPIYFZMN8sXMqlxesm0KhJbyzX3YjeC8dSjWpqSmVxeD8agqWi+ynMMueWyDvmMPknFrBwFVDEeF4sw8ABAVVqvju3VO7zJIj0kKiy8IO8N2GXPuLImJ6gh3dLm2JnETK0t4W5+2NKsbnVB+qF6d+4tTzIMntBzMVYiYUoYesBAtiKCYEJezXfn60V3cGXUU4Oxbsy4YMz1GyLgqCLq0TRMUnx09m0kdrrdOn8ajmwMgfDEeaV0awFQMRLmytp1aQAA7z7aE/wcDXEDKUzuTbIoGiCY0HnxUXojxQXns1jph3rEa7J2ufB5x9Wn4RC7PZ2rLRjSgFARLUVFEpqh5SGMc4BBOhDtsbzKgZumClHM0UCwHB4wESNNHOuenL4oP5fNLhaUGdmRx3dtglpbd1Xs+2+j6x1dPDqEA+uzc/2fnp03ewABZQlLnfM/BZQ+UZMDlPOE8A1oRCeWi8GZ39jU/Z4Zn5oDnQul8rDoN6A03UMf3wvQypUO55y+xd3QvpMOC+2f+4BBli01jPcp/lZ3K6gYnUI2KA4GVdVoNSnWkdSzTKcL1OERuCZ8BK1lanBKeheUwYSz3hHfrTZAvj7DSC08dyKUvkBB2VPMBShiBkaz4IcPgOsc5RIdz+5M6LMdDLg3I22doahP1l/H5DDHRC/GaHZfUv1QCU25o79ZJYGSwp/w16BInQADHSmW8tDb0h31MBOiX1rL/MPU+XmrfwlYq52I4Sig9IfN68QTRD3cDl7/kt93Scxts+4rnnknUYOP1fob3GX/BgBDXGSBssaBu9+1+HotXYoKiOwqPVSRVnzvKKGuxdDV4mHHqyf4bFrIDbZBnPMYDY83qVlflCKgv/YtSFxA3VVVRQADnU+y5INqjK+YpXukRtFRiyDFZ2cXVm/8H1N3EVNw4FcHQJSFJPWGuEa0zeX0Ti9C/3WkzWevGgFvsGvzmyBr+YAEI5wdlW5vgW/176UCNrjSWl3HFuSHVzZELjMtgjnqqjGPXPRsn/ZGYasbdHvs7j1wsboTAa/JUGB29N3MIRjDB8AERPo8A8izl+t49Mt5E0OnOg6Pvm2DuKDQLjHRvWz/n/3Yg8uW4HmsIngCByQdRLdaorvIIanzplTIlGOvaVK15gAYnwVGmciAAAABQAAAAAAAAAAAAAAAFpYUFqW0dv435HLIbVEGfw26T/eAAAAAAAAtwoPAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC43WZAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdWx1bmEAAwAAAAAAAAAAAAAAAN9ZxZDXoyjKBffAowCgj1ie/pcoAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==```

**Comment by sebastianscatularo** [comment]
@Dahtank here is a valid VAA

```hex
01000000030d00e6f30ff08f21815930df2c5ccaa5c5eb26d0a8496f2cd7dd88de0bc7528d6a6a4a6571783f1a82a5a2fb29cc32e796c83be630f92716b0701550c4785e2cc3c00101556abe3bb754eef32488f490a8b2f083bc3761973ee2c8989ea087774b9b62671132b4b785b9fb634ab1b9d507ea85e9dfb8b53cc8327b41ccc55889852861eb0102d88a0981097b35df9fad15ddc197514e0ec5bb32e18333d46c8b82a08bab44d13149f1d3d9b491daeb74e9fc6a39b03207c311e695d1ac0540c44b9b2b69d5a40003bcfb684ff07035c40ca533b936c8a068826341e7c545e88f14179ecd63a61deb11aec9dae7c1e71f569f8442ecf676acb4634a014044b515144a6a87948631ce0104e843b6c6f32a066e982947334502c07078c0448d3473ae7a72f8a0fe5f34b85a506766471dddb609696ddd57b3edbe8fac7574f0ea100faecdcff67e7a74ddec000594252e77ccfc1650f9464c0e53ce13c035a1109e5a2f06677f6353f678667e680e742e97cac3a0de80d3750c7f7c2f432a543b9e72fb177742fa4c382fb67fee010658b4d633dca7f959dcaea0627508d8a038195755a0d4a75a4752cd329c2f538446e099f012b595a9c129e85e530612cf78477eb4d902f8fb0d20b4f1dc8a52f9010799cc07ec77940a7de3a62158e1f635a8231c5425827e441e45244a89840cf7a16af336f7f59bb0debf2e5b98c3456b3104a0090731a6b8395ae190d4fb68d404010c74a65bcb436f4877d4c04e897d6b2ff30f53e5e6adfc2562ae762384a283d21f37af104d10f770397bfe4b7ddd2731b6cfb8ae79e49d460e3f57e86f7197fc18010d719206cb1a06ef7ed7e1e8b576282a23b0a8f5524559f3bca286bb17435789871eac9fe1b16b2036d90673cc60363cdea5657e508a82ffd8b521710375555514000e753ecb920daa32be6295ee911b45462c83159d9c5d59bff07d4ddc454dc3815c1d02521493d61ae11ad33797d138bd0bfdd693359ebc6805bec1afce6c81afe600108e707655b9be05bfd7be9408dae34969771c5b921d5cd910b8ccb608e7aaa8c63d73d1b27fd91986ac6dd1efb3b8f5c2c6e84c06bf254181dbd3773084630c1f001113e8f00f22ce5fade3d32de44d0e9ce83a3ef9b60ee28340b8c746f5b3fe7ff7620f2e5b81e6b089e0081c907512dd6a8aef2086a7ce995322518ebda54ad79800627c151a6722000000050000000000000000000000005a58505a96d1dbf8df91cb21b54419fc36e93fde000000000000b70a0f010000000000000000000000000000000000000000000000000000000002e37599010000000000000000000000000000000000000000000000000000756c756e610003000000000000000000000000df59c590d7a328ca05f7c0a300a08f589efe972800020000000000000000000000000000000000000000000000000000000000000000
```

https://portalbridge.com/advanced-tools/#/redeem?vaa=01000000030d00e6f30ff08f21815930df2c5ccaa5c5eb26d0a8496f2cd7dd88de0bc7528d6a6a4a6571783f1a82a5a2fb29cc32e796c83be630f92716b0701550c4785e2cc3c00101556abe3bb754eef32488f490a8b2f083bc3761973ee2c8989ea087774b9b62671132b4b785b9fb634ab1b9d507ea85e9dfb8b53cc8327b41ccc55889852861eb0102d88a0981097b35df9fad15ddc197514e0ec5bb32e18333d46c8b82a08bab44d13149f1d3d9b491daeb74e9fc6a39b03207c311e695d1ac0540c44b9b2b69d5a40003bcfb684ff07035c40ca533b936c8a068826341e7c545e88f14179ecd63a61deb11aec9dae7c1e71f569f8442ecf676acb4634a014044b515144a6a87948631ce0104e843b6c6f32a066e982947334502c07078c0448d3473ae7a72f8a0fe5f34b85a506766471dddb609696ddd57b3edbe8fac7574f0ea100faecdcff67e7a74ddec000594252e77ccfc1650f9464c0e53ce13c035a1109e5a2f06677f6353f678667e680e742e97cac3a0de80d3750c7f7c2f432a543b9e72fb177742fa4c382fb67fee010658b4d633dca7f959dcaea0627508d8a038195755a0d4a75a4752cd329c2f538446e099f012b595a9c129e85e530612cf78477eb4d902f8fb0d20b4f1dc8a52f9010799cc07ec77940a7de3a62158e1f635a8231c5425827e441e45244a89840cf7a16af336f7f59bb0debf2e5b98c3456b3104a0090731a6b8395ae190d4fb68d404010c74a65bcb436f4877d4c04e897d6b2ff30f53e5e6adfc2562ae762384a283d21f37af104d10f770397bfe4b7ddd2731b6cfb8ae79e49d460e3f57e86f7197fc18010d719206cb1a06ef7ed7e1e8b576282a23b0a8f5524559f3bca286bb17435789871eac9fe1b16b2036d90673cc60363cdea5657e508a82ffd8b521710375555514000e753ecb920daa32be6295ee911b45462c83159d9c5d59bff07d4ddc454dc3815c1d02521493d61ae11ad33797d138bd0bfdd693359ebc6805bec1afce6c81afe600108e707655b9be05bfd7be9408dae34969771c5b921d5cd910b8ccb608e7aaa8c63d73d1b27fd91986ac6dd1efb3b8f5c2c6e84c06bf254181dbd3773084630c1f001113e8f00f22ce5fade3d32de44d0e9ce83a3ef9b60ee28340b8c746f5b3fe7ff7620f2e5b81e6b089e0081c907512dd6a8aef2086a7ce995322518ebda54ad79800627c151a6722000000050000000000000000000000005a58505a96d1dbf8df91cb21b54419fc36e93fde000000000000b70a0f010000000000000000000000000000000000000000000000000000000002e37599010000000000000000000000000000000000000000000000000000756c756e610003000000000000000000000000df59c590d7a328ca05f7c0a300a08f589efe972800020000000000000000000000000000000000000000000000000000000000000000

that was validated here

<img width="1439" alt="image" src="https://github.com/XLabs/portal-bridge-ui/assets/1277510/7e1eb99d-93c6-42d2-ba74-197b3b41e683">

**Comment by Dahtank** [comment]
Thank you
