### ISSUE TITLE
[support] <Ticket 7982 Polygon -> Aptos, unable to redeem>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
Source Chain: Polygon
Source Wallet Address: 0xb20dfee23918848faaa8eac952bf80a7454621d3
Target Chain: Aptos
Target Wallet Address: 0x23d4c13e7d196350b3a92c1f1d333219e785e61c9f7e9abc3309b903f5de8601
Asset Type: Token (WETH)
Tx: 0x46aa1e170c6683e5bc52094598888d30951da0e344c67b3d27b99e61ed1bf7fe
```

### Current Behavior

claim/redeem with Petra, Nightly and Martian, None are working
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/fa86596e-3a69-4bfa-b74c-ac43ac9eadef)

### Expected Behavior

Able to claim/redeem normally

### Steps To Reproduce

**1.** Go to https://www.portalbridge.com
**2.** Scroll down :arrow_down: and Click “**Resume Transaction**”
**3.** Select Source Chain: Polygon
**4.** Enter Source TXID: 0x46aa1e170c6683e5bc52094598888d30951da0e344c67b3d27b99e61ed1bf7fe

**Comment by yuli-ferna** [comment]
@Dahtank It seems the tx is completed: https://wormholescan.io/#/tx/0x46aa1e170c6683e5bc52094598888d30951da0e344c67b3d27b99e61ed1bf7fe
![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/c1742f13-4b91-4ac7-95d3-7f177c60ad4f)

For now I will close this issue.
