### ISSUE TITLE
[bug] Color palette on v0.2.12-Pc91e899a68 build does not match color palette on v0.2.12-5b60745b9f build

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Color palette on v0.2.12-Pc91e899a68 build does not match color palette on v0.2.12-5b60745b9f.

### Expected Behavior

Color palette on v0.2.12-Pc91e899a68 build is the same as on v0.2.12-5b60745b9f.

### Steps To Reproduce

Compare Assets list:
1. Select Ethereum network
2. Connect MetaMask wallet
3. Compare Assets list

Compare Colors in Route section:
1. Prepare to send 0.001 ETH from Ethereum (MetaMask) to Fantom (MetaMask)
2. Compare colors in Route section

### Environment

```markdown
- OS: macOS 14.2.1 (23C71)
- Wallet: MetaMask 
- Browser: Version 122.0.6261.112 (Official Build) (arm64)
```

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/7aa07e0b-b9b2-4bf6-a376-a67b3ede0cf8)

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/099dc294-9a52-4278-ba12-d25cf6093294)

![Screenshot 2024-03-08 at 09 39 47](https://github.com/XLabs/portal-bridge-ui/assets/10746654/2ac3785d-7b13-4c72-a476-68ac4c480e47)

**Comment by AigaD** [comment]
Tested from: https://preview.portalbridge.com/#
Add <suggested token>  to your wallet design is shown differently for some assets. For some the icon has the correct Asset icon colour, but for some all the text and icon are shown in blue font.

Attachment:
![Screenshot 2024-03-11 at 12 07 28](https://github.com/XLabs/portal-bridge-ui/assets/91047061/f2c2862e-4a46-495a-9b88-df1b457b4707)

![Screenshot 2024-03-11 at 11 50 04](https://github.com/XLabs/portal-bridge-ui/assets/91047061/bb16f732-e69c-4381-9513-23f1ef3fd946)

**Comment by artursapek** [comment]
yeah I probably caused this in https://github.com/wormhole-foundation/wormhole-connect/pull/1698

**Comment by artursapek** [comment]
solved in https://github.com/wormhole-foundation/wormhole-connect/pull/1698/commits/b442b3a20aa6868659cc04269eddc4a6ea127514

**Comment by AigaD** [comment]
Tested from: https://portalbridge.com/ and https://preview.portalbridge.com/b05f4e9322/#
Colour contrast for warning messages "Wallet disconnected, please connect a supported wallet" and "Select an asset" are different
Attachment:

![Screenshot 2024-03-12 at 13 46 43](https://github.com/XLabs/portal-bridge-ui/assets/91047061/9c87458c-b4d8-4cf7-b05f-28b3cf87fce0)

![Screenshot 2024-03-12 at 13 43 58](https://github.com/XLabs/portal-bridge-ui/assets/91047061/318b268f-a439-41f5-b1c2-1bd0b46ef0f9)

**Comment by tsadovska** [comment]
Tested OK.
* Correct colors are used on "Select asset" screen
* Correct colors are used in Route section
* Correct colors are used in "Add <token> to your wallet" link
* Correct color is used for loading icon
