### ISSUE TITLE
[bug] BONK contract address on Portal Bridge is different from contract address in Metamask 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

BONK contract address on Portal Bridge is different from contract address in Metamask. 

### Expected Behavior

Contract address is the same on wormhole-connect and in Metamask.

### Steps To Reproduce

1. Open https://portalbridge.com/ or https://preview.portalbridge.com/ 
2. Select Celo as source chain
3. Connect MetaMask wallet
4. Open Assets list
5. Open MetaMask extension 
6. Switch network to Celo
7. Check BONK token details

### Environment

```markdown
- OS: macOS 14.2.1 (23C71)
- Wallet: MataMask
- Browser: Google Chrome Version 122.0.6261.112 (Official Build) (arm64)
```

### Anything else?

Asset in Explorer: https://explorer.celo.org/mainnet/token/0x3fc50bc066aE2ee280876EeefADfdAbF6cA02894/token-transfers

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/84f904c8-6359-411c-a04f-8bfe773b6b6d)

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) on Celo.

**Comment by AigaD** [comment]
Precondition:
BONK asset available at Moonbeam network

Tested from:
https://preview.portalbridge.com/bceadc8c64/#

Attachment:
Contract address for BONK in Metamask: 0xbA2A7434AE628ed7B928e6A85E37Eb1583c9cfba

<img width="998" alt="Screenshot 2024-05-08 at 14 33 11" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d9c0f684-6233-488b-b746-cbecd7adc877">

**Comment by mliu-xlabs** [comment]
User Expectations should be the following:

1) When a user is selecting the source chain asset, the address that is displayed for the source asset should reflect the source asset address
2) When a user is selecting the destination chain asset, the address that is displayed for the destination asset should reflect the destination asset address
