### ISSUE TITLE
[bug] Warning messages have different colour contrasts 

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Colour contrast for warning messages "Wallet disconnected, please connect a supported wallet" and "Select an asset" are different

### Expected Behavior

Same colour is used for warning messages

### Steps To Reproduce

1. Select Solana Network at sending From section
2. Connect Solflare wallet
3. Enter the amount
4. Select e.g Celo at sending To section
5. Connect Metamask wallet
6. Change Solana Network to Aptos
7. Observe warning messages shown

### Environment

```markdown
- OS: macOS Ventura 13.0.1
- Wallet: Solflare, Metamask
- Browser: Chrome Version 121.0.6167.85
- Tested from: https://portalbridge.com/ / https://preview.portalbridge.com/b1ba6e856a/ and https://preview.portalbridge.com/b05f4e9322/#
```

### Anything else?

Attachment:

![Screenshot 2024-03-12 at 13 46 43](https://github.com/XLabs/portal-bridge-ui/assets/91047061/9c87458c-b4d8-4cf7-b05f-28b3cf87fce0)

![Screenshot 2024-03-12 at 13 43 58](https://github.com/XLabs/portal-bridge-ui/assets/91047061/318b268f-a439-41f5-b1c2-1bd0b46ef0f9)

**Comment by artursapek** [comment]
sorry these look the same to me. what in these screenshots is different?

**Comment by AigaD** [comment]
Sorry, perhaps in screenshot it is not well seen, but the warning messages have different number for hex background colour

<img width="1280" alt="Screenshot 2024-03-12 at 20 22 47" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/5166b340-34c9-4473-a88c-d092854230a8">

<img width="1316" alt="Screenshot 2024-03-12 at 20 23 13" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/a954051f-1f22-4ff5-b038-aceed5c9d8e9">

**Comment by AigaD** [comment]
Closing as per comment above
