### ISSUE TITLE
[bug] token registration - Non-base58 character

### ISSUE THREAD

**Issue by anondev2323** [XLabs/portal-bridge-ui#80]
Trying to register SOL on Moonbase Alpha. Can’t complete token registration because Step 3 fails with error “Error: Non-base58 character”

https://user-images.githubusercontent.com/122566365/232855492-521b5aa1-133d-4fc2-b110-4acef8bbd05a.mov

**Comment by sebastianscatularo** [comment]
that is wormhole-connect, it is a different project than portal bridge, maybe @M-Picco could help you with the correct place for this issue

**Comment by anondev2323** [comment]
Actually token registration isn't handled internally in Wormhole Connect, it links out. However, I did realize that for testnet it links to the example token bridge UI. My bad. I'll file the issue there
