### ISSUE TITLE
[support] <Ticket 9855 Solana to Algorand, unable to make TX>

### ISSUE THREAD

**Issue by Dahtank** [XLabs/portal-bridge-ui#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Operation Details

```markdown
- Source Chain: Solana
- Source Chain Wallet: N/A
- Target Chain: Algorand
- Target Chain Wallet: N/A
- Asset Type: Sol tokens
- Tx: N/A
```

### Current Behavior

Unable to start transfer, error in Step 3. After press transfer(the transaction not confirmed in 30 secs)

![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/5e180e68-8517-4ade-b60f-3568310a1067)
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/5900215c-8254-4b4c-a326-8035ff8bef71)

### Expected Behavior

Able to do Bridge route without issues
User has previously able to make this bridge route many times

### Steps To Reproduce

1. https://portalbridge.com/advanced-tools/#/transfer
2. Select Solana as Source Chain and Algorand as Target Chain
3. Connect the Solana wallet and select the SOL token, enter a valid amount of SOL
4. Connect the Algorand wallet and select Manual Payment
5. Click Transfer, approve the Solana wallet Pop up

### Anything else?

Mod Willis tested with same results
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/84ab8aea-c279-480b-a204-80a006afa1fe)
![image](https://github.com/XLabs/portal-bridge-ui/assets/141799468/f8fb51a3-1260-458d-84e3-a22516557a24)

**Comment by willis20188** [comment]
Hello
Any updates?

**Comment by sebastianscatularo** [comment]
@willis20188 this seems to be an issue related with solana network congestion/outage, apart from improve error handling, it is nothing else that we can do at this moment, I'll close this ticket
