### ISSUE TITLE
[support] wstETH (Arbitrum)  At the moment, amount cannot exceed 5

### ISSUE THREAD

**Issue by 8001800** [XLabs/portal-bridge-ui#810]
![Screenshot 2024-04-06 21 30 14](https://github.com/XLabs/portal-bridge-ui/assets/5697645/ffbb7e48-6c34-48f8-a1ca-5e3bdbb4077d)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Bridge Experience URL

https://portalbridge.com/

### Operation Details

```markdown
- Source Chain:arb
- Source Chain Wallet:
- Target Chain:eth
- Target Chain Wallet:
- Asset Type:wstETH (Arbitrum)
- Tx:
```

### Current Behavior

At the moment, amount cannot exceed 5  

### Expected Behavior

At the moment, amount can exceed 5  ,  reach the 500k $ cap if you can

**Comment by yuli-ferna** [comment]
To change this we need to include one item in the config

**Comment by sebastianscatularo** [comment]
we need to double check if this is in place to do not issues with governor limits, and ask connect folks what is the intention with the default value of 5

**Comment by yuli-ferna** [comment]
I was able to confirm that we should not change these limits for the pool. So I will close this issue.
