### ISSUE TITLE
[support] I can't redeem my SOL from BSC to solflare wallet

### ISSUE THREAD

**Issue by wizwow** [XLabs/portal-bridge-ui#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com/advanced-tools

### Operation Details

```markdown
- Source Chain: BSC
- Source Chain Wallet: Metamask
- Target Chain: Solana
- Target Chain Wallet: Solflare or Phantom (tried both)
- Asset Type: Token
- Tx: https://bscscan.com/tx/0xdb691061e8a90d28f08397321cb1ec907a8b534b958450f869a271d729b7baf3
```

### Current Behavior

I click on redeem, i approve the TX on my solflare or phantom wallet but the process remains stuck. It never completes. I have been trying for almost 24 hours and still can't get it to work.

![image](https://github.com/XLabs/portal-bridge-ui/assets/1069518/ea096562-483d-4be4-90e1-54c1caacc922)

**Comment by sebastianscatularo** [comment]
you tx shows up as redeemed you can check [here](https://wormholescan.io/#/tx/0xdb691061e8a90d28f08397321cb1ec907a8b534b958450f869a271d729b7baf3)
