### ISSUE TITLE
[bug] Our wrapped SPL token got deployed with metaplex metadata standard 1(FungibleAsset)  instead of metadata 2 (Fungible)

### ISSUE THREAD

**Issue by destructioneth** [XLabs/portal-bridge-ui#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, we are [crow with knife](https://www.coingecko.com/en/coins/crow-with-knife) , we recently expanded our reach to Solana via portal bridge.

Due to our token having 0 decimals, the wrapped wormhole token got deployed with metadata standard 1, this is significantly problematic as wallets and explorers are detecting it as an NFT.
![image](https://github.com/XLabs/portal-bridge-ui/assets/7505068/6b2b8fea-e1ff-4b7f-a436-9974690e7175)

### Expected Behavior

The SPL token metadata simply needs to be updated to tokenStandard 2. 

Since this requires a metadata update, we would like to update our "uri" field so it points to: https://www.crowwithknife.com/metadata.json

Thanks!

### Environment

```markdown
- OS:all
- Wallet:all
- Browser:all
```

**Comment by sebastianscatularo** [comment]
Hi @destructioneth, since the Token Bridge contract is permissionless, we do not have a way to manually update any kind of metadata. To update metadata, you need to attest the token by using https://portalbridge.com/advanced-tools/#/register or interacting directly with the blockchain itself. If the token has already been attested, the process must update the metadata instead.

You can check:

- https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0003_token_bridge.md#api--database-schema
- https://docs.wormhole.com/wormhole/explore-wormhole/vaa#attestation

**Comment by sebastianscatularo** [comment]
the decimals normalization, for evm happens here https://github.com/wormhole-foundation/wormhole/blob/main/ethereum/contracts/bridge/Bridge.sol#L288 for sure you can find similar functions on other smart contracts
here is the evm version for createWrapped https://github.com/wormhole-foundation/wormhole/blob/main/ethereum/contracts/bridge/Bridge.sol#L365, that is where the attest vaa should be redeemed or here if it is an update https://github.com/wormhole-foundation/wormhole/blob/main/ethereum/contracts/bridge/Bridge.sol#L385

for solana you can check:
- https://github.com/wormhole-foundation/wormhole/blob/main/solana/modules/token_bridge/program/src/api/create_wrapped.rs#L93
- https://github.com/wormhole-foundation/wormhole/blob/main/solana/modules/token_bridge/program/src/api/create_wrapped.rs#L191

**Comment by destructioneth** [comment]
So assuming we can't change the token decimal on the EVM side, you're telling me there's no possible way to update the metadata to the correct standard on the SOL side? I don't buy it.

There are messages on discord of users who have gotten metadata updates on SOL from the developers, there has to be a way

updateAuthority: "BCD75RNBHrJJpW4dXVagL5mPjzRLnVZq4YirJdjEYMV7" the update authority address is 

this is already our second time bridging to solana and it's a mess if we have to tell our community to bridge back to another contract again, and we also burnt $40k of LP on Raydium on this token, 

Are we really stuck with the wrong tokenStandard forever? Can we at least get the URI field updated so at least we get a picture on the NFT display since we're stuck with that ? 

https://www.crowwithknife.com/metadata.json

**Comment by sebastianscatularo** [comment]
well, asking partners, and checking the source code, we arrived to the next conclusion, when the Solana bridge was written that standard didn’t exist, and it’s never been updated to support, so, the token bridge contract needs an update to support token standard 2

**Comment by sebastianscatularo** [comment]
cc: @mliu-xlabs @chase-45 to be aware of it, it is out of our scope as UI, but, just in case

**Comment by sebastianscatularo** [comment]
I'll close this issue since it is an issue at contract level and not an issue at the UI

**Comment by destructioneth** [comment]
other wormhole wrapped tokens are deployed with the correct token standard 2, so it definitely is supported

here is an example of a wormhole wrapped token with the correct tokenStandard

https://solscan.io/token/ACE91xu5bSLHHKGtLjgrDtv8QkFN6a81QaGa5N8e9YWV
![image](https://github.com/XLabs/portal-bridge-ui/assets/7505068/30d76c5a-4b25-4256-bca2-c7f578b3240c)

the updateAuthority of the metaplex metadata is BCD75RNBHrJJpW4dXVagL5mPjzRLnVZq4YirJdjEYMV7 , this address has permission to edit the metadata so it can easily be fixed.

**Comment by destructioneth** [comment]
is there a correct channel to open issues for the contract level? thanks

**Comment by destructioneth** [comment]
it looks like the tokenStandard field might actually NOT be able to be updated, and if that is the case, my apologies.

assuming we're stuck with this standard though, we'd like to at least get our URI field pointing to this endpoint, so at least we get the picture on the NFT display: https://www.crowwithknife.com/metadata.json

some wallets such as solflare and backpack have been updated to properly support tokenStandard 1 so it might not be that bad.

**Comment by sebastianscatularo** [comment]
as far as I know, we do not have that ability. You could open an issue at https://github.com/wormhole-foundation/wormhole to see what other folks can do
