### ISSUE TITLE
[support] Issue Redeem portalbridge.com "App interaction Unknow" Solana Phantom

### ISSUE THREAD

**Issue by FouFou75** [XLabs/portal-bridge-ui#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Bridge Experience URL

https://portalbridge.com/advanced-tools/#/redeem

### Operation Details

```markdown
Source Chain: ATRADE BNB
Source Chain Wallet: Metamask
Target Chain: Solana
Target Chain Wallet: Phantom
Asset Type:  Token
Tx: 
https://bscscan.com/tx/0xf55bc16cace4350035608b413ef2f4b2e63c3b3375a5d80ea8d0041f36c9f377
error >>>  https://bscscan.com/tx/0xabca6686cf989fc0627a77af7ddad364d54780dd0a050c72aec7665d28b6d205
```

### Current Behavior

I have issue with https://portalbridge.com/advanced-tools/#/transfer
It does'nt work since 10 days after try several Time
I want transfert to my Phantom wallet sollana but each time error

### Steps To Reproduce

I follow the redeem process and each time error https://portalbridge.com/docs/faqs/troubleshooting#portal-bridge-troubleshooting

![image](https://github.com/XLabs/portal-bridge-ui/assets/167023343/14e8681f-5e60-466e-8cc7-b02bbb29bc85)

### Anything else?

It's urgent because I lost monney.... the price down ....

**Comment by sebastianscatularo** [comment]
we can see you trasaction was relayed and automatically redeemed, you can see the redeem tx [here](https://solscan.io/tx/4ovPc7QMvkWMFZKjtF6x8EsTyyisnzVxzvcdcackTW8kwi2CKLf3tnqxq7YRD9UAQe7pQ6HpHXUjVT2JAd6y17A5) and also you can check the status at [wormholescan](https://wormholescan.io/#/tx/0xabca6686cf989fc0627a77af7ddad364d54780dd0a050c72aec7665d28b6d205)
