### ISSUE TITLE
[support] The transaction is stuck Polygon -> Kujira (Ticket #11665）

### ISSUE THREAD

**Issue by willis20188** [XLabs/portal-bridge-ui#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain:Polygon
- Source Chain Wallet:0x9FcE4d8eF4b429cD92bD46e29640960c0c180B27
- Target Chain:Kujira
- Target Chain Wallet:kujira1tq92u36u2ucukmjgg66j7g93yg0x7t87ddpsfv
- Asset Type:USDC
- Tx:https://wormholescan.io/#/tx/0x2b9f42c960996f1d558244db6026232ef945d015e437b4eb0a21f88a96e1844b
```

### Current Behavior

Transaction stuck on Kujira side
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/abfa150d-b02d-4847-901d-be551fc7fc35)

**Comment by sebastianscatularo** [comment]
possible it was impacted by the guardian set update, checking the current status, the tx has been redeemed successfully, closing it
