### ISSUE TITLE
[support] Pending transfer to Osmosis, Ticket-7820

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain: Base
- Source Chain Wallet: Metamask 
- Target Chain: Osmosis 
- Target Chain Wallet:Keplr
- Asset Type:Token
- Tx: https://basescan.org/tx/0xb4712991be942543778b2254e25bae78bec0f9bebd03178140c60e6416aa64b7
```

### Current Behavior

![IMG_20240421_222320](https://github.com/XLabs/portal-bridge-ui/assets/64994788/2042684b-2bd2-41f5-8caa-f1450de6c3e7)

### Expected Behavior

Relay transfer to Osmosis 

### Steps To Reproduce

1, Go to https://portalbridge.com/
2, Click on the RESUME option on the bottom left
3, Choose Osmosis as Network
4. Paste in the transaction hash

### Anything else?

![IMG_20240421_222307](https://github.com/XLabs/portal-bridge-ui/assets/64994788/c63e96b8-61cd-4db3-bc3e-2d56819c1ddf)

**Comment by drisAloma** [comment]
These transactions face the same issue;
Ticket #11244
Source chain: Solana
Target chain: Osmo
Tx:
https://wormholescan.io/#/tx/28bkBvn1qeKCGzVgYv6rwbMYcPPdEiRm6mjGyDS6aFQvuhUiNzv3CanFLhRiGeMvPH9Vu5HEnb6VwhpEkTcY7MsZ

Ticket #11251
Source chain: Solana
Target chain: Osmo
Tx: https://wormholescan.io/#/tx/63cgQoH47zzX6naGyw2QMdrGPTMPVzBABKgwbXeyLesuDCHjoYkwYZbZ84S9mcDe6wpqhb9QpUXk27dpecYHYXLD

Ticket 11282
Source chain: Solana
Target chain: Osmo
Tx:
https://wormholescan.io/#/tx/4LHw8K5rcG8GnUHeHnDndcG4wfqKTnFPwHWwfnsUzXuRaxXmch8LdbuuQUMTz7FD9CyTiE23aH1Q19jUwjKYEqGc

**Comment by willis20188** [comment]
Ticket 11496
Source chain: Solana
Target chain: Osmo
Tx:
https://wormholescan.io/#/tx/2SoEZUgYiDbUP3tf4hUx4iJmmCf2c8KD5P4YicCUVxzau3AEuh2GmQjXVdVW3vkdV9tP7by3m3pfGEcV9thg1xK8

**Comment by sebastianscatularo** [comment]
@willis20188 @drisAloma seems to be, all the tx has been redeemed successfully, probably they got impacted by the guardian set update, then closing it.
