### ISSUE TITLE
[bug] W token contract address on Portal Bridge is different from contract address in Metamask 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

W token contract address on Portal Bridge is different from contract address in Metamask.

### Expected Behavior

Contract address is the same on wormhole-connect and in Metamask.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/3064c36d95/ 
2. Select Blast network as source chain
3. Connect MetaMask wallet
4. Open Assets list and search for W (Ethereum) asset
5. Open MetaMask extension
6. Switch network to Blast Mainnet
7. Check W token details

### Environment

```markdown
- OS: macOS Sonoma 14.4.1 
- Wallet: MetaMask
- Browser: Google Chrome Version 124.0.6367.208 (Official Build) (arm64)
```

### Anything else?

Asset in Explorer: https://blastscan.io/token/0x24c903d354b729188353ae3BbE4A9A7c4e11DC8b

![Screenshot 2024-05-14 at 13 38 54](https://github.com/XLabs/portal-bridge-ui/assets/10746654/99db7493-c548-4992-9073-b15a5c4c22e9)

**Comment by sebastianscatularo** [comment]
could you re try this @tsadovska, blast should not be available to select, but please test with other networks

**Comment by tsadovska** [comment]
Contract addresses on Portal Bridge https://portalbridge.com/ and in Metamask are the same for following tokens:
- W (Ethereum) on Ethereum, 0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91
- W (Solana) on Solana, 85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ
- W (Base) on Base, 0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91
- W (Arbitrum) on Arbitrum, 0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91
- W (Optimism) on Optimism, 0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91

Remaining issues:
- https://github.com/wormhole-foundation/wormhole-connect/issues/2283
- https://github.com/wormhole-foundation/wormhole-connect/issues/2282

Ticket is closed.
