### ISSUE TITLE
Update USDC Bridge to USDC Transfer in Advanced Tool

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#864]
Update USDC Bridge to USDC Transfer in Advanced Tool.

**Acceptance Criteria**
- Anywhere there is the term USDC Bridge should be renamed to USDC Transfer

This will not cover the changing of the URL

**Comment by yuli-ferna** [comment]
@mliu-xlabs this issue is relaed with https://github.com/XLabs/portal-bridge-ui-issues/issues/70 ?

**Comment by sebastianscatularo** [comment]
no, it is unrelated to that issue
