### ISSUE TITLE
Wallet Connect - Unable to retrieve token list on target token picker

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#87]
Originally reported: https://github.com/XLabs/portal-bridge-ui/issues/81#issuecomment-1521932779

```
I have a new issue in the token selection step so I can't get to the target account step:

When clicking ETH, wBTC or any of the tokens in the dropdown, I get: Unable to retrieve required information about this token. Ensure your wallet is connected, then refresh the list.

```

![Image](https://user-images.githubusercontent.com/1277510/235049164-13e75558-d834-4ed0-b073-d56d20001804.png)

**Comment by sebastianscatularo** [comment]
@d13co on what chains are experiencing this issue? Is it Ethereum to Algorand bridging? 

cc: @M-Picco

**Comment by d13co** [comment]
Yes, correct - when Algorand is selected as destination, the token list is shown with wBTC and ETH at the top, and clicking either of them produces this error.

**Comment by sebastianscatularo** [comment]
@d13co could you share a little more information on your setup? would be useful to know the wallets that you are using, I have been trying to reproduce it today unsuccessfully.

I think I would be in good shape knowing the wallet provider that you are using for Ethereum and Algorand

**Comment by sebastianscatularo** [comment]
@d13co please reopen the issue, if you do still have it.
