### ISSUE TITLE
[bug] Native balance is not loading for Aptos network

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Actual Result: Native balance is not loading.

### Expected Behavior

Expected result: Native balance is loading.

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Select Aptos network as source chain
3. Connect Rise/Petra wallet in From section
4. Open Assets list

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Rise/Petra
- Browser: Google Chrome Version 126.0.6478.57 (Official Build) (x86_64)
```

### Anything else?

<img width="1440" alt="Screenshot 2024-06-17 at 10 54 15" src="https://github.com/XLabs/portal-bridge-ui/assets/169661796/f958a22a-9678-4977-ac5f-b4a205f355c5">

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ [Mainnet]. APT asset balance is displayed. Checked with Rise and Petra wallets. 

https://github.com/user-attachments/assets/7f0b96ad-d965-41ad-bf24-703de23549c6

Ticket can be closed.

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is reproducible again, reopening the ticket. 
APT token balance is not loading for Aptos network. 

Attachment:
<img width="1438" alt="Screenshot 2024-09-09 at 09 44 27" src="https://github.com/user-attachments/assets/281a884d-c0b2-4b5d-a5b6-81b677874c10">

**Comment by agodlevska** [comment]
Closing the ticket as there is a more appropriate and updated ticket that better reflects the current situation. 
Please refer to #1079 for further details.
