### ISSUE TITLE
Review PR to reduce bundle size

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#91]
Action: review the PR

Outcome: 
- determine if still apply and check if this is the best option to reduce the bundle size
- explore other alternatives to reduce bundle size

https://github.com/XLabs/portal-bridge-ui/pull/62

**Comment by hernandiegosavio** [comment]
We are evaluating another bundler tool that could produce smaller bundle

- Parcel
- Vite

**Comment by sebastianscatularo** [comment]
won't fix
