### ISSUE TITLE
[bug] Duplicating tab opens main page instead of transaction continuation page

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user duplicates the tab, the Portal Bridge main page opens. This happens when user sends an asset from X Layer network. Instead, the page to continue the transaction should be shown.

https://github.com/user-attachments/assets/a63ed005-d58e-4387-9f41-898b750f781f

### Expected Behavior

Page to continue the transaction should be shown.

### Steps To Reproduce

1. Prepare to send 0.0001 WBNB from X Layer (MetaMask) to BSC (MetaMask)
2. Click on "Approve and proceed with transaction" button
3. Duplicate the tab

### Environment

```markdown
- OS: macOS Sonoma 14.5 
- Wallet: MetaMask
- Browser: Google Chrome Version 126.0.6478.183 (Official Build) (arm64)
```

**Comment by sebastianscatularo** [comment]
this is expected since feature branch does not support the routing mechanism that we have in prod
