### ISSUE TITLE
[bug] Cannot add WIF token to the wallet

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot add WIF token to the wallet. 

`Uncaught (in promise) {code: -32602, message: 'The symbol in the request (WIF) does not match the symbol in the contract ($WIF)'}`

![image](https://github.com/user-attachments/assets/dae3cc14-1a50-431a-a054-32c98d116f8b)

### Expected Behavior

Token can be added to the wallet. 

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Send 0.0001 WIF from Solana (Phantom) to Moonbeam (MetaMask)
3. Click on "Add WIF to your wallet" link

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Phantom
- Browser: Google Chrome Version 126.0.6478.183 (Official Build) (arm64)
```

**Comment by yuli-ferna** [comment]
@tsadovska It should be fixed :)
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/ad5a613b-5dc1-4437-b6d3-895576b85e17">

**Comment by tsadovska** [comment]
Thank you! 

Checked following scenarios:
* WIF transfer from Solana (Phantom) to Moonbeam (MetaMask)
* WIF transfer from Solana (Phantom) to Avalanche (MetaMask)
* WIF transfer from Avalanche (MetaMask via WalletConnect) to Fantom (MetaMask via WalletConnect)

When user clicks on"Add $WIF to your wallet" link, MetaMask notification opens  and token can be successfully added to the wallet.

Ticket is closed.
