### ISSUE TITLE
[bug] Incorrect error notification displayed for invalid manual wallet address input

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A notification "Error with transfer, please try again" appears when user enter invalid wallet address.

### Expected Behavior

A notification message should inform the user that the entered wallet address is not valid - "Not valid target address".

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/. 
2. Prepare to send 0.001 ETH from Ethereum (MetaMask) to BSC (invalid wallet address)
3. Manually input an incorrect wallet address.
4. Click on "Approve and proceed with transaction" button.

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, invalid wallet address input
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (x86_64)
```

### Anything else?

The console logs correctly indicate that the wallet address is invalid.

<img width="1439" alt="Screenshot 2024-08-02 at 10 02 41" src="https://github.com/user-attachments/assets/c66983cc-7c00-4c62-8a5b-89b3143f3e35">

**Comment by yuli-ferna** [comment]
@agodlevska could you give me the invalid address that you use in this test? :)

**Comment by agodlevska** [comment]
@yuli-ferna sure! I used a my half-erased wallet address, for example, 0xd493066498aCe409059fDA4. I don’t remember exactly up to which point it was erased, but it was something like this.

**Comment by yuli-ferna** [comment]
It should work now :)

<img width="683" alt="image" src="https://github.com/user-attachments/assets/aa484f2a-1efb-437b-8884-9edf7aea9928">

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/859350d189/ v0.2.15-P2b952cbfb3. 
The issue is no longer reproducible. The notification message is "Not valid target address" when user enters the invalid wallet address.
Closing the ticket. 

Attachment: 
<img width="454" alt="Screenshot 2024-08-05 at 10 08 12" src="https://github.com/user-attachments/assets/9a2bcef8-2aeb-4a6e-853e-ed36d8e7746d">
