### ISSUE TITLE
[bug] Cannot find token by contract address 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Search by contract address `3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh` shows "No results". 
Token in Explorer: https://solscan.io/token/3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh 

https://github.com/user-attachments/assets/e0e5f7e1-ae05-486e-b074-55a531be95cb

### Expected Behavior

Asset is found.

### Steps To Reproduce

1. Select Solana as source chain
2. Connect Phantom wallet
3. Open Assets list
4. Search for WBTC token by contract address "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Phantom
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
- Build: https://preview.portalbridge.com/859350d189/
```

**Comment by danielisaacgeslin** [comment]
@tsadovska the address in the example is incorrect. That was an older bug where assets were always showing addresses in their native chain rather than the one in the selected chain (wrapped)

**Comment by sebastianscatularo** [comment]
@danielisaacgeslin @tsadovska just keep in mind there exist native assets with addresses, and those should be searcheable,  the assets that does not have address are the fee payment assets like ETH, BTC, AVAX, but the wrapped version of them also exist and that does necessarily means wormhole wrapped, for instance WETH is the ERC20 representation over the native ETH, but, it is not a Wormhole wrapped

**Comment by danielisaacgeslin** [comment]
https://preview.portalbridge.com/859350d189/

**Comment by tsadovska** [comment]
Thank you! Issue is no longer reproducible on https://preview.portalbridge.com/859350d189/.

![image](https://github.com/user-attachments/assets/ed72fbfd-1185-4414-8a87-60a24eaef2b6)

Ticket is closed.
