### ISSUE TITLE
[bug] Manual route remains disabled after switching back to MetaMask

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Manual route remains disabled even after switching back to using a MetaMask wallet.

### Expected Behavior

When switching back to using the MetaMask wallet, the manual route should be re-enabled.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/.
2. Prepare to send 1 AVAX from Avalanche (MetaMask) to BSC (manual wallet address input).
3. Switch to using a MetaMask wallet in destination section. 
4. Observe that manual route remains disabled.

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, manual address input
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (x86_64)
```

### Anything else?

<img width="1440" alt="Screenshot 2024-08-02 at 11 35 09" src="https://github.com/user-attachments/assets/61c0e7ae-51cc-465b-a6ad-2d9c2adbc904">

**Comment by sebastianscatularo** [comment]
should be fixed once https://github.com/wormhole-foundation/wormhole-connect/pull/2317 gets merged 

https://github.com/user-attachments/assets/8ba148cc-d86d-472f-8d50-5149a66c1ebe

**Comment by tsadovska** [comment]
Re-checked on https://preview.portalbridge.com/859350d189/ [Mainnet]:
Manual route option can be selected after switching back to MetaMask, Phantom or Spika wallet. 
Ticket can be closed.
