### ISSUE TITLE
[bug] Manual entry of MetaMask address for Solana and Cosmos networks allows transaction initiation without error notification

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No error message or notification is displayed, allowing the transaction to be initiated with an incompatible wallet address.

### Expected Behavior

An error message or notification should appear indicating that the MetaMask wallet address is not suitable for Solana and Cosmos networks, preventing the initiation of the transaction.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/.
2. Prepare to send 0.001 WMATIC  from Arbitrum (MetaMask) to Osmosis (manual MetaMask wallet address input).
3. Click on "Approve and proceed with transaction" button.
4. Observe that the transaction can be initiated without any error message or notification about the incompatibility of the wallet address.

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, manual MetaMask wallet address input
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (x86_64)
```

### Anything else?

Transaction from [Arbitrum](https://arbiscan.io/tx/0x40990675fd82cc54e573053d341f38a8139d71583d8d19b236af7d0e402cd47d) (MetaMask) to [Osmosis](https://www.mintscan.io/osmosis/tx/7B3F6E4546B78515B5AE1E4E5A2CBE9C7C97DCE3B315FC3FFFE6344CD40AAE94) (MetaMask manual input), [Wormholescan](https://wormholescan.io/#/tx/0x40990675fd82cc54e573053d341f38a8139d71583d8d19b236af7d0e402cd47d). 

<img width="1421" alt="Screenshot 2024-08-02 at 12 28 45" src="https://github.com/user-attachments/assets/8bb32f7c-b47c-4088-a092-f32392606249">

<img width="1413" alt="Screenshot 2024-08-02 at 12 51 16" src="https://github.com/user-attachments/assets/62cfab1e-3f2a-4464-9398-bbb8e0cf9f40">

**Comment by tsadovska** [comment]
An error appears after user enters MetaMask wallet address instead of Solana wallet address:
```
Error: Non-base58 character
    at Object.ko [as decode] (pb-index-DkhI8Z9o.js:352:153069)
    at new ay (pb-index-DkhI8Z9o.js:352:245352)
    at SolanaContext.getNativeBalance (pb-index-DkhI8Z9o.js:508:191547)
    at WormholeContext.getNativeBalance (pb-index-DkhI8Z9o.js:511:626960)
    at pb-index-DkhI8Z9o.js:743:103673
    at Rj (pb-index-DkhI8Z9o.js:46:26759)
    at Ik (pb-index-DkhI8Z9o.js:46:46793)
    at Xk (pb-index-DkhI8Z9o.js:46:45486)
    at Qk (pb-index-DkhI8Z9o.js:46:44440)
    at Fk (pb-index-DkhI8Z9o.js:46:40700)
```

![image](https://github.com/user-attachments/assets/7f5305a1-1766-4443-8e91-00845b4e53d0)

**Comment by yuli-ferna** [comment]
@tsadovska @agodlevska It shuold be fixed :)
<img width="683" alt="image" src="https://github.com/user-attachments/assets/6f0754d7-fed8-43a8-be98-915cc1fab87d">

**Comment by tsadovska** [comment]
Thank you! 
Re-checked on https://preview.portalbridge.com/859350d189/ [Mainnet]. 
Warning 'Not valid target address' appears when an unsuitable wallet address is manually entered.
Ticket can be closed.
