### ISSUE TITLE
[bug] QR Code scanner is not working on Chrome Desktop

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

QR Code scanner is not working on Chrome Desktop. 

https://github.com/user-attachments/assets/b7fd46af-af1e-49b5-bd5d-8316850b47c5

### Expected Behavior

QR Code scanner icon is not displayed or is working. 

### Steps To Reproduce

1. Prepare to send ETH from Ethereum (MetaMask) to BSC
2. Click on "Connect wallet" button in "Send to" section 
3. Click on "Switch to Manual input" button
4. Click on QR Code icon

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
@sebastianscatularo Thank you! I can scan the QR Code, but wallet address includes network name. 

![Screenshot 2024-08-05 at 16 54 44](https://github.com/user-attachments/assets/21e0c6b3-e21d-4684-a5b5-bd31469fce01)

After entering transaction details and clicking on "Approve" button, transaction fails with "Not valid target address" error. Scenario checked: Send 0.04 AVAX from Avalanche (MetaMask) to Fantom (MetaMask, entered manually). 

```
Error validating transfer {chain: 'ethereum', address: 'ethereum:0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012', error: TypeError: (intermediate value) is not iterable
    at isSanctioned (https://preview.portalbridge.c…}
```

![image](https://github.com/user-attachments/assets/aa198664-ed55-45c7-8248-fb8126f9b651)

Incorrect address in displayed on Wormholecsan. It is opened with "Transactions" option from "To" wallet dropdown. 

![Screenshot 2024-08-05 at 17 03 50](https://github.com/user-attachments/assets/f325edd3-d76b-443b-8544-060e0a6aa4ab)

**Comment by tsadovska** [comment]
Re-checked on https://preview.portalbridge.com/859350d189/ [Mainnet]. Issue is still reproducible. 
Actual result: Wallet address includes network name.
Expected result: Wallet address does not include network name.

https://github.com/user-attachments/assets/790c6c8b-e4a2-424f-b287-0ca8db79f5df

**Comment by sebastianscatularo** [comment]
the network prefix is cleared after you click connect 


Uploading Screen Recording 2024-08-07 at 18.00.33.mov…

**Comment by tsadovska** [comment]
Thank you for the fix! Re-checked on https://preview.portalbridge.com/859350d189/. 
1. Correct wallet address is displayed in "To" section on the main screen after clicking on "Connect" button on "Manual Input" screen.
2. Transaction starts and completes successfully when wallet was connected with QR Code. Scenario checked: 0.001 AVAX from Avalanche to Fantom. 
3. Correct address is displayed on Wormholescan after clicking on "Transactions" option from dropdown menu in "To" section. 

Ticket is closed.
