### ISSUE TITLE
[bug] Token addresses not displayed for Klaytn, Scroll, X Layer networks

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only the address of wKLAY is displayed, and the addresses of other tokens are not visible.

### Expected Behavior

The addresses of all tokens should be displayed for the Klaytn network.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/.
2. Connect MetaMask wallet.
3. Open assets list.

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (x86_64)
```

### Anything else?

<img width="1440" alt="Screenshot 2024-08-02 at 16 43 55" src="https://github.com/user-attachments/assets/de5b9bb0-8f28-4733-bf63-3c06ba5d047e">

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/859350d189/. 
The issue is reproducible with Scroll, X Layer networks.

Attachments:
<img width="478" alt="Screenshot 2024-08-05 at 11 26 39" src="https://github.com/user-attachments/assets/eb3c0693-d75d-4ca1-b4bb-fac3960df539">
<img width="543" alt="Screenshot 2024-08-05 at 11 26 53" src="https://github.com/user-attachments/assets/ca59c7e4-4622-4b19-84ef-28ee8be895c6">

**Comment by danielisaacgeslin** [comment]
@agodlevska  the native token from each chain doesn't have an address

<img width="558" alt="image" src="https://github.com/user-attachments/assets/78babd43-c5d1-4cda-9135-569ba185ea44">

<br/><br/>

<img width="526" alt="image" src="https://github.com/user-attachments/assets/89e79e9e-1b9d-4a19-854f-911e9ba94c04">
