### ISSUE TITLE
[bug] W asset is not displayed on Assets screen

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Asset is not displayed in Available tokens list.

https://github.com/user-attachments/assets/60806933-21e8-4740-849f-e5fbaa946b5a

### Expected Behavior

Asset is displayed in Available tokens list.

### Steps To Reproduce

1. Send 0.01 W from Solana (Backpack) to Avalanche (MetaMask)
2. Click on the Avascan link and check if the transaction was completed successfully
3. Open https://portalbridge.com/
4. Select Avalanche network and check if asset is displayed in "Available tokens" list

### Environment

```markdown
- OS: macOS Sonoma 14.5 
- Wallet: Backpack, MetaMask
- Browser: Google Chrome Version 126.0.6478.183 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
Issue is also reproducible when sending 0.0001 W from Solana (Phantom) to BSC (MetaMask). Received asset is not displayed in "Available tokens" Tab and in "All tokens" tab.

- Send from tx: [Solana Explorer](https://explorer.solana.com/tx/3wtv6gbnJsdninpoDMrixv2xGEa1g2rtnUgqzRMFx9vUcnFGgkm9pTac6zP2n37Hzy9naFMfM5vv2ALWsbhJhtJt)
- Send to tx: [BscScan](https://bscscan.com/tx/0xf5095c953bd29a030e766ab2765a3f400532a647d420f309cd56f4a4a985b400)

![image](https://github.com/user-attachments/assets/4e47b008-3cdf-4c76-b348-a6cbe7279d79)

![image](https://github.com/user-attachments/assets/1a23e2a2-93ab-4cef-9783-8b29db610904)

**Comment by yuli-ferna** [comment]
Avax and BSC W tokens are not listed at this time as they do not have an NTT route.
