### ISSUE TITLE
[bug] Cannot add token to the wallet - W

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MetaMask notification does not open.

`Uncaught (in promise) {code: -32602, message: 'The decimals in the request (18) do not match the decimals in the contract (6)'}`

![image](https://github.com/user-attachments/assets/7b360515-51a6-4b2a-a096-d9e97e9e988f)

### Expected Behavior

MetaMask notification is opened.

### Steps To Reproduce

Steps:
1. Send 0.01 W from Solana (Backpack) to Avalanche (MetaMask)
2. Click on "Add W to your wallet" link

### Environment

```markdown
- OS: macOS Sonoma 14.5 
- Wallet: Backpack, MetaMask
- Browser: Google Chrome Version 126.0.6478.183 (Official Build) (arm64)
- Build:  https://portalbridge.com/
```

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/321a610744/ (Portal Bridge: v0.2.15-P22997d4780, Wormhole Connect: v^0.3.20-beta.4-development). 

The W token was successfully added to MetaMask and Rabby wallets.
Ticket can be closed.
