### ISSUE TITLE
[bug] Contract address for BONK asset is not displayed

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Contract address for BONK asset is not displayed.

![image](https://github.com/user-attachments/assets/11f645bd-dd70-4b48-8df0-aea88a387fb3)

### Expected Behavior

Contract address for BONK asset is displayed.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Select Celo network as source chain and connect MetaMask wallet
3. Open Assets list
4. Check Contract address for BONK token

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask 
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by danielisaacgeslin** [comment]
![image](https://github.com/user-attachments/assets/dabc93b0-726c-4d8a-8530-e33ba15a62e1)
