### ISSUE TITLE
[bug] USDT contract address is not checksummed

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

USDT contract address is not checksummed. 

![image](https://github.com/user-attachments/assets/21039f4f-8b94-4095-9298-c954cd908a71)

### Expected Behavior

Contract address is displayed with uppercase and lowercase letters, 0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Select Avalanche as source chain and connect MetaMask wallet
3. Open Asset list
4. Check contract address for USDT 

### Environment

```markdown
- OS: macOS Sonoma 14.5 
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by yuli-ferna** [comment]
@tsadovska Fixed! :)
<img width="479" alt="image" src="https://github.com/user-attachments/assets/39a023b1-4f93-4aa3-b2f4-f648712e86f0">

**Comment by tsadovska** [comment]
Tested OK on https://preview.portalbridge.com/859350d189/. 
Ticket is closed.
