### ISSUE TITLE
[bug] User can click on "Connect" button without entering a Wallet Address

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User can click on "Connect" button without entering a Wallet Address. 

https://github.com/user-attachments/assets/edc403e1-b50b-4601-b5ca-d038b22c7d5c

### Expected Behavior

A warning that the wallet address is not entered is displayed or "Connect" button is inactive.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Select Fantom as source chain
3. Select Avalanche as destination chain
4. Connect MetaMask wallet in From section
5. Click on "Connect wallet" button in To section
6. Switch to Manual Input
7. Click on "Connect" button without entering a Wallet Address 

### Environment

```markdown
- OS: macOS Sonoma 14.5 
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by sebastianscatularo** [comment]
Issue addressed at https://github.com/wormhole-foundation/wormhole-connect/pull/2323

**Comment by tsadovska** [comment]
Re-checked on https://preview.portalbridge.com/859350d189/ [Mainnet]. 
"Connect" button remains inactive until user enters a wallet address.
Ticket is closed.
