### ISSUE TITLE
[bug] Cannot Claim token if destination address was entered manually - Cosmos Gateway Manual route

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot Claim token on Aptos if destination address was entered manually. 

```
TypeError: u.signAndSendTransaction is not a function
    at signAndSendTransaction (aptos-FL7F0RS8-Bxv3BExQ.js:34:301903)
    at signAndSendTransaction (pb-index-D87dar2w.js:516:72842)
    at async BridgeRoute.redeem (pb-index-D87dar2w.js:516:92030)
    at async Operator.redeem (pb-index-D87dar2w.js:519:94472)
    at async Object.Nr [as onClick] (pb-index-D87dar2w.js:746:1327)
```

![image](https://github.com/user-attachments/assets/8c4470f6-9589-4607-9f48-0c3d34805dc0)

### Expected Behavior

Cosmos manual route should not be allowed. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Select Osmosis as source chain and Aptos as destination chain
3. Connect Leap wallet in From section
4. Connect Spika wallet in To section (enter address manually)
5. Click on "Approve and proceed with transaction" button
6. Click on "Claim" button

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Leap, Spika
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by sebastianscatularo** [comment]
manual address enter should only be available for routes and chains that supports relays, this escenario should not exist by definition, good catch

**Comment by sebastianscatularo** [comment]
PR to address this issue https://github.com/wormhole-foundation/wormhole-connect/pull/2322

**Comment by tsadovska** [comment]
Re-checked on https://preview.portalbridge.com/859350d189/.
Scenario "0.0001 USDT transfer from Osmosis (Leap) to Aptos (Wallet address entered manually)" can be reproducible. 
Please use this [link](https://drive.google.com/file/d/1crFoeX85a4bxp9F3lwqW7O6m6Be4Yw5Q/view?usp=sharing) to view the recording. 
I cleared the cache and did a hard reload before starting the transfer.

![image](https://github.com/user-attachments/assets/885d7721-2ab4-479c-854f-04688933d5ba)

**Comment by tsadovska** [comment]
Re-checked on https://preview.portalbridge.com/859350d189/. 'Cosmos Gateway Manual Route' route is now displayed as disabled when sending USDT from Osmosis (Leap) to Aptos (Manually entered wallet address). However, transfer can still be started. Please use [this link ](https://drive.google.com/file/d/116OoZcPqk7t7J-nnGc5dbuK7O7mS9TPL/view?usp=sharing) to view the recording. 

[Scenario](https://github.com/XLabs/portal-bridge-ui/issues/980#issuecomment-2271714006) will be re-checked after https://github.com/XLabs/portal-bridge-ui/issues/999 is resolved.

**Comment by tsadovska** [comment]
Re-checked on https://portalbridge.com/.
1. "Cosmos Gateway Manual route" is disabled when destination address is entered manually.
2. "Approve and proceed with transaction" button is not displayed after user clicks on route option when destination address is entered manually. 
Ticket is closed.
