### ISSUE TITLE
[bug] Transaction fails with "Not valid target address" error when valid wallet address is connected

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails. 

```
Error validating transfer {chain: 'cosmos', address: 'inj1mqq0u6w0yetxgct4sk53pncaqzz0eml8j2ap97', error: TypeError: (intermediate value) is not iterable
    at isSanctioned (https://preview.portalbridge.c…}
```

![image](https://github.com/user-attachments/assets/b41358b2-de14-4dd1-a779-91da25ecc1ed)

### Expected Behavior

Transaction proceeds without errors. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ 
2. Prepare to send 0.0001 W from Base (MetaMask) to Injective (Leap)
3. Click on "Approve and proceed with transaction" button
 

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Leap, MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

### Anything else?

Issue is not reproducible on https://portalbridge.com/.

**Comment by yuli-ferna** [comment]
@tsadovska I fixed the cosmos address validations

<img width="1550" alt="Captura de pantalla 2024-08-06 a las 9 10 59 a m" src="https://github.com/user-attachments/assets/d3c86ac3-7caa-4cf1-9f78-fa42d0cc52e9">
