### ISSUE TITLE
[bug] Warning "Not valid target address" does not disappear after valid wallet account is connected

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Warning "Not valid target address" does not disappear after valid wallet is connected.

![image](https://github.com/user-attachments/assets/02c7550a-58bc-47b1-9cd5-2a4fb7053017)

### Expected Behavior

Warning is no longer displayed. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ 
2. Prepare to send 5 FTM from Fantom (MetaMask) to Solana (invalid wallet address)
3. Click on "Approve and proceed with transaction" button
4. Connect valid Solana account
5. Check if "Not valid target address" warning is displayed

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Phantom
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by yuli-ferna** [comment]
PR related: https://github.com/wormhole-foundation/wormhole-connect/pull/2336

**Comment by yuli-ferna** [comment]
@tsadovska Should be fixed :)

https://github.com/user-attachments/assets/edb20a01-c717-4f0d-93b3-afcdb793f533

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/859350d189/ [Mainnet].

* Warning disappears after user connects the wallet
* Warning disappears after user manually enters valid account address 

Ticket is closed.
