### ISSUE TITLE
[bug] OFAC Check: Warning "This address is sanctioned" is not shown 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Warning "This address is sanctioned" is not shown. 
 
 
![image](https://github.com/user-attachments/assets/83ce222a-7cea-4685-9f25-0932743f98d9)

### Expected Behavior

 Warning "This address is sanctioned" is shown. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ 
2. Prepare to send 0.1 AVAX from Avalanche (MetaMask) to Fantom (Wallet address from https://github.com/ultrasoundmoney/ofac-ethereum-addresses, 0x8576acc5c05d6ce88f4e49bf65bdf0c62f91353c)
3. Check if warning  "This address is sanctioned" is displayed

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, https://github.com/ultrasoundmoney/ofac-ethereum-addresse
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by yuli-ferna** [comment]
@tsadovska The message appears when you click on "Approve and proceed with transaction":

<img width="757" alt="image" src="https://github.com/user-attachments/assets/6edc6aa4-00b3-4526-a418-2c0a0a8e57ba">

**Comment by tsadovska** [comment]
@yuli-ferna Noticed that warning is not displayed after user clicks on "Approve and proceed with transaction" button with following scenario:
1. Prepare to send 0.1 USDC from Polygon (MetaMask) to Arbitrum
2. Manually enter wallet address 0x1da5821544e25c636c1417ba96ade4cf6d2f9b5a (Sanctioned target address)
3. Click on "Approve and proceed with transaction" button

Actual result: MetaMask notification opens. Please use this link to view the [recording](https://drive.google.com/file/d/10kG1bICglHYg_wRnq49PfCo9AbaAtiP4/view?usp=sharing). 

![image](https://github.com/user-attachments/assets/4d728775-db78-4818-a2c0-4cc3a605d0d6)


Issue is not reproducible with 0xd882cfc20f52f2599d84b8e8d58c7fb62cfe344b wallet address (also sanctioned target address).

**Comment by sebastianscatularo** [comment]
I think that is expected, since it is the contract approval before the actual check

**Comment by yuli-ferna** [comment]
@tsadovska should be fixed :) https://portalbridge.com/

<img width="683" alt="image" src="https://github.com/user-attachments/assets/e9a48cf2-6094-4df1-92ee-9d35c930b114">

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/. 
Warning that address is sanctioned is displayed after sanctioned wallet address is entered or after user clicks on "Approve and proceed with transaction" button.
Ticket is closed.
