### ISSUE TITLE
[bug] "Circle CCTP Manual route" becomes available after user closes Solana wallet 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Circle CCTP Manual route" is not disabled. 

https://github.com/user-attachments/assets/e06d9bdc-f59a-4ef7-8d8c-71250d875427

### Expected Behavior

"Circle CCTP Manual route" is disabled. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Prepare to send 0.1 USDC from Polygon (MetaMask) to Solana (Wallet address entered manually)
3. Click on wallet address in "To" section and select "Change wallet" option from dropdown menu
4. Select Pontem option
5. Close Pontem notification
6. Check if "Circle CCTP Manual route" can be selected 

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Pontem
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

### Anything else?

Similar issue: https://github.com/XLabs/portal-bridge-ui/issues/990

**Comment by mliu-xlabs** [comment]
this Is expected since there is not an automatic route for CCTP to solana yet
