### ISSUE TITLE
[bug] Typo in warning message

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Warning message contains typo. 
Warning is shown: "Sanctionated target address". 

![image](https://github.com/user-attachments/assets/f3a7f267-f101-441a-b58c-21f9768fc985)

### Expected Behavior

Warning is shown: "Sanctioned target address". 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ [Mainnet]
2. Prepare to send 0.07 AVAX from Avalanche (MetaMask) to Fantom
3. Manually enter sanctioned wallet address, 0x8576acc5c05d6ce88f4e49bf65bdf0c62f91353c
4. Click on "Approve and proceed with transaction" button
5. Check the warning message

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by bradstevens1** [comment]
Are you able to solve your issues now ?

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://preview.portalbridge.com/859350d189/.

![image](https://github.com/user-attachments/assets/2250464c-a245-492a-87ca-82a6481cd817)

Ticket is closed.
