### ISSUE TITLE
[bug] Transaction fails with "call revert exception" error

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails. 

```
Wormhole Connect: error completing transfer Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="quoteDeliveryPrice(uint16,bytes)", data="0x9449a36c0000000000000000000000000000000000000000000000000000000000000001", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at M1.makeError (pb-index-CZhFlO9z.js:349:47781)
    at M1.throwError (pb-index-CZhFlO9z.js:349:47914)
    at Interface.decodeFunctionResult (pb-index-CZhFlO9z.js:350:14713)
    at Contract.<anonymous> (pb-index-CZhFlO9z.js:359:25500)
    at Generator.next (<anonymous>)
    at _r (pb-index-CZhFlO9z.js:359:20132)
```

![image](https://github.com/user-attachments/assets/cbe6b1f7-bef5-4d12-90f4-ee5173bb3371)

### Expected Behavior

Transaction proceeds without errors. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Prepare to send 1 Yaku from Avalanche (MetaMask) to Solana (Phantom)
3. Select NTT Automatic route
4. Click on "Approve and proceed with transaction" button

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Phantom
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

### Anything else?

Linked issue: https://github.com/XLabs/portal-bridge-ui/issues/995

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/b3b7091778/. 
Unable to claim on Mantle when sending 0.5 WTFM from X Layer (Rabby) to Mantle (Rabby) through Manual route. 

Error message in console: 
```
Error: call revert exception; VM Exception while processing transaction: reverted with reason string "invalid emitter" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="completeTransfer(bytes)", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f696e76616c696420656d69747465720000000000000000000000000000000000", errorArgs=["invalid emitter"], errorName="Error", errorSignature="Error(string)", reason="invalid emitter", code=CALL_EXCEPTION, version=abi/5.7.0)
    at D1.makeError (pb-index-DohA4Xao.js:376:47781)
    at D1.throwError (pb-index-DohA4Xao.js:376:47914)
    at Interface.decodeFunctionResult (pb-index-DohA4Xao.js:377:14713)
    at Object.<anonymous> (pb-index-DohA4Xao.js:386:25500)
    at Generator.next (<anonymous>)
    at _r (pb-index-DohA4Xao.js:386:20132)
``` 
Attachment:
<img width="1440" alt="Screenshot 2024-08-27 at 16 54 28" src="https://github.com/user-attachments/assets/6a9fa569-c03f-4c9e-a0a8-0dc9e1771a3a">

**Comment by tsadovska** [comment]
Closing the ticket, because Yaku token is no longer displayed in the tokens list on Avalanche and token balances are not displayed on X Layer (ticket https://github.com/XLabs/portal-bridge-ui/issues/1099). I haven't noticed the issue with different scenarios.
