### ISSUE TITLE
[bug] Transaction to Injective is stuck at Step 2 and transfer from Injective fails to start

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction is stuck at Step 2 for 13 hours. 
* Transaction: https://preview.portalbridge.com/859350d189/?sourceChain=base&transactionId=0x5e366ebf79d22dac0df330c62ac9259273d0837a1247e3f2454f73b458e43bf9
* Send from tx: [BaseScan](https://basescan.org/tx/0x5e366ebf79d22dac0df330c62ac9259273d0837a1247e3f2454f73b458e43bf9)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x5e366ebf79d22dac0df330c62ac9259273d0837a1247e3f2454f73b458e43bf9)

Error in Console:
```
Error: Invalid string. Length must be a multiple of 4
    at getLens$1 (pb-index-Bt7Weqss.js:134:101942)
    at Object.toByteArray$1 (pb-index-Bt7Weqss.js:134:102257)
    at fromBase64 (pb-index-Bt7Weqss.js:519:158848)
    at decodeAttribute (pb-index-Bt7Weqss.js:522:45748)
    at Array.map (<anonymous>)
    at decodeAttributes$1 (pb-index-Bt7Weqss.js:522:45944)
    at decodeEvent$1 (pb-index-Bt7Weqss.js:522:46037)
    at Array.map (<anonymous>)
    at decodeEvents$1 (pb-index-Bt7Weqss.js:522:46181)
    at decodeTxData$1 (pb-index-Bt7Weqss.js:522:46428)
```

![image](https://github.com/user-attachments/assets/f7ac6ceb-1490-4738-8036-36d41680f1aa)

![image](https://github.com/user-attachments/assets/2066a5b0-ecb9-4094-a81c-3aeb32e797ad)

### Expected Behavior

Transaction is successfully completed.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/
2. Prepare to send 0.00011 W from Base (MetaMask) to Injective (Leap)
3. Click on "Approve and proceed with transaction" button
4. Click on "View on Wormholescan" link and wait until transaction status changes to "Completed"
5. Check Step 2 on Portal Bridge
6. Check for errors in Console

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Leap
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
Issue is also reproducible on https://portalbridge.com/ when sending 1 BONK from BSC (MetaMask) to Injective (Leap) 
* Transaction: https://portalbridge.com/?sourceChain=bsc&transactionId=0xb4eb3273d281c2ca33fdc800a265608afcc3eab78e83bcb38cc5583528e250fb
* Send from tx: [BscScan](https://bscscan.com/tx/0xb4eb3273d281c2ca33fdc800a265608afcc3eab78e83bcb38cc5583528e250fb)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xb4eb3273d281c2ca33fdc800a265608afcc3eab78e83bcb38cc5583528e250fb)

![image](https://github.com/user-attachments/assets/cfb0da77-25fc-4098-8250-4b57fd837a42)

**Comment by tsadovska** [comment]
Transaction fails with the same error after clicking on "Approve and proceed with transaction" button when sending WMATIC from Injective (Leap) to Solana (Phantom). 

```
Wormhole Connect: error completing transfer Error: Invalid string. Length must be a multiple of 4
    at getLens$1 (pb-index-Zet3Zyve.js:134:101879)
    at Object.toByteArray$1 (pb-index-Zet3Zyve.js:134:102194)
    at fromBase64 (pb-index-Zet3Zyve.js:519:158848)
    at decodeAttribute (pb-index-Zet3Zyve.js:522:45748)
    at Array.map (<anonymous>)
    at decodeAttributes$1 (pb-index-Zet3Zyve.js:522:45944)
    at decodeEvent$1 (pb-index-Zet3Zyve.js:522:46037)
    at Array.map (<anonymous>)
    at decodeEvents$1 (pb-index-Zet3Zyve.js:522:46181)
    at decodeTxData$1 (pb-index-Zet3Zyve.js:522:46428)
```


![image](https://github.com/user-attachments/assets/92b2f11d-764b-4bb5-84d9-b7fdcf65cde3)

**Comment by tsadovska** [comment]
Re-checked on https://portalbridge.com/.
1. Transfers to Injective completes successfully.
* W transfer from Base (MetaMask) to Injective (Leap)
  * Send from tx: [BaseScan](https://basescan.org/tx/0xe37768d42377e157d9ff5e398a471f343baa04699f208809ca3fb61f7d8084b7)
  * Send to tx: [Injective Explorer](https://explorer.injective.network/transaction/93DE520C61BD655341C42E465D8C10E8534F68D691BD680996C4BC1D23C7A730/)
* BONK transfer from BSC (MetaMask) to Injective (Leap)
  * Send from tx: [BscScan](https://bscscan.com/tx/0x4ed5d45b0b53458db67ee10aab68406c15dd54de2729061a5b49959da94cea88)
  * Send to tx: [Injective Explorer](https://explorer.injective.network/transaction/E42A281BB1F54E1B3C8656ED02812F749BEFA05315FF4061CB74D4AD25701C2D/)
2. Transfers from Injective fails after clicking on "Approve and proceed with transaction" button.

![image](https://github.com/user-attachments/assets/e5323ff9-daf2-4edb-a8a6-a33ab93903b1)

**Comment by sebastianscatularo** [comment]
yes, portal does not have the last connect version in place, will update it asap and let you know to re try

**Comment by sebastianscatularo** [comment]
portal has been updated, please re check when ever you get some spare time

**Comment by tsadovska** [comment]
Thank you! Issue is no longer reproducible on https://portalbridge.com/.

Checked following transfers:
* WMATIC from [Injective](https://explorer.injective.network/transaction/D3B31A235A83FABEA6348790E4620262D07FC7319C497ACC35E7340379F2A282/) (Leap) to [Solana](https://explorer.solana.com/tx/3zrHQ31YfWvLK6aCGiAQrdjvbfKNh8xcQyVJS6rbpvx1cTJniPhbRzFqoMtpJ89QywHrKMNqC3XJGKsog8ap28Ju) (Phantom) 
* WMATIC from [Injective](https://explorer.injective.network/transaction/DA2BF31D1F5756A7A8CE1715542FF0DA6A7E3735D2FAF8F3E356387FC13FF0F9/) (Leap) to [Avalanche](https://avascan.info/blockchain/c/tx/0xceef1c2b910796753d77959210ca758e48d74f9e629aeac9a19bbf2c5856a1af) (MetaMask)

Ticket is closed.
