### ISSUE TITLE
[bug] "Manual Bridge" route becomes unavailable when user enables manual address input without entering a wallet address

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Manual Bridge" route becomes unavailable when user enables manual address input without entering a wallet address. 

https://github.com/user-attachments/assets/20081f1b-7f07-4058-912a-6dde3750dc85

### Expected Behavior

"Manual Bridge" route can be chosen because the wallet address was not entered manually.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ 
2. Prepare to send 0.001 AVAX from Avalanche (MetaMask) to Aptos (Pontem)
3. Click on wallet address in "To" section and select "Change wallet" from dropdown menu
4. Enable Manual Input 
5. Click on "Close" button 
6. Check if "Manual Bridge" route can be selected 

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Pontem
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by sebastianscatularo** [comment]
should be fixed once https://github.com/wormhole-foundation/wormhole-connect/pull/2349 get merged

**Comment by tsadovska** [comment]
Re-checked the scenario from the Description:
1. Open https://preview.portalbridge.com/859350d189/
2. Prepare to send 0.001 AVAX from Avalanche (MetaMask) to Aptos (Pontem)
3. Click on wallet address in "To" section and select "Change wallet" option from dropdown menu
4. Enable Manual Input
5. Click on "Close" button
6. Check if "Approve" button is displayed


Actual result: "Manual Bridge" route is available, but "Approve and proceed with transaction" button appears only after user clicks on the route option. 

https://github.com/user-attachments/assets/95909fc7-6741-4a0e-9868-5b76961dc783

Issue will be re-checked once https://github.com/XLabs/portal-bridge-ui/issues/1004 is solved.

**Comment by yuli-ferna** [comment]
@tsadovska This should be fixed and the issue https://github.com/XLabs/portal-bridge-ui/issues/1004 too

https://github.com/user-attachments/assets/db61e056-ba23-4be1-a481-b94e2349eaa2

**Comment by tsadovska** [comment]
Tested OK on https://portalbridge.com/. 
Ticket is closed.
