### ISSUE TITLE
[bug] Possible to start a transfer with disabled route

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Token transfer starts. Please use [this link](https://drive.google.com/file/d/1PvH-Fl5sEL7zqNEh1MSMQP2BrXaWBpeo/view?usp=sharing) to view the recording. 

![image](https://github.com/user-attachments/assets/2ac5507e-c092-4d62-9b22-05df5358a15a)

Transaction fails after clicking on "Claim" button.
```
TypeError: Cannot read properties of undefined (reading 'publicKey')
    at postVaa (pb-index-CjRBRb8w.js:527:70153)
    at BridgeRoute.redeem (pb-index-CjRBRb8w.js:527:88437)
    at Operator.redeem (pb-index-CjRBRb8w.js:537:139030)
    at Object.wo [as onClick] (pb-index-CjRBRb8w.js:764:1347)
    at gr (pb-index-CjRBRb8w.js:761:25536)
    at Object.Nb (pb-index-CjRBRb8w.js:43:10486)
    at Tb (pb-index-CjRBRb8w.js:43:10655)
    at Ub (pb-index-CjRBRb8w.js:43:10721)
    at nf (pb-index-CjRBRb8w.js:43:33594)
    at se$1 (pb-index-CjRBRb8w.js:43:34071) 
```

### Expected Behavior

It should not be possible to start a transfer when the route is disabled.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ [Mainnet] 
2. Prepare to send 0.0001 AVAX from Avalanche (MetaMask) to Solana (Wallet address entered manually)
3. Select "Manual Bridge" route
4. Click on "Approve and proceed with transaction" button

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.89 (Official Build) (arm64)
```

**Comment by yuli-ferna** [comment]
@tsadovska should be fixed :) https://portalbridge.com/

<img width="711" alt="image" src="https://github.com/user-attachments/assets/5249aa53-5fb1-4db0-b41d-5b2ef1258432">

**Comment by tsadovska** [comment]
@yuli-ferna [The original scenario](https://github.com/XLabs/portal-bridge-ui/issues/999#issue-2455463069) is no longer reproducible on https://portalbridge.com/, but it is still posible to start a transfer with "Manual Bridge" route with the scenario mentioned in the https://github.com/XLabs/portal-bridge-ui/issues/999#issuecomment-2277906014:

1. Prepare to send 0.0001 AVAX from Avalanche (MetaMask) to Solana (Wallet address entered manually)
2. Click on wallet address in "To" section and select "Change wallet" option from dropdown menu
3. Close the "Connect wallet" window
4. Click on "Approve and proceed with transaction" button


Actual result: "Manual Bridge" route becomes available. 

https://github.com/user-attachments/assets/796b2333-8eca-46f0-a7ee-a5e1210870bb

**Comment by agodlevska** [comment]
Checked on https://preview.portalbridge.com/321a610744/ (Portal Bridge: v0.2.15-P22997d4780, Wormhole Connect: v^0.3.20-beta.4-development).

Everything looks good now. If the automatic route is available, the error message does not occur. 
The ticket can be closed.

Attachments:
<img width="1440" alt="Screenshot 2024-08-21 at 10 14 15" src="https://github.com/user-attachments/assets/80edcb3a-22f6-4827-9697-dda03fc3b397">
<img width="1440" alt="Screenshot 2024-08-21 at 10 14 25" src="https://github.com/user-attachments/assets/57c8e139-cce1-41f3-ab76-0cebc1a033e4">
